### ISSUE TITLE
Deprecation: #85012 - GetValidationResults of Argument:class and Arguments::class


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#1059]
Deprecation: #85012 - GetValidationResults of Argument:class and Arguments::class

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.3/Deprecation-85012-OnlyValidateMethodParamsIfNeeded.html

.. include:: ../../Includes.txt

=================================================================================

Deprecation: #85012 - GetValidationResults of Argument:class and Arguments::class

=================================================================================

See :issue:`85012`

Description

===========

The following public methods have been marked as deprecated:

* :php:`TYPO3\CMS\Extbase\Mvc\Controller\Argument::getValidationResults()`

* :php:`TYPO3\CMS\Extbase\Mvc\Controller\Arguments::getValidationResults()`

Impact

======

Calling the method will trigger a PHP :php:`E_USER_DEPRECATED` error.

Affected Installations

======================

Extensions that call any of the methods. The extension scanner will find usages.

Migration

=========

Use the following methods instead:

* :php:`TYPO3\CMS\Extbase\Mvc\Controller\Argument::validate()`

* :php:`TYPO3\CMS\Extbase\Mvc\Controller\Arguments::validate()`

.. index:: PHP-API, FullyScanned, ext:extbase

**Comment by tomasnorre** [comment]
I could take a look at this too. When the first one is finished.

**Comment by sabbelasichon** [comment]
For this one i think you can use a so called configurable Rector: https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#renamemethodrector

**Comment by sabbelasichon** [comment]
No need for stubs and tests. The only thing that´s left is how to communicate that typo3-rector is doing this change for you. Because the configurable rectors are not part of the documentation.
