### ISSUE TITLE
Deprecation: #85759 - GeneralUtility::getHostName


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#1110]
Deprecation: #85759 - GeneralUtility::getHostName

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85759-GeneralUtilitygetHostName.html

.. include:: ../../Includes.txt

=================================================

Deprecation: #85759 - GeneralUtility::getHostName

=================================================

See :issue:`85759`

Description

===========

The method :php:`GeneralUtility::getHostName()` has been marked as deprecated and will be removed in TYPO3 v10.

Impact

======

Calling the mentioned method will trigger a PHP :php:`E_USER_DEPRECATED` error.

Affected Installations

======================

Third party code which accesses the method.

Migration

=========

No migration available.

.. index:: PHP-API, FullyScanned

**Comment by sabbelasichon** [comment]
Just copy the method over

**Comment by sabbelasichon** [comment]
Not worth it.

**Comment by ayacoo** [comment]
Short question: Why is it not worth it? Because it is not used in the community?

I would simply replace \TYPO3\CMS\Core\Utility\GeneralUtility::getHostname() with \TYPO3\CMS\Core\Utility\GeneralUtility::getIndpEnv('HTTP_HOST')

**Comment by typoworx-de** [comment]
Such things should be noticed in ```@deprecated``` annotation.
