### ISSUE TITLE
Deprecation: #85807 - EnvironmentService::isEnvironmentInCliMode


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#1113]
Deprecation: #85807 - EnvironmentService::isEnvironmentInCliMode

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85807-EnvironmentServiceisEnvironmentInCliMode.html

.. include:: ../../Includes.txt

================================================================

Deprecation: #85807 - EnvironmentService::isEnvironmentInCliMode

================================================================

See :issue:`85807`

Description

===========

The method :php:`TYPO3\CMS\Extbase\Service\EnvironmentService::isEnvironmentInCliMode()` has been marked as deprecated.

Impact

======

Calling the method will trigger a PHP :php:`E_USER_DEPRECATED` error.

Affected Installations

======================

Any TYPO3 installation with a custom extension calling the method above.

Migration

=========

Use :php:`TYPO3\CMS\Core\Core\Environment::isCli()` as replacement.

.. index:: PHP-API, FullyScanned, ext:extbase

**Comment by verdure-peuser** [comment]
this seems already been solved by the pr #1358 ?
