### ISSUE TITLE
Deprecation: #85462 - Signal 'hasInstalledExtensions'


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#1139]
Deprecation: #85462 - Signal 'hasInstalledExtensions'

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85462-SignalHasInstalledExtensions.html

.. include:: ../../Includes.txt

=====================================================

Deprecation: #85462 - Signal 'hasInstalledExtensions'

=====================================================

See :issue:`85462`

Description

===========

The usage of signal :php:`hasInstalledExtensions` of class

:php:`\TYPO3\CMS\Extensionmanager\Service\ExtensionManagementService`

has been marked as deprecated and will be removed in TYPO3 v10.

The signal is a duplication of :php:`afterExtensionInstall` that is also emitted during

extension installation.

Impact

======

Slots of this signal will get executed in TYPO3 v9 but will be abandoned with TYPO3 v10.

Affected Installations

======================

Extensions that register slots for the signal :php:`hasInstalledExtensions` of class

:php:`\TYPO3\CMS\Extensionmanager\Service\ExtensionManagementService`.

Migration

=========

Extensions should use the signal :php:`afterExtensionInstall` of class

:php:`\TYPO3\CMS\Extensionmanager\Utility\InstallUtility` instead which is emitted after an

extension has been installed.

.. index:: Backend, LocalConfiguration, PHP-API, NotScanned, ext:extensionmanager

**Comment by tomasnorre** [comment]
I'll be trying my luck with this one :)

**Comment by tomasnorre** [comment]
Looking for some inspiratation and saw this: 
https://github.com/sabbelasichon/typo3-rector/blob/master/src/Rector/v9/v4/UseSignalTablesDefinitionIsBeingBuiltSqlExpectedSchemaServiceRector.php#L72

Isn't that a mistake that the two use statements are on same line?

**Comment by sabbelasichon** [comment]
It is more a unpretty formatting issue. Nothing problematic codewise. If you like you could fix this with your PR.

**Comment by tomasnorre** [comment]
Will see if I can have it done during the weekend.
