### ISSUE TITLE
TYPO3 8.7 compatibility

### ISSUE THREAD

**Issue by infabo** [sabbelasichon/typo3-rector#1335]
```
Cannot declare class TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper, because the name is already in use
```

I guess because it is already declared in `LegacyClassesForIde.php`.

**Comment by sabbelasichon** [comment]
@infabo Could please remove the these lines for testing purposes: https://github.com/sabbelasichon/typo3-rector/blob/master/composer.json#L47

**Comment by sabbelasichon** [comment]
@infabo What config are you using?

**Comment by infabo** [comment]
Did not get to use rector because after `composer require --dev ssch/typo3-rector` my whole TYPO3 installation was tilt.

**Comment by infabo** [comment]
> @infabo Could please remove the these lines for testing purposes: https://github.com/sabbelasichon/typo3-rector/blob/master/composer.json#L47-L54

did not help

**Comment by sabbelasichon** [comment]
@infabo Thanks for your feedback and your patience. I have removed the autoloading of the Migrations folder. This was left over and not very useful anyways. Now it works. I have tested it on a fresh 8.7 installation.

**Comment by infabo** [comment]
Confirm working. Thanks!
