### ISSUE TITLE
Error with each command - The "debug" option does not exist.

### ISSUE THREAD

**Issue by robsonrobi** [sabbelasichon/typo3-rector#1397]
I installed it via composer and went into vendor/bin .

Typing:

./typo3_rector sets

results in the following error. Am i missing something ?

In Input.php line 150:

  [Symfony\Component\Console\Exception\InvalidArgumentException]
  The "debug" option does not exist.

`Exception trace:
  at /var/www/cmp-www-vagrant/current/app/vendor/symfony/console/Input/Input.php:150
 Symfony\Component\Console\Input\Input->getOption() at /var/www/cmp-www-vagrant/current/app/vendor/rector/rector/src/Console/Command/AbstractCommand.php:56
 Rector\Console\Command\AbstractCommand->initialize() at /var/www/cmp-www-vagrant/current/app/vendor/symfony/console/Command/Command.php:221
 Symfony\Component\Console\Command\Command->run() at /var/www/cmp-www-vagrant/current/app/vendor/rector/rector/src/Console/Command/AbstractCommand.php:34
 Rector\Console\Command\AbstractCommand->run() at /var/www/cmp-www-vagrant/current/app/vendor/symfony/console/Application.php:1012
 Symfony\Component\Console\Application->doRunCommand() at /var/www/cmp-www-vagrant/current/app/vendor/symfony/console/Application.php:272
 Symfony\Component\Console\Application->doRun() at /var/www/cmp-www-vagrant/current/app/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/cmp-www-vagrant/current/app/vendor/ssch/typo3-rector/bin/typo3_rector:19
`

**Comment by sabbelasichon** [comment]
@robsonrobi Thanks for your report. I updated the documentation to clearify the process of configuring and processing rector. Please have a look at https://github.com/sabbelasichon/typo3-rector#configuration-and-processing. Hope that this will help you to run rector correctly.
