### ISSUE TITLE
Broken composer dependency

### ISSUE THREAD

**Issue by AnatoliZich** [sabbelasichon/typo3-rector#1401]
The dependency for rector 0.6 in the composer.json does seem to be broken. Trying to install the dev-master branch using composer generates several of these Warnings:

```
symplify/package-builder (v7.2.3): Failed to update https://github.com/symplify/package-builder.git in cache, package installation for symplify/package-builder might fail.
Cloning 5f72b6735d from cache
    5f72b6735d1b82c771856807752088ec81ae7584 is gone (history was rewritten?)
    Failed to download symplify/package-builder from source: Failed to execute git checkout '5f72b6735d1b82c771856807752088ec81ae7584' -- && git reset --hard '5f72b6735d1b82c771856807752088ec81ae7584' --

fatal: reference is not a tree: 5f72b6735d1b82c771856807752088ec81ae7584

    Now trying to download from dist
```

I've looked them up and found out that the packagist Commit Hash no longer exists in the github repos. Updating rector to 0.7 fixes the problem for me. Is there a special reason for the fixed ^0.6.0 rector dependency or can it be updated?

**Comment by sabbelasichon** [comment]
@AnatoliZich Thanks for the report. At the moment there are a lot of changes in rector itself. So it is not an easy step to upgrade to version v0.7 right now.  

I have defined the version in the composer.json to 0.6.14 for now. This should fix your problem for the moment.
