### ISSUE TITLE
Class "Rector\Renaming\Rector\MethodCall\RenameMethodCallRector" was not found while loading "vendor/ssch/typo3-rector/config/typo3-95.yaml" file

### ISSUE THREAD

**Issue by localhorst** [sabbelasichon/typo3-rector#1465]
I am using 

```
  "require": {
    "typo3/cms-core": "^9.5",
   (...)
  "config": {
    "platform": {
      "php": "7.2.14"
   (...)
```

```
  "require-dev": {
    "rector/rector": "0.7.64",
    "ssch/typo3-rector": "0.2"
  },
```
I cleared all caches:
`rm -rf var/cache/* htdocs/typo3temp/* && composer dumpautoload && composer cc`

When executing 
` ./vendor/bin/rector process htdocs/typo3conf/ext/my_extension/ --config=rectorconfig.yaml`

I get this error:

```
 [ERROR] Class "Rector\Renaming\Rector\MethodCall\RenameMethodCallRector" was not found while loading
         "vendor/ssch/typo3-rector/config/typo3-95.yaml" file. Are you sure it is correctly spelled? in
         /srv/apache2/vhostname/vendor/ssch/typo3-rector/config/typo3-95.yaml (which is being imported from
         "/srv/apache2/vhostname/rectorconfig.yaml").
```

I got the same error before updating rector (was 0.7.47 before)

**Comment by tmotyl** [comment]
Hi
We're in progress of upgrading typo3-rector to newest rector 0.8. Some patches are already in master some are in progress in https://github.com/sabbelasichon/typo3-rector/pull/1473.
currently the rector version 0.2 works with rector 0.7.21

**Comment by tmotyl** [comment]
FYI, the current master is compatible with rector 0.8.
