### ISSUE TITLE
Wrong replacement of PATH_site

### ISSUE THREAD

**Issue by georgringer** [sabbelasichon/typo3-rector#1488]
See https://github.com/georgringer/news_importicsxml/commit/48e894d61e81428688894db600872dd64a86bf92#diff-403ae037cbd1c2311eb2b8b87f2a092dL141:

Replacement of `PATH_site` is wrong as that contains an end slash but `Environment::getPublicPath()` not

**Comment by tmotyl** [comment]
👍 that was quick! Thanks!
