### ISSUE TITLE
nette/utils is missing in composer.json

### ISSUE THREAD

**Issue by ducrot** [sabbelasichon/typo3-rector#1520]
Nette\Utils\Strings is used in RemoveFlushCachesRector, but package is missing in composer.json.

```
[ERROR] Could not process "someFile.php" file by
         "Ssch\TYPO3Rector\Rector\Extbase\RemoveFlushCachesRector", due to:
         "Class 'Nette\Utils\Strings' not found".
```

**Comment by tmotyl** [comment]
Isnt it a dependency of Rector?

**Comment by ducrot** [comment]
Yes, but if using https://github.com/rectorphp/rector-prefixed one is stucked.

**Comment by sabbelasichon** [comment]
I have to check it. But for now you could require nette/utils in your project. Right?

**Comment by ducrot** [comment]
Yes, this workaround works.

**Comment by sabbelasichon** [comment]
@ducrot I have added the nette/utils package as a hard requirement. Does this fix your problem?

**Comment by ducrot** [comment]
Yes!
