### ISSUE TITLE
TYPO3_REQUESTTYPE replacement wrong

### ISSUE THREAD

**Issue by simonschaufi** [sabbelasichon/typo3-rector#1584]
This is not correct:

```php
- (TYPO3_REQUESTTYPE & TYPO3_REQUESTTYPE_FE) 
+ (Environment::isCli() & TYPO3_REQUESTTYPE_FE)
```

Applied rules:

 * Ssch\TYPO3Rector\Rector\v9\v4\ConstantToEnvironmentCallRector

**Comment by sabbelasichon** [comment]
@simonschaufi Could you try it again? Will release a new Version soon.
