### ISSUE TITLE
[ERROR] Class 'Typo3SetList' not found 

### ISSUE THREAD

**Issue by Starraider** [sabbelasichon/typo3-rector#1600]
If you use your example configuration file from your manual, the error "Class 'Typo3SetList' not found" will be shown.
You should add the following line in the manual:
`use Ssch\TYPO3Rector\Set\Typo3SetList;`

Then it works! ;-)

**Comment by tmotyl** [comment]
@Starraider can you send a PR?

**Comment by sabbelasichon** [comment]
@Starraider, @tmotyl: I´ll do it, because i have to adjust some other minor issues in the README as well. Thanks for reporting. I found the misconfiguration myself yesterday.
