### ISSUE TITLE
Suggestion: Have Configuration sets alphabetically like use statement

### ISSUE THREAD

**Issue by tomasnorre** [sabbelasichon/typo3-rector#1629]
I would suggest that we have the configuration sets like here:
https://github.com/sabbelasichon/typo3-rector/blob/master/config/v9/typo3-94.php#L31

Done alphabetically like the use statements. This will lower the risk of merge conflicts and keep a better overview, what's include and what's not. 

Could even be a rector to ensure that ;)

**Comment by sabbelasichon** [comment]
After thinking about it, i would suggest to leave it as it is. I think the merge conflicts will be higher if you reorder everything.
