### ISSUE TITLE
Idea: typo3-rector-maker binary analog to symfony make bundler.

### ISSUE THREAD

**Issue by tomasnorre** [sabbelasichon/typo3-rector#1632]
I have been creating a few Rectors only, but already recognizing a pattern. 
By most rectors I create the following files: 

```shell 
CHANGE='TheChangeThatIsImplemented'
snake_case_change='the_change_that_is_implemented'

// Contains the same 3 functions as default
src/Rector/v${major}/v${minor}/${CHANGE}Rector.php

// Is close to identical every time, only the `getRectorClass`-function differs
tests/Rector//v${major}/v${minor}/${CHANGE}/${CHANGE}RectorTests.php
tests/Rector//v${major}/v${minor}/${CHANGE}/Fixture/${snake_case_change}.php.inc

``` 

The `RectorTests.php` file is close to identical every time, only the `getRectorClass`-function differs

I don't know if it's work the effort, but I think this could help people get to contribute easier. 

I could imagine a binary like following creating this: 

`$ make rector 8.7 TheChangeThatIsImplemented` which then creates the basic for you.

**Comment by tmotyl** [comment]
Would https://github.com/rectorphp/rector/blob/master/docs/rector_recipe.md be helpful in this case?

**Comment by tomasnorre** [comment]
Sounds like it, didn't know about that :)

**Comment by sabbelasichon** [comment]
I knew about it, but also forget about it. Will take a look. Maybe it helps to speed things up.
