### ISSUE TITLE
Document all configurable rectors

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#1635]

**Comment by tomasnorre** [comment]
How should this be done? Do you have an example @sabbelasichon ?

**Comment by sabbelasichon** [comment]
For now, i have no other idea than just create a .md File underneath the docs folder manually and put all the configured rectors into it. For example this one here: https://github.com/sabbelasichon/typo3-rector/blob/master/config/v8/typo3-80.php#L105.

**Comment by tomasnorre** [comment]
Is it worth investing some time in a way to see how it's can be done automatically?

**Comment by tomasnorre** [comment]
I haven't got it to run within the TYPO3 Rector due to dependency conflicts so could not test, 
but sounds like this could help us. 

https://github.com/symplify/rule-doc-generator

**Comment by sabbelasichon** [comment]
@tomasnorre Looks promising. I think Tomas extracted this as a new repository. So, let us wait some time. If we upgrade to a new rector version where this package is included we will give it a try. So this ticket is on hold for now.

**Comment by sabbelasichon** [comment]
I think the configurable rectors are not taking into account by the auto generation of the docs. I think it is too much work and not really worth it. We have already a lot of rectors to show. I am gonna close this issue.
