### ISSUE TITLE
Question regarding transforming ExtensionUtility::configurePlugin

### ISSUE THREAD

**Issue by georgringer** [sabbelasichon/typo3-rector#1658]
Got a question transforming `\TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin`. 

This worked fine in ext:news but in tt_address this is not replaced?
```
\TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
    'FriendsOfTYPO3.tt_address',
    'ListView',
    [
        'Address' => 'list,show'
    ],
    [
        'Address' => ''
    ]
);
```

**Comment by sabbelasichon** [comment]
@georgringer Cannot confirm this behaviour. See https://github.com/sabbelasichon/typo3-rector/pull/1663/files
