### ISSUE TITLE
Example to modify TCA

### ISSUE THREAD

**Issue by georgringer** [sabbelasichon/typo3-rector#1660]
Hey,

I would love to see an example for changing TCA values as this is one of the most boring tasks I got during updates and those would be perfect for rector and IMO quite easy to contribute - what do you think?

Examples would be:
- https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.3/Feature-88901-RenderAllFieldsInElementInformationController.html?highlight=showrecordfieldlist
- or anything which I fixed at https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.3/Feature-88901-RenderAllFieldsInElementInformationController.html?highlight=showrecordfieldlist
- or in core we changed all real integer values to intextes, e.g. `'size' => '10'` or `'exclude => 1'`

**Comment by georgringer** [comment]
just saw https://github.com/sabbelasichon/typo3-rector/pull/1522 > is there a reason why this is not merged?

**Comment by tmotyl** [comment]
Afaik needs somebody to test and review

**Comment by sabbelasichon** [comment]
@georgringer I merged it yesterday. It is not perfect, but i would like to test in the wild. If you need guidance contact me directly please.
