### ISSUE TITLE
Parser stops at die() statement

### ISSUE THREAD

**Issue by abeutel** [sabbelasichon/typo3-rector#1661]
If parsing PHP code like

```php
// Exit, if script is called directly (must be included via eID in index_ts.php)
if (!defined('PATH_typo3conf')) {
    die('<h1>Error</h1><p>You are not allowed to access this script directly. This incident has been logged!</p>');
}
```

The parser stops:

```
[parsing] foo/bar.php
<h1>Error</h1><p>You are not allowed to access this script directly. This incident has been logged!</p>%
```

Used `./vendor/bin/typo3-rector process --debug foo/bar.php`

**Comment by sabbelasichon** [comment]
@abeutel What version of TYPO3 are you using? I guess version 10. This constant is removed there. I will check if it is useful to provide a bootstrap file for rector to not fail under these circumstances.

**Comment by abeutel** [comment]
This happened on a 7.6 test migration.

**Comment by abeutel** [comment]
@sabbelasichon using a bootstrap as you suggested finally fixed it:

`bootstrap.php`

```php
<?php
defined('PATH_typo3conf') ?: define('PATH_typo3conf', 'foo');
defined('PATH_site') ?: define('PATH_site', 'foo');
defined('TYPO3_version') ?: define('TYPO3_version', 'foo');
```
and adding this in `rector.php`
```php
$parameters->set(Option::AUTOLOAD_PATHS, [
    __DIR__ . '/bootstrap.php'
]);
```

**Comment by sabbelasichon** [comment]
Cool. I will add a bootstrap file per default.
