### ISSUE TITLE
Error when processing ext_tables

### ISSUE THREAD

**Issue by tmotyl** [sabbelasichon/typo3-rector#1669]
I'm getting
```
 [ERROR] Could not process "packages/my_package/ext_tables.php" file, due to:                                    
         "strrpos() expects parameter 1 to be string, null given".
```
The funny thing is that the file doesn't contain the strrpos call, so its something from inside rector.

The file looks like:
```
<?php


defined('TYPO3_MODE') || die();

call_user_func(
    function ($extensionKey) {
        if (TYPO3_MODE === 'BE') {
            \TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerPlugin(
                $extensionKey,
                'CardCheck',
                'Plugin'
            );

            \TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerPlugin(
                $extensionKey,
                'Verify',
                'Plugin Full Name'
            );

            \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile($extensionKey, 'Configuration/TypoScript', 'Some name');
        }
    },
    'my_package'
);

```

In the same run, changes in ext_localconf are wrong:

```
1) packages/my_package/ext_localconf.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -15,58 +15,38 @@
 call_user_func(
     function ($extensionKey) {
         \TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
-            'Vendor.' . $extensionKey,
+            '',
             'CardCheck',
-            [
-                'Card' => 'form,check',
-            ],
-            [
-                'Card' => 'form,check',
-            ]
+            [\Vendor\\Controller\CardController::class => 'form,check'],
+            [\Vendor\\Controller\CardController::class => 'form,check']
         );

```
As the first argument of the configurePlugin becomes empty. As well as the doubled slashes in controller namespace

**Comment by sabbelasichon** [comment]
Found the culprit. Yes it is inside of rector https://github.com/sabbelasichon/typo3-rector/blob/master/src/Rector/v10/v0/UseControllerClassesInExtbasePluginsAndModulesRector.php#L58
It is hard to resolve the variable during the analysis. Actually it is not possible. I try to do some magic behind the scenes. i will try to extend the magic so you can use it. At the moment only $_EXTKEY is supported. I should extend it.

**Comment by tmotyl** [comment]
hmm so at last we should protect the code so it will not change this line

**Comment by sabbelasichon** [comment]
Sure. That´s the reason i need more people to test the things in the wild. I will add these things to tests.

**Comment by sabbelasichon** [comment]
@tmotyl Can you try it again with the current master please?
