### ISSUE TITLE
Stubs not found

### ISSUE THREAD

**Issue by Patta** [sabbelasichon/typo3-rector#1700]
Error on process `./vendor/bin/typo3-rector process packages/my-sitepackage --dry-run`

`
 [ERROR] File or directory                                                                                          
         'C:\...\vendor\ssch\typo3-rector\src\Stubs/../../stubs' not     
         found.  `

TYPO3 Rector 0.7.3
PHP 7.4.12
Windows 10 (local)

**Comment by sabbelasichon** [comment]
@Patta Could you try it again with Release 0.7.4. I have ignored the stubs in .gitattributes. This is wrong if you install it via composer the default way as an archive.

**Comment by sabbelasichon** [comment]
I tested it on a Mac. Should be fixed with version 0.7.4
