### ISSUE TITLE
Replace $_EXTKEY with extension key

### ISSUE THREAD

**Issue by georgringer** [sabbelasichon/typo3-rector#1702]
The variable `$_EXTKEY` is not filled anymore in the following files:
- `ext_localconf.php`
- `ext_tables.php`

See e.g. https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Important-82692-GuidelinesForExtensionFiles.html

*DON'T* replace in `ext_emconf.php as it is required here ;)

**Comment by tmotyl** [comment]
https://github.com/sabbelasichon/typo3-rector/issues/952
