### ISSUE TITLE
Best practice: Convert imports to FQDN in some files

### ISSUE THREAD

**Issue by mmunz** [sabbelasichon/typo3-rector#1704]
Currently typo3-rector ignores some files when using AUTO_IMPORT_NAMES, because imports should not be used in their global space, see https://github.com/sabbelasichon/typo3-rector/blob/master/templates/rector.php.dist#L37. This is already helpful, but it doesn't prevent the usage of imports in those files. It would be helpful to have a rector rule to check for following this best practice and fix it by replacing imports with FQDN.

The doc states for ext_tables.php and ext_localconf.php: "You must never use a use statement in the files global scope - that would make the cached script concept break and could conflict with other extensions.", see https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ConfigurationFiles/Index.html#best-practices-for-ext-tables-php-and-ext-localconf-php

I'm currently unsure if this applies to other files than ext_tables.php and ext_localconf.php as well.

**Comment by sabbelasichon** [comment]
@mmunz There are also other files like these in Configuration/TCA. For now i would say that rector is not responsible for that. So i am going to close this for now. Maybe we can move this to github discussions. I am gonna enable that.

**Comment by sabbelasichon** [comment]
Moved it to https://github.com/sabbelasichon/typo3-rector/discussions/1738
