### ISSUE TITLE
LLL:EXT:lang rewrite to resources directory not happening

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#1839]
I'm currently upgrading from v8 to v10 and have two extensions that we're build some time apart.
The older EXT used the old LLL:EXT:lang/locallang.. labels.
The newer one already had the proper Resources paths - this one also got changed by the v9 rector that moves the EXT:lang into their fitting EXT:core etc. paths

The older EXT did not receive an update and stayed the same.
I'm guessing the "MoveLanguageFilesFromLocallangToResourcesRector" is the right one
I'm using the TYPO3 Rector SETS:: 7 - 10 stepwise while the change should happen with the usage of the 87 set.
Is it on purpose that the move is not in there, is it missing or maybe conflicting with other rectors?

**Comment by sabbelasichon** [comment]
The Rector is missing in the set.
