### ISSUE TITLE
Wrong link inside error message

### ISSUE THREAD

**Issue by PhilippKuhlmay** [sabbelasichon/typo3-rector#1884]
Inside the following error message, the link is wrong:
<img width="842" alt="Bildschirmfoto 2021-01-12 um 15 14 32" src="https://user-images.githubusercontent.com/57705869/104325661-292f2200-54e9-11eb-8449-ae0ec29e3554.png">
There is no anchor for "configuration". Maybe the correct link is https://github.com/rectorphp/rector#full-config-configuration

**Comment by sabbelasichon** [comment]
Could you post this in the rector project itself please https://github.com/rectorphp/rector/. Not part of this  repository.
