### ISSUE TITLE
Error: A cache with identifier "cache_core" does not exist.

### ISSUE THREAD

**Issue by michadu** [sabbelasichon/typo3-rector#1888]
Analyzing an AjaxDispatcher class results in the Error:

```
[ERROR] Could not process "typo3conf/ext/myExtension/Classes/Utility/AjaxDispatcher.php" file, due to:
         "Analyze error: "TYPO3\CMS\Core\Cache\Exception\NoSuchCacheException (A cache with identifier "cache_core" does
         not exist.) thrown while looking for class MyVendor\MyExtension\Utility\AjaxDispatcher.". Include your
         files in "$parameters->set(Option::AUTOLOAD_PATHS, [...]);" in "rector.php" config.
```

Removing these 2 lines at the end of the file let typo3-rector run without an error.

$eid = GeneralUtility::makeInstance('MyVendor\MyExtension\Utility\AjaxDispatcher', $GLOBALS['TYPO3_CONF_VARS']);
echo $eid->run();

**Comment by sabbelasichon** [comment]
This is not really solvable at the moment. As all autoloaded files are also executed. This is one of the most annoying gotchas in rector at the moment. Maybe in the near future we can take advantage of static reflection. For further information see https://github.com/rectorphp/rector/issues/3490
