### ISSUE TITLE
String 'Locale" is migrated to \Locale::class

### ISSUE THREAD

**Issue by DanielSiepmann** [sabbelasichon/typo3-rector#1892]
In one of our projects we had the hardcoded label `'Locale'` within TCA. This got migrated to `\Locale::class` which is provided by php ext-intl. https://www.php.net/manual/en/class.locale.php.

I understand the change but would not expect that change. It might be related to our way of writing the TCA. We use the ` \TYPO3\CMS\Core\Utility\ArrayUtility::mergeRecursiveWithOverrule(` and maybe the rule isn't aware of that way and don't know this is TCA.
We use this way to have a single way vor `TCA/Overrides` and `TCA`. That way we can just copy and paste parts from one file to another.

```diff
diff --git a/local_packages/e2_core/Configuration/TCA/Overrides/sys_language.php b/local_packages/e2_core/Configuration/TCA/Overrides/sys_language.php
index 969152925..15ec59149 100644
--- a/local_packages/e2_core/Configuration/TCA/Overrides/sys_language.php
+++ b/local_packages/e2_core/Configuration/TCA/Overrides/sys_language.php
@@ -7,7 +7,7 @@ if (!defined('TYPO3_MODE')) {
     \TYPO3\CMS\Core\Utility\ArrayUtility::mergeRecursiveWithOverrule($GLOBALS['TCA'][$tableName], [
         'columns' => [
             'locale' => [
-                'label' => 'Locale'
+                'label' => \Locale::class
                     . ' Format: "language-territory", e.g. de-DE or fr-DE,',
                 'config' => [
                     'type' => 'input',
```

**Comment by sabbelasichon** [comment]
@sabbelasichon Have a look at Rector\Php55\Rector\String_\StringClassNameToClassConstantRector

**Comment by sabbelasichon** [comment]
@DanielSiepmann The reason is that the StringClassNameToClassConstantRector is added in the config for typo3-90. I added this a long time ago because i thought it is a good idea. But now i consider it dangerous. On the other hand, we could configure the rector to skip certain classes, but this is not reliable in the end. I am not sure how to deal with this. It is nice to use the ::class instead of a string. But your case showed me it is also not reliable.

**Comment by DanielSiepmann** [comment]
I would say that depends on the idea. Should typo3 rector prevent false positives?
Or are false positives okay and everyone should check the changes afterwards?

If false positives are fine, I would keep it and maybe exclude certain files or classes.

**Comment by sabbelasichon** [comment]
@DanielSiepmann I cam to the conclusion to remove this rector because it is not specific to TYPO3 and leads to side effects. If someone wants to really transform this just add the StringClassNameToClassConstantRector to the custom config.
