### ISSUE TITLE
Raise PHP-Version constraint to 7.4

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#1894]

**Comment by helsner** [comment]
I'm not gonna stop you from keep going the very good work you're doing, but i am not sure if this change would affect the usability/UX of using rector as i would have to pin the version to v0.8.4 or something, as the old versions of TYPO3 to not have the 7.4 in use.
From own experience i can tell that i have only a few instances that are actively running php 7.3 or 7.4 and by that i mean they run this on the server but not directly as a constraint for composer - those are still often setup with 7.2 or 7.3 at its best.
Also e.g. JWeiland does only provide PHP 7.4 in their cloud solution which started lately.
Of course rector is used on DEV and you HAVE to run TYPO3 v11 with 7.4 - but the use case of rector is in my personal case with older core versions that might not run on 7.4
Concrete case: if you're running a v8 version then you definitely update to v9 as the PageSlugs and EXT:seo came in there
Third party ext might need own migration, are outdated and do not support 7.4 - this would then conflict with the rector dependencies

**Comment by sabbelasichon** [comment]
We won´t do it. We will stick to version 7.3. This is also true for the phar file. Therefore i had to set platform-check to false during the compilation of the phar file.
