### ISSUE TITLE
DOCS: Readd NameImportingPostRector to base docs

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#1901]
I set up a new rector config in a project that did not include rector before.
For this i checked the installation and config + processing docs
https://github.com/sabbelasichon/typo3-rector/blob/master/docs/configuration_and_processing.md

I just copied it and tried a dry run just to see if it works - then i noticed that i got my ext_localconf marked as "would change".
The import rector has been triggered which i consider highly dangerous as the import of files in ext_tables and ext_localconf can cause system errors, as both get concatenated along all extensions used.
https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ExtensionArchitecture/ConfigurationFiles/Index.html#rules-and-best-practices

**Comment by sabbelasichon** [comment]
@helsner Could you please provide your rector configuration? I am wondering why this is happening at all, because it is false per default. So no AutoImport is triggered.

**Comment by helsner** [comment]
I took the older rector config i had left in a project.
I just checked and had the following in it
`$parameters->set(Option::AUTO_IMPORT_NAMES, true);`

Removing this changes the behavior, but i would want to  auto import all - so i added the following:

```
$parameters->set(Option::SKIP, [
        NameImportingPostRector::class => [
            'ClassAliasMap.php',
            'class.ext_update.php',
            'ext_localconf.php',
            'ext_emconf.php',
            'ext_tables.php',
            __DIR__ . '/**/TCA/*',
        ],
    ]);
```

which does not fix that the auto import changes the named files (which i would expect, if i am not wrong with that understanding?)

**Comment by sabbelasichon** [comment]
@helsner In order to skip certain files and folders i have introduced a custom option called Typo3Option::AUTO_IMPORT_NAMES. But now i understand why it is not working for you as you expected. But you are right, i am going to add this to the configuration section of the docs.
