### ISSUE TITLE
Composer update ist triggered when running rector

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#1906]

**Comment by sabbelasichon** [comment]
Yes, during the ProcessCommand the ComposerProcessor is doing some stuff. So, under some conditions this can happen. Not sure why Rector is doing it in the first place.

**Comment by dahaupt** [comment]
@sabbelasichon I've just noticed this new behavior of rector. Additionally, Rector changes the indentation within the `composer.json`. Do you already know any way to prevent this?

**Comment by sabbelasichon** [comment]
@dahaupt: No, after looking at the code i think it is not possible.

**Comment by dahaupt** [comment]
@sabbelasichon Since we run typo3-rector as part of our CI pipeline, this is of course inconvenient if we want to keep our current `composer.json`. Then I guess I will have to open an issue in rector itself.

**Comment by dahaupt** [comment]
@sabbelasichon Solved by latest release (0.8.7) which updates rector to v0.9.10.
