### ISSUE TITLE
Extension Builder with PhpParser in wrong version

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#1917]

**Comment by t3easy** [comment]
Environment:
TYPO3 Rector 0.8.8
TYPO3 8.7
friendsoftypo3/extension-builder: 8.10.4
https://github.com/FriendsOfTYPO3/extension_builder/blob/8.10.4/Resources/Private/PHP/PHP-Parser/lib/PhpParser/PrettyPrinter/Standard.php

**Comment by t3easy** [comment]
> Fatal error: Access level to Rector\Core\PhpParser\Printer\BetterStandardPrinter::pScalar_String() must be public (as in class PhpParser\PrettyPrinter\Standard) in /opt/typo3-rector/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php on line 418

**Comment by sabbelasichon** [comment]
This is related to #1879.
