### ISSUE TITLE
Duplication of ClassAlias Replace

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#1924]
We had a case where the class alias that was used to replaced outdated interfaces created a duplication as two classes where replaced by the same.

`class ChooseOneViewHelper extends AbstractViewHelper implements ViewHelperInterface, ViewHelperInterface`

core v8 LTS, rector v0.7.7 -- this might be solved already as it is an older version.

**Comment by sabbelasichon** [comment]
@helsner Could you create a failing test as a PR with the used code?

**Comment by helsner** [comment]
Yes, i'll try
i forgot to mention the original code:
`class ChooseOneViewHelper extends AbstractViewHelper implements ChildNodeAccessInterface, CompilableInterface {`
 
my bad

**Comment by sabbelasichon** [comment]
@helsner Ok, that´s enough. I am gonna try to fix it.

**Comment by sabbelasichon** [comment]
@helsner Can confirm this bug. This is already addressed in rector itself. I try to fix it. Thanks for reporting the issue.

**Comment by sabbelasichon** [comment]
This is part of rector itself and should be fixed there: https://github.com/rectorphp/rector/issues/5389
