### ISSUE TITLE
foreign_selector_fieldTcaOverride Migration Rector

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#1930]
Currently the config `foreign_selector_fieldTcaOverride` is not migrated.
The existing rector should be https://github.com/sabbelasichon/typo3-rector/blob/master/src/Rector/v8/v7/MoveForeignTypesToOverrideChildTcaRector.php
This could be extended to also migrate the said field which is fully dropped in its Migration with v10 (this means the Upgrade Wizard in the BE does not detect it anymore as invalid config)

**Comment by helsner** [comment]
cpt hook causes some trouble ATM so i cannot push but basically you can use the documentation to test this
This should be the change that is made, which is not happening
 <?php
 
 return [
     'ctrl' => [
     ],
     'columns' => [
         'aField' => [
             'config' => [
                 'type' => 'inline',
                 'foreign_selector' => 'uid_local',
                 'foreign_selector_fieldTcaOverride' => [
                     'config' => [
                         'appearance' => [
                             'elementBrowserType' => 'file',
                         ],
                     ],
                 ],
             ],
         ],
     ],
 ];
 
 ?>
 -----
 <?php
 
 return [
     'ctrl' => [
     ],
     'columns' => [
         'aField' => [
             'config' => [
                 'type' => 'inline',
                 'foreign_selector' => 'uid_local',
                 'overrideChildTca' => [
                     'columns' => [
                         'uid_local' => [
                             'config' => [
                                 'appearance' => [
                                     'elementBrowserType' => 'file',
                                 ],
                             ],
                         ],
                     ],
                 ],
             ],
         ],
     ],
 ];
 
 ?>

**Comment by sabbelasichon** [comment]
Resolved by #1940
