### ISSUE TITLE
Wrongfully delete of TCA wizard segment

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#1932]
I noticed that some wizard functionalities got deleted even though the wizard changed in its behavior.
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.6/Deprecation-79440-TcaChanges.html

The following segment is describing the wizard i mean - suggest does not get transformed into "suggestOptions", which would be ok, but fully dropped instead which could cause malfunction in general.
```
'name_of_travel_guide' => [
            'exclude' => 1,
            'label' => 'Name des Reiseleiters',
            'config' => [
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'pages',
                'size' => 1,
                'minitems' => 0,
                'maxitems' => 1,
                'show_thumbs' => '1',
                'appearance' => [
                    'elementBrowserType' => 'db'
                ],
                'wizards' => [
                    '_PADDING' => 1,
                    'suggest' => [
                        'type' => 'suggest',
                        'pages' => [
                            'searchCondition' => 'doktype=22',
                        ],
                    ],
                ],
            ],
        ],
```

**Comment by helsner** [comment]
I added the wizard segment that breaks in my commit, so you can copy that or similar.

**Comment by helsner** [comment]
And i just found a case of mine that worked within the same project.
I definitely would not exclude the case that our config in the TCA itself is invalid.

I double checked and it seems like it depends on the index that calles "pages" or "default" (right above the searchCondition)
If the segment is default the rewrite works, if it is pages then the whole wizard gets deleted

**Comment by helsner** [comment]
![PagesTestCase](https://user-images.githubusercontent.com/16156392/106707577-c1ed2500-65f1-11eb-9564-18c625d6e9c6.png)
![DefaultTestCase](https://user-images.githubusercontent.com/16156392/106707581-c285bb80-65f1-11eb-8f39-c43e93d9399d.png)

**Comment by helsner** [comment]
Lastly i found a 3 case of "missbehavior" where the rector dropped a functionality which he did not understand as it seems.
This case might be hacky, but it's pretty hard the deletion is done as this directly changes the functionality of the field in the specific case:

```
'mail_message' => [
    'exclude' => 0,
    'label' => 'Nachricht',
    'config' => [
        'type' => 'text',
        'cols' => 48,
        'rows' => 20,
        'wizards' => [
            '_PADDING' => 1,
            '_VERTICAL' => 1,
            'feedbackLink' => [
                'type' => 'userFunc',
                'userFunc' => \DFAU\Feedbacks\FormEngine\Payingout\PayingoutMailLinkWizard::class . '->render',
            ],
        ],
    ]
],
```

**Comment by sabbelasichon** [comment]
@helsner Thanks for this detail report. Very good to follow and to fix.
