### ISSUE TITLE
@lazy does not get converted to TYPO3\CMS\Extbase\Annotation\ORM\Lazy

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#1953]

**Comment by sabbelasichon** [comment]
Resolved by #1956

**Comment by DanielSiepmann** [comment]
This is fixed. I've tested with 0.8.17.
For some reason those namespaces are not imported. Which can be configured via `$parameters->set(Option::IMPORT_DOC_BLOCKS, true);`. This option is `false` by default.
