### ISSUE TITLE
Process functionality is broken if PHP 8 is used. 

### ISSUE THREAD

**Issue by Raidri** [sabbelasichon/typo3-rector#1960]
### Description

I used a TYPO3 9.5 installation with typo3-rector 0.8.15. My PHP CLI Version was 8.0.1. 
When I run the process script I got the following error:

 [ERROR] Could not process "packages/extensionName/Classes/ViewHelpers/RegexViewHelper.php" file, due to:
         "Analyze error: "Could not read file:
         phar://typo3-rector.phar/vendor/phpstan/phpstan-src/src/Reflection/SignatureMap/../../../vendor/phpstan/php-8-s
         tubs/stubs/ext/pcre/preg_replace.php". Include your files in "$parameters->set(Option::AUTOLOAD_PATHS, [...]);"
         in "rector.php" config.
         See https://github.com/rectorphp/rector#configuration".

**Comment by sabbelasichon** [comment]
@sabbelasichon This is only true for the .phar file. But we would like to get rid of it anyways. Gonna close this for now
see #1879
