### ISSUE TITLE
Add more extensions to composer sets

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#1984]
Maybe it is useful to add also more extensions to the composer configs to ease the upgrade process. I am not sure if this is useful. It always depends on the preferences of the developer what version constraint to use. But maybe we could say, upgrade to the at least minimum version for the targeted TYPO3 Version, i.e.

1. https://packagist.org/packages/apache-solr-for-typo3/solr#10.0.0
2. https://packagist.org/packages/directmailteam/direct-mail#7.0.0
3. https://packagist.org/packages/in2code/powermail#8.3.0
4. https://packagist.org/packages/localizationteam/l10nmgr#10.0.1
5. https://packagist.org/packages/jigal/t3adminer#9.4.1
6. https://packagist.org/packages/yoast-seo-for-typo3/yoast_seo#7.1.3
7. https://packagist.org/packages/bk2k/bootstrap-package#11.0.2
8. https://packagist.org/packages/fluidtypo3/vhs
9. https://packagist.org/packages/mask/mask#v6.4.4

**Comment by tomasnorre** [comment]
I'm not sure what is meant by this issue. Can you please elaborate a little more.

**Comment by sabbelasichon** [comment]
@tomasnorre Sure. I have added some new sets to automatically update the composer.json in the root of the directory which rector runs against. I.e. https://github.com/sabbelasichon/typo3-rector/blob/master/config/typo3-104-composer-packages.php#L74. It would be convenient to add some popular extensions which are compatible with the targeted TYPO3 version to the sets.

**Comment by tomasnorre** [comment]
Ah. I see. 

When would an extension classify as popular?

**Comment by sabbelasichon** [comment]
This is up to us. In the end it can be every extension but i don´t want to add every possible extension there.

**Comment by tomasnorre** [comment]
Wouldn't this be something can in Theory could be autogenerated from the packagist information? 
https://packagist.org/?type=typo3-cms-extension 

All the requirements' information is stored on packagist, it "just" needs to be parsed. 
I would make the option optinal though, as I don't always want to auto update extension in case there are breaking changes etc. in the extension, i might want to do it by hand. not all extension will have rector rules for updating :)

**Comment by sabbelasichon** [comment]
Nice one. Yes, could be done automatically. It is not about updating the code of extension in your custom code. It is only about updating the composer.json to the least required version. For example, you cannot update to TYPO3 Version 10 without having the package aoepeople/crawler:^9.0 at least.

**Comment by tomasnorre** [comment]
Correct.

I think I would split core and extensions in two sets. Makes it easier to choose what you want. 

Perhaps having a script that generates the extension list, could be limited by downloads as well.. No need to add extensions downloaded 10 times.

**Comment by tmotyl** [comment]
Please also take into acconut that newer T3 versions are providing new packages, or remove some from the core

**Comment by tomasnorre** [comment]
True, that needs to be taking into account, but not as much the new packages, as we are talking about root composer dependencies. But packages being removed, is for sure something that should be taking into consideration.

**Comment by sabbelasichon** [comment]
@tmotyl This is already handled by the composer sets.

**Comment by sabbelasichon** [comment]
@tomasnorre Would like to have a look at the PR for that feature? Would like to get another opinion.

**Comment by tomasnorre** [comment]
Sure I can do that, but it's a quite big PR, which you already merged. Looks like cleanup and feature are combined in this PR. 
But I'll check it out.

**Comment by tomasnorre** [comment]
It's this one you mean right? 
https://github.com/sabbelasichon/typo3-rector/pull/2004
