### ISSUE TITLE
Migrate special configuration and remove show item style pointer config

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#1988]
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.6/Deprecation-79440-TcaChanges.html

Basically we have to write a rector for this method https://github.com/TYPO3/TYPO3.CMS/blob/9e1c91aed86490f75730ae186504bd900057107e/typo3/sysext/core/Classes/Migrations/TcaMigration.php#L184

**Comment by sabbelasichon** [comment]
@helsner Do you have also a concrete example to write a rector for that change? I have seen something in the Tests of the core, but i would like see a real life example.

**Comment by helsner** [comment]
Yes i have.
I don't know for sure if they worked previously though, i checked them and they seemed fine before.

```
'catalogue_link' => [
    'label' => 'Katalog PDF',
    'displayCond' => 'FIELD:doktype:IN:20,24',
    'exclude' => 0,
    'config' => [
        'type' => 'input',
        'size' => '50',
        'max' => '256',
        'eval' => 'trim',
        'wizards' => [
            '_PADDING' => 2,
            'link' => [
                'type' => 'popup',
                'title' => 'LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:header_link_formlabel',
                'icon' => 'link_popup.gif',
                'module' => [
                    'name' => 'wizard_element_browser',
                    'urlParameters' => [
                        'mode' => 'wizard',
                    ],
                ],
                'JSopenParams' => 'height=300,width=500,status=0,menubar=0,scrollbars=1',
            ],
        ],
        'softref' => 'typolink',
    ],
],
```

```
'trip_base' => [
    'label' => 'Reise',
    'config' => [
        'type' => 'select',
        'renderType' => 'selectSingle',
        'foreign_table' => 'pages',
        'foreign_table_where' => 'AND pages.doktype IN (20,24) AND pages.hidden = 0 AND pages.deleted = 0 ORDER BY pages.title',
        'size' => '5',
        'maxitems' => '1',
        'minitems' => '1',
        'wizards' => [
            '_VERTICAL' => 1,
            'suggest' => [
                'type' => 'suggest',
                'default' => [
                    'searchWholePhrase' => 1,
                ],
                'pages' => [
                    'searchCondition' => 'doktype IN (20,24) AND hidden = 0 AND deleted = 0',
                ],
            ],
        ],
    ],
],
```

The following is a custom case, but i guess this is fitting as a "wild case".

```
'mail_message' => [
    'exclude' => 0,
    'label' => 'Nachricht',
    'config' => [
        'type' => 'text',
        'cols' => 48,
        'rows' => 20,
        'wizards' => [
            '_PADDING' => 1,
            '_VERTICAL' => 1,
            'feedbackLink' => [
                'type' => 'userFunc',
                'userFunc' => \DFAU\Feedbacks\FormEngine\Payingout\PayingoutMailLinkWizard::class . '->render',
            ],
        ],
    ]
],
```

**Comment by MK-42** [comment]
relevant unit tests in core:

* https://github.com/TYPO3/TYPO3.CMS/blob/9e1c91aed86490f75730ae186504bd900057107e/typo3/sysext/core/Tests/Unit/Migrations/TcaMigrationTest.php#L174
* https://github.com/TYPO3/TYPO3.CMS/blob/9e1c91aed86490f75730ae186504bd900057107e/typo3/sysext/core/Tests/Unit/Migrations/TcaMigrationTest.php#L208
* https://github.com/TYPO3/TYPO3.CMS/blob/9e1c91aed86490f75730ae186504bd900057107e/typo3/sysext/core/Tests/Unit/Migrations/TcaMigrationTest.php#L255

**Comment by MK-42** [comment]
@sabbelasichon  what about https://github.com/TYPO3/TYPO3.CMS/blob/9e1c91aed86490f75730ae186504bd900057107e/typo3/sysext/core/Classes/Migrations/TcaMigration.php#L262
is that already covered anywhere?
