### ISSUE TITLE
Call to Undefined Functon  Symfony\Component\DependencyInjection\Loader\Configurator\service

### ISSUE THREAD

**Issue by wolffc** [sabbelasichon/typo3-rector#1995]
Im Trying to Install typo3-rector on an TYPO3 9.5 installation
the installtion is composer based

i had to use the shim version due to conflicts if i try to run 
`vendor/bin/typo3-rector` it returns with an error  `[ERROR] Call to undefined function Symfony\Component\DependencyInjection\Loader\Configurator\service()`

**Comment by sabbelasichon** [comment]
@wolffc What version of symfony/dependency-injection is used?

**Comment by wolffc** [comment]
symfony/dependency-injection v5.2.3

**Comment by sabbelasichon** [comment]
Could you try to use the rector/rector-prefixed version instead before installing typo3-rector. 
So the steps should be the following

1. composer require --dev rector/rector-prefixed
2. composer require --dev ssch/typo3-rector

**Comment by sabbelasichon** [comment]
If it works for you. Could you close the issue here. Thanks a lot.

**Comment by wolffc** [comment]
i was able to Update an old typoscript linter package and now have a newer symfony/dependency-injection version and it seems typo3 rector is now working! thanks for your support.

maybe you could add `symfony/dependency-injection` to the requirments inside composer.json so it fails at install time and not at run-time

**Comment by sabbelasichon** [comment]
@wolffc Should already be the case by this line https://github.com/rectorphp/rector/blob/master/composer.json#L46 if i am not wrong.
