### ISSUE TITLE
Use typo3-rector-prefixed in the docker container

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#2000]

**Comment by sabbelasichon** [comment]
@t3easy Could we have a chat about the integration of composer and the rector prefixed version into the docker container. If the scoped version is inside the docker container we have nice isolated setup to use typo3-rector

**Comment by t3easy** [comment]
Sure. Tuesday at the earliest.

**Comment by sabbelasichon** [comment]
@t3easy Ping me on slack. Take your time.

**Comment by sabbelasichon** [comment]
@t3easy I try to get rid of the docker container. We should embrace the infrastructure from rector itself. It is a maintenance i don´t want to handle. Thanks for your work so far.
