### ISSUE TITLE
EXT:cms/locallang_ttc.xlf replacement

### ISSUE THREAD

**Issue by mkrappitz** [sabbelasichon/typo3-rector#2072]
Even though there is a rule here:
https://github.com/sabbelasichon/typo3-rector/blob/556089ec52b92c64f89566eaac132a28a8df45de/src/Rector/v7/v4/MoveLanguageFilesFromRemovedCmsExtensionRector.php#L24

The cms/locallang_ttc.xlf does not get replaced to frontend/Resources/Private/Language/locallang_ttc.xlf in TCA files when it stands in ['types']['1']['showitem'] => '...', See following example:

```php
<?php
return array(
	...
	'types' => array(
		'1' => array('showitem' => 'sys_language_uid,--palette--;;,l10n_parent,l10n_diffsource,hidden,--palette--;;1,title,slug,id,ean,description,manufacturer,moq,weight,images,categories,feature_groups,variants,filter_values,--div--;LLL:EXT:cms/locallang_ttc.xlf:tabs.access,starttime,endtime'),
	),
	...
```

In my rector config i have setlist Typo3SetList::TCA_76, in my parameters set.

**Comment by sabbelasichon** [comment]
Thanks. Yes, i was a little defensive and only checked for strings which begin with it, but we should be save to change beginsWith to contains.
