### ISSUE TITLE
Upgrade to Rector 0.10.x

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#2094]
@TomasVotruba Is this already doable? What are the necessary steps for me as a consumer of RectorPHP? And thanks for this really huge step. Really amazing to see this happen. If it is not that easy to answer, don´t worry.

**Comment by TomasVotruba** [comment]
Hi Sebastian, thanks for your words of appreciation. This has been the hardest refactoring so far :)

I'm trying to figure out first few bugs and edge-cases and busy with work. Could you ping me next Monday? I'll be more ready to help :+1:

**Comment by sabbelasichon** [comment]
@TomasVotruba Sure. Take your time. This is such an amazing tool. I am so happy everyday using it.

**Comment by tomasnorre** [comment]
Just out of curiosity, will you go for rector/rector-prefixed? or will you stay at rector/rector?

**Comment by sabbelasichon** [comment]
I am gonna stay at rector/rector. But as a consumer you can still use rector/rector-prefixed.

**Comment by sabbelasichon** [comment]
This is done by #2141
