### ISSUE TITLE
v9 - TCA type group internal_type file and file_reference

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#2100]
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5/Deprecation-86406-TCATypeGroupInternal_typeFileAndFile_reference.html

With v9 the support for the internal_type=file has been dropped.
The following example can be rewritten just like below:
```

'feedback_image' => [
    'exclude' => 1,
    'label' => 'FeedbackImage',
    'config' => [
        'type' => 'group',
        'internal_type' => 'file',
        'allowed' => $GLOBALS['TYPO3_CONF_VARS']['GFX']['imagefile_ext'],
        'max_size' => '20000',
        'uploadfolder' => 'fileadmin/feedbacks',
        'maxitems' => '1',
    ],
],

Turns into:

'feedback_image' => [
    'exclude' => 1,
    'label' => 'FeedbackImage',
    'config' => \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::getFileFieldTCAConfig(
        'feedback_image',
        [
            'max_size' => '20000',
            'uploadfolder' => 'fileadmin/feedbacks',
            'maxitems' => 1,
            'appearance' => [
                'createNewRelationLinkTitle' => 'LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:images.addFileReference',
            ],
        ],
        $GLOBALS['TYPO3_CONF_VARS']['GFX']['imagefile_ext']
    ),
],
```

A slight conflict occurred though:
The files are handled differently with FAL which makes a migration necessary, which can be build up just like here
https://review.typo3.org/c/Packages/TYPO3.CMS/+/54830/8/typo3/sysext/install/Classes/Updates/BackendLayoutIconUpdateWizard.php#1
Also the FE probably needs adaption.

To me the last two mentioned points are definitely not the job of rector.
The question would be if we can use rector to help out the DEV at this point by marking the TCA to be checked manually.
I checked the TCA Migration option in the BE with my v10 and did not a notification about the outdated segment anymore - rector could come to rescue in cases like this

**Comment by helsner** [comment]
Most importantly: this is a suggestion.
I pointed out the contra aspects in the end and would fully understand a rejection.

**Comment by sabbelasichon** [comment]
@helsner: Have a look at https://github.com/sabbelasichon/typo3-rector/pull/2113. Did i miss something? I think despite the fact that someone needs an upgrade wizard it still useful to offer this rector.

**Comment by helsner** [comment]
Approved!
Still wondering if there's a way to help out the DEV more.
The rector does now the job of changing the TCA up.
But at that moment the data changes from saving "filexyz.jpg" to the FAL "1" as reference.
This does not happen right away with the rector, which is good, but every image that is created after that point is saved differently than before with causes inconsistent data.
Do we have the option of hinting within the CLI execution to show a Box at the end "be aware of xxx" ? or something similar

**Comment by sabbelasichon** [comment]
I see. Yes, would be nice to have some kind of report output for changes still to be done manually afterwards. I am gonna open up a new issue for that: https://github.com/sabbelasichon/typo3-rector/issues/2115
