### ISSUE TITLE
Collect report data

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#2115]
Atm rector is doing some changes which still need some manually work afterwards. 
It would be nice to collect all of these information and output it afterwards.

**Comment by sabbelasichon** [comment]
@helsner Would you like to create a concept for that? What would be the minimal value report output you can think of? We can afterwards chat about the technical implementation. But for the beginning i would keep a simple.

**Comment by helsner** [comment]
This far i had only the one case you already referenced so i don't know which possible information/data could be actually helpful.
I guess the base rector + the documentation link as it is already provided is a good step.
If the documentation should not be enough we could think of an optional description within the rector that is then provided for the DEV within the reporting. This would be provided by us as out of experience, knowledge or other sources that might not be directly linked to the documentation.

Preferable those specific rector should be gathered and put out in a special notice.
