### ISSUE TITLE
TypoScript parsing issue when there is syntax error

### ISSUE THREAD

**Issue by Apen** [sabbelasichon/typo3-rector#2124]
The new typoscipt functionnality have some issues when there is syntax errors in the code. 
In this case, nothing happen, even if there is some rules to applied and rector think its done.

Small example from legacy code i find :

```
page.10.subparts.content_right.50<
page.10.subparts.content_right.50 = CONTENT
page.10.subparts.content_right.50{
select.pidInList = {$page_contenant_identification}
	table = tt_content
	select.orderBy = sorting
	select.where = colPos=3
	select.andWhere = CType="login"
}

[usergroup = 1,2]
test = TEXT
[end]
```

(Error in the first line 👍 )
Rector will ended correctly but nothing will be convert.

**Comment by sabbelasichon** [comment]
I am gonna fail hard then.

**Comment by sabbelasichon** [comment]
@Apen No, sorry, i cannot fail hard. The reason i ignored it. Let´s say someone is using .txt as the TypoScript ending, or .ts end there are also txt and typoscript files in the analysed directories. How can i tell if it should be a valid TypoScript file or not. So ignoring it silently is the only option.

**Comment by Apen** [comment]
Can you do like rector when there is an error like an unknown class name, it totally break the process no?
