### ISSUE TITLE
To be discussed: Migrate TYPO3 Commands?

### ISSUE THREAD

**Issue by ayacoo** [sabbelasichon/typo3-rector#2127]
Disclaimer: There might already be something like this, but I couldn't find anything suitable in the Github Issues.

**Given scenario / code:**

We've old TYPO3 Commands (TYPO3 v8):

```php
use \TYPO3\CMS\Extbase\Mvc\Controller\CommandController;

class ProductCommandController extends CommandController
{
   public function myFirstCommand() {
     echo 'Hello 1';
   }
   
   public function mySecondCommand() {
     echo 'Hello 2';
   }
}
```

Documentation: 
- https://docs.typo3.org/m/typo3/reference-coreapi/9.5/en-us/ApiOverview/CommandControllers/Index.html
- https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.0/Feature-73042-IntroduceNativeSupportForSymfonyConsole.html

Our best case would be this result (Here v9. v10 with an int as return):

The old file still exists for controlling and two new files are created.

```php
use Symfony\Component\Console\Command\Command;

class MyFirstCommand extends CommandController
{
   public function execute() {
     echo 'Hello 1';
   }
}
```

```php
use Symfony\Component\Console\Command\Command;

class MySecondCommand extends CommandController
{
   public function execute() {
     echo 'Hello 2';
   }
}
```

You could also create this new file at the end: "Configuration/Commands.php"

```php
return [
    'extensionKey:myFirstCommand' => [
        'class' => \Vendor\Extension\Command\MyFirstCommand::class,
    ],
    'extensionKey:mySecondCommand' => [
        'class' => \Vendor\Extension\Command\MySecondCommand::class,
    ],
];
```

**Questions:**
1. Is that sensible or realistic?
2. How would we deal with an existing Commands.php? Simply manipulate the array
3. I can offer to participate in the development, would probably only need to have 1-2 concepts explained in advance. Sounds not so easy

**Comment by sabbelasichon** [comment]
@ayacoo This would be of course awesome. If you have your next project, we could try together and see how far we can get with this. Maybe we could first add to one of the experimental rules and try it out in the wild. But it would be still a great time saver.

**Comment by sabbelasichon** [comment]
@sabbelasichon 

Commands.php contains namespace and double slash for ::class.

**Comment by sabbelasichon** [comment]
Autoloading crashes for installations where the CommandController does not exist anymore.

**Comment by sabbelasichon** [comment]
Add this to your config

`require_once __DIR__ .'/vendor/ssch/typo3-rector-prefixed/stubs/TYPO3/CMS/Extbase/Mvc/Controller/CommandController.php';`

**Comment by ayacoo** [comment]
Really awesome work! Great to see what is possible with Rector and competent people ;-)

**Here my first feedback:**
Perhaps an additional note or notes would be useful.  Alternatively a link to the github repo where we might have the documentation for the case?

"Remember to modify the old command after editing/reviewing in the scheduler list" or something similar?

"When upgrading the commands, changes to the dependency injection may be necessary. For example, the ObjectManager is not automatically necessary." Providing a list of possible improvements could be helpfully.



In the Commands.php i would change the generated name. An example from me: "ayacoo:importteamcommand". 
=> "ayacoo:importteam" should certainly suffice here. What do you think?


**Short hint:**
If you use dev-main this is the requirement for your config
`require_once __DIR__ .'/vendor/ssch/typo3-rector/stubs/TYPO3/CMS/Extbase/Mvc/Controller/CommandController.php';`

**Comment by sabbelasichon** [comment]
I am working on it to improve it even more. As i already said, there a some gotchas to tackle and then i will be officially releasing this rule. Thanks for the idea.

**Comment by sabbelasichon** [comment]
It is done, but still can be optimized. But dedicated issues already exist
