### ISSUE TITLE
Additional report for possible missed out TCA migration addTCAcolumns()

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#2188]
AFAIK we got a new reporting that hints points in the code which cannot fully migrated by rector.

I just found a case in my code which could make use of this:
```
$tmp_showings_columns = [
    'showing' => [
        'exclude' => 1,
        'label' => 'LLL:EXT:offers/Resources/Private/Language/locallang_db.xlf:tx_showings_domain_model_spaceunit.showing',
        'config' => [
            'type' => 'select',
            'foreign_table' => 'tx_showings_domain_model_showing',
            'items' => [
                ['', '']
            ],
            'readOnly' => 1,
        ],
    ],
];
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTCAcolumns('tx_offers_domain_model_offer',
    $tmp_showings_columns);
```

The select is not enriched with "selectSingle" as the rector handling this addition ( AddRenderTypeToSelectFieldRector ) checks for full TCA.
As the function does specifically require the columsarray without the wrapping of 'columns' or 'ctrl' which are used to evaluate if the code is actually TCA and should be transformed by rector.

I guess it would be difficult to adapt the rector for this as the conditions are there to prevent transformation of code that is not actually TCA.
So we could filter for the usage of  `addTCAcolumns()` and add that to the reporting

**Comment by sabbelasichon** [comment]
Nice catch, but this would produce too many false positive report entries in my opinion. I would rather weaken the constraint to identify a TCA related array. This should be doable. Let me think about it.

**Comment by MK-42** [comment]
@sabbelasichon  I think I will tackle this next - to streamline the TCA helper trait to support these scenarios. After that I would skim over the existing rectors to see what we can do for readability there
