### ISSUE TITLE
FEAT: Refactor typoscript extbase class mapping

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#2189]
The following feature would be a hard one and might not be used that often i guess, but i still want to mention this.
I only had one project (out of double figures) which used the functionalities in this:

The old extbase class mapping got changed from typoscript into a `Classes.php` file.
The build-up of the mapping is close to the same, just the columns/properties got turned around like seen in the third example of the properties:
https://docs.typo3.org/c/typo3/cms-core/10.4/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html

The overall documentation of the extbase class hierarchy currently is wrong on v10, but correct on master docu
Here are also more examples for this
https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/6-Persistence/5-modeling-the-class-hierarchy.html

What rector might could do:
- report the usage of a extbase mapping according to existing Typoscript
- refactor the existing typoscript into a new PHP file 

Questions:
- is it possible to create new files with rector?
- does rector also read typoscript now? (i guess i read that somewhere..) and especially detect the specific segments
- are there enough usecases that take advantage of this - and is it worth the time in such a special case

**Comment by sabbelasichon** [comment]
Thanks. Yes, this is already on the list https://github.com/sabbelasichon/typo3-rector/discussions/2045

I would close this issue, otherwise it will be a long hanging fruit. It is more suited for the discussions.
