### ISSUE TITLE
Make icons processor info more precise

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#2213]
Currently the `IconsProcessor` says `File "%s" will be moved to %s'`
which results in e.g.
`File "packages/movies" will be moved to packages/movies/Resources/Public/Icons/Extension.gif`

We should adapt this for better understanding

**Comment by helsner** [comment]
I'll do that myself 👌

**Comment by sabbelasichon** [comment]
Thank you.
