### ISSUE TITLE
How to check a single TYPO3 extension with rector in Docker (Class not found error)?

### ISSUE THREAD

**Issue by Starraider** [sabbelasichon/typo3-rector#2223]
I tried to check a single TYPO3 extension with typo3-rector using your Docker Image.

With my sitepackages (without Classes) it works like a charm.

But as soon as the extension has any **Classes**, always this error comes up: 

> Could not process "packages/myextension/Classes/MyController.php" file, due to:               
         "Analyze error: "Class skom\myextension\MyController was not found while trying to analyse it -
         discovering symbols is probably not configured properly.". Include your files in                               
         "$parameters->set(Option::AUTOLOAD_PATHS, [...]);" in "rector.php" config.                                     
         See https://github.com/rectorphp/rector#configuration".

I tried it with a couple of different extensions, always the same result.

I tried to include the file with:
`
$parameters->set(Option::AUTOLOAD_PATHS, [
     __DIR__ . '/packages/myextension/Classes/MyController.php',
]);
`
Still the same error.

I even tried to skip the Class files with:

`    $parameters->set(Option::SKIP, [
        NameImportingPostRector::class => [
            __DIR__ . '/packages/myextension/Classes/MyController.php',
        ],
    ]);
`
But still the same error is shown.

So please can you explain (in the documentation), how to check a single extension (without a whole working TYPO3 installed locally)? Or do I always need to install TYPO3 locally first? Or how can I at least skip a single file from the test run?

**Comment by sabbelasichon** [comment]
I am answering the last question first, skipping a single file should work the following way:

```php
$parameters->set(Option::SKIP, [ __DIR__ . '/packages/myextension/Classes/MyController.php', ]);
```

**Comment by sabbelasichon** [comment]
To be honest, the docker image is something i am going to drop in the near future. But i should still gonna work. But as the docker image is not using static reflection you must bootstrap a full TYPO3 setup.

**Comment by sabbelasichon** [comment]
@Starraider I am gonna close this issue for now. Please contact me directly on slack if you like and i try to help you. Maybe the new version with static reflection can help you but it is not available in a docker image.
