### ISSUE TITLE
[BUG] Duplication of suggestOptions on migration (TCA)

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#2244]
Not sure if this is the same as #1988 

When migrating the old TCA `wizard -> suggest ` the options are duplicated depending on the config.
See below for the official docu (old version) which displays the earlier usages.
The migration then causes a duplication of the `suggestOptions`.

Official docs (with the relevant code segment copied)
https://docs.typo3.org/m/typo3/reference-tca/6.2/en-us/AdditionalFeatures/WizardsConfiguration/Index.html#add-a-suggest-wizard
```
'wizards' => array(
    'suggest' => array(
        'type' => 'suggest',
        'default' => array(
            'searchWholePhrase' => 1
        ),
        'pages' => array(
            'searchCondition' => 'doktype = 1'
        )
    )
)
```

results in 
```
'suggestOptions' => ['default' => [
    'searchWholePhrase' => 1,
]],
'suggestOptions' => ['pages' => [
    'searchCondition' => 'doktype = 1',
]],
```

**Comment by sabbelasichon** [comment]
@helsner Can confirm it. Test is added and now green.
