### ISSUE TITLE
ExtConf rector does not respect unserialize

### ISSUE THREAD

**Issue by froemken** [sabbelasichon/typo3-rector#2248]
Hello Sebastian,

in typo3-rector-prefixed:dev-main it suggests to change following:

```
$extConf = unserialize(
-            $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['mediapool'] ?? '',
+            GeneralUtility::makeInstance(ExtensionConfiguration::class)->get('mediapool') ?? '',
             [
                 'allowed_classes' => false
             ]
);
```

In UseExtensionConfigurationApiRector I found following line:
```
        if ($node instanceof \PhpParser\Node\Expr\FuncCall && !$this->isName($node->name, 'unserialize')) {
            return null;
        }
```

I'm very new to typo3-rector but I would interprete, that these lines should prevent changing these lines of code, if they were found in an unserialize function.

Nice greetings

Stefan

**Comment by sabbelasichon** [comment]
Thanks Stefan for reporting. Yes, that´s definitely changed incorrectly. I am gonna fix this by not changing it but reporting it.
