### ISSUE TITLE
declaration errors after typo3-rector-prefixed update

### ISSUE THREAD

**Issue by mkrappitz** [sabbelasichon/typo3-rector#2266]
I used typo3-rector-prefixed fine for some time and now update from 0.9.23 to 0.10.1. My call is as follows and now i get the following php fatal:
```
ssh@dd44338:/www/htdocs/$ php74 /.config/composer/vendor/bin/rector process typo3conf/ext/template/ -c ./rector.php --dry-run --autoload-file ./autoload.php
PHP Fatal error:  Declaration of Typo3RectorPrefix20210429\Symfony\Component\DependencyInjection\ServiceLocator::has(string $id) must be compatible with Psr\Container\ContainerInterface::has($id) in /.config/composer/vendor/ssch/typo3-rector-prefixed/vendor/symfony/dependency-injection/ServiceLocator.php on line 41
Fatal error: Declaration of Typo3RectorPrefix20210429\Symfony\Component\DependencyInjection\ServiceLocator::has(string $id) must be compatible with Psr\Container\ContainerInterface::has($id) in /.config/composer/vendor/ssch/typo3-rector-prefixed/vendor/symfony/dependency-injection/ServiceLocator.php on line 41
```

Switching back to 0.9.23 and calling as follows, everything is working again:

```
ssh@dd44338:/www/htdocs/$ php74 /.config/composer/vendor/bin/typo3-rector process typo3conf/ext/template/ -c ./rector.php --dry-run --autoload-file ./autoload.php
 68/68 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

3 files with changes
...
```

**Comment by sabbelasichon** [comment]
@TomasVotruba As i am still having my custom prefixed version and i know that is fixed for rector-prefixed. Is there quick win solution for my prefixed version? I have seen that you managed to solve it with different PR´s.

**Comment by TomasVotruba** [comment]
The exact fix is line 33 here: https://github.com/rectorphp/rector/commit/147973bcb2cc9d423e6bf039887aaad977d8d51d

PSR and Symfony must be downgraded together, so the covariant type is removed from both.

**Comment by sabbelasichon** [comment]
I am not fixing it. The way to go is to use the prefixed version of rectorphp/rector in the near future by default and not building my own prefixed version. Sorry.

**Comment by mkrappitz** [comment]
That means the prefixed version is from version 0.10.1 for the moment practically unusable? Or am I getting something wrong here. 

Not great, but at least that should be mentioned at https://github.com/sabbelasichon/typo3-rector-prefixed, or?

The not prefixed version unfortunately didn't work for me so far. So I will stay on 0.9.23 then.

**Comment by sabbelasichon** [comment]
No, i am using it and others too, but i think you have a specific setup or dependencies which are not working. I am working on it, believe me. But it is a lot of work to came here and to get there. Stay tuned.

**Comment by sabbelasichon** [comment]
The prefixed which version is a maintenance burden for me. Very fragile with all the scoping involved. I would really like to leverage the existing solution of Rector itself. We will get there, i promise.

**Comment by mkrappitz** [comment]
OK, understand. So it is my setup and not a problem in general. If there is anything I could help or provide to find out what is the speciality here, tell me.

**Comment by TomasVotruba** [comment]
@sabbelasichon I'm reading this and feel the burden.
Let's try something. Could create a PR where you extend this workflow with typo3 Rector install?
https://github.com/rectorphp/rector-src/blob/main/.github/workflows/build_scoped_rector.yaml#L36

Right before that line.

The other Rector packages are installed this way so it might be a light in the darkness :)

**Comment by sabbelasichon** [comment]
I will give it a try.

**Comment by sabbelasichon** [comment]
Thanks for your empathy ;-)

**Comment by mkrappitz** [comment]
Thanks a lot you too, even I'm still far away from understanding! 😅

**Comment by sabbelasichon** [comment]
@mkrappitz Now you can use rector/rector instead of all the other packages and the error should be gone.

**Comment by mkrappitz** [comment]
Great, that means my call with the latest prefixed version should still be as follows but now will work?
php74 /.config/composer/vendor/bin/rector process typo3conf/ext/template/ -c ./rector.php --dry-run --autoload-file ./autoload.php
Or do you mean I need to stop using the prefixed version and from now on the regular one? Different call then?

**Comment by sabbelasichon** [comment]
No. Just use rector/rector this is the new package to go: https://github.com/rectorphp/rector

```
composer remove ssch/typo3-rector-prefixed
composer require rector/rector --dev
```

**Comment by sabbelasichon** [comment]
All the TYPO3 rules are included there. It is the reversed version of ssch/typo3-rector-prefixed ;-)
ssch/typo3-rector-prefixed was a wrapper for rector but now typo3-rector is included in rector/rector ;-)
The rector/rector is also prefixed and downgraded to PHP 7.1

**Comment by mkrappitz** [comment]
Ok, did that and it works! 

Interesting find, when using rector/rector 0.11.7 instead of ssch/typo3-rector-prefixed 0.9.23 the Option::SKIP rector configuration part is actually being respected (for the first time?). I noticed as with this configuration after the switch to rector/rector far less files were found for changes:

```
<?php

    // If you set option Option::AUTO_IMPORT_NAMES to true, you should consider excluding some TYPO3 files.
    $parameters->set(Option::SKIP, [
        '*PageLayoutControllerHook',
        '*RecordListHook',
        NameImportingPostRector::class => [
            'ClassAliasMap.php',
            'ext_localconf.php',
            'ext_emconf.php',
            'ext_tables.php',
            getcwd() . '/**/TCA/*',
            getcwd() . '/**/Configuration/RequestMiddlewares.php',
            getcwd() . '/**/Configuration/Commands.php',
            getcwd() . '/**/Configuration/AjaxRoutes.php',
            getcwd() . '/**/Configuration/Extbase/Persistence/Classes.php',
        ],
    ]);

```

Why should files like ext_localconf.php, ext_emconf.php, ext_tables.php or for example the whole TCA being skipped in the processing? I got this part from the suggested default config at https://github.com/sabbelasichon/typo3-rector/blob/main/docs/configuration_and_processing.md#configuration-and-processing. But these are areas that definitely need changes.

**Comment by sabbelasichon** [comment]
The files are only skipped for the NameImportingPostRector so the FQN is still there. That is very important in the context of TYPO3.

**Comment by mkrappitz** [comment]
Ah ok! Anyway this config was apparently not respected in ssch/typo3-rector-prefixed 0.9.23.
