### ISSUE TITLE
Docu for special/bonus processors

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#2275]
Currently there are some processors that require a setup as they are not part of the ruleset

Those should be documented along with their usage, config and everything other to know 

Examples:
- https://github.com/sabbelasichon/typo3-rector/pull/2272
- ExtbasePersistenceVisitor ( https://github.com/sabbelasichon/typo3-rector/blob/main/src/TypoScript/Visitors/ExtbasePersistenceVisitor.php )

**Comment by sabbelasichon** [comment]
You can also take this one here #2272
