### ISSUE TITLE
Documentation: Contradictory example for TCA migration 

### ISSUE THREAD

**Issue by julianhofmann** [sabbelasichon/typo3-rector#2291]
https://github.com/sabbelasichon/typo3-rector/blob/master/docs/configuration_and_processing.md is telling  "Let´s say you want to migrate the TCA from a TYPO3 7 project to a TYPO3 9 project", but the following example does:
- *not* add TCA sets
- add Typo3SetList for 10.5 and 11, too

I'm confused...

**Comment by sabbelasichon** [comment]
You don't have to be confused. 
The sets include the TCA stuff already. So, no need to add it separately. And the part with 10 and 11 is plain wrong. Could please remove these lines? Thank you

**Comment by sabbelasichon** [comment]
Did it. Thanks for reporting.
