### ISSUE TITLE
AddReturnTypeDeclarationRector: Wrong returnType configuration for TypeConverterInterface::convertFrom()

### ISSUE THREAD

**Issue by julianhofmann** [sabbelasichon/typo3-rector#2295]
In `config/v10/typo3-100.php` the returnType for `TypeConverterInterface::convertFrom()` is defined to be `BooleanType`.
Extbase does say it's `mixed|\TYPO3\CMS\Extbase\Error\Error`....

```
new AddReturnTypeDeclaration(
    'TYPO3\CMS\Extbase\Property\TypeConverterInterface',
    'convertFrom',
    new BooleanType()
),
```

\TYPO3\CMS\Extbase\Property\TypeConverterInterface::convertFrom():
```
    /**
     * (...)
     * @return mixed|\TYPO3\CMS\Extbase\Error\Error the target type, or an error object if a user-error occurred
     */
    public function convertFrom($source, string $targetType, array $convertedChildProperties = [], PropertyMappingConfigurationInterface $configuration = null);
```

**Comment by sabbelasichon** [comment]
Thanks. Good catch. This must be a copy and paste error from the canConvertFrom. But i am happy that it worked for you thanks to static reflection. Just amazing. At least for me.
