### ISSUE TITLE
Do not duplicate keys in TCA subarrays

### ISSUE THREAD

**Issue by julianhofmann** [sabbelasichon/typo3-rector#2303]
`RichtextFromDefaultExtrasToEnableRichtextRector` does not check already existing keys of subarray (duplicates the 'enableRichtext').

<img width="879" alt="changes" src="https://user-images.githubusercontent.com/25646388/117652172-22f93b80-b193-11eb-835c-2cfea3634b67.png">

(I know, it's dirty TCA... And I'm not sure, if typo3-rector should cover all dirty edge-cases...)

**Comment by sabbelasichon** [comment]
Well, is it dirty? I don´t know. I guess it is not migrated cleanly. But rector should not be in your way. So i guess, we should check it.
