### ISSUE TITLE
Idea: Parse Core unit-tests regarding TcaMigrations and validate typo3-rector against that

### ISSUE THREAD

**Issue by MK-42** [sabbelasichon/typo3-rector#2328]
Maybe it could be doable to refactor the core TcaMigrationTest https://github.com/TYPO3/TYPO3.CMS/blob/9e1c91aed86490f75730ae186504bd900057107e/typo3/sysext/core/Tests/Unit/Migrations/TcaMigrationTest.php into a form where all testcases thrown into `TcaMigration` could be thrown at typo3-rector for validation.

I don't know if its worth the hassle, but it would show that we are producing the same stuff that the core does.

**Comment by sabbelasichon** [comment]
Thanks. But for now i don´t want to do that. This is a lot of work to go forth and back. I added a lot of tests from real world examples and also used some of the core tests. If you could come up with a quick win solution, i am fine to do so.

**Comment by sabbelasichon** [comment]
@MK-42 I am gonna transfer this to the discussions panel here: https://github.com/sabbelasichon/typo3-rector/discussions/2341
