### ISSUE TITLE
Fatal:  Undefined class constant 'T_ENUM'

### ISSUE THREAD

**Issue by Mabahe** [sabbelasichon/typo3-rector#2365]
One 10er project runs fine, but in another 10er project I run into an fatal error
In both `"ssch/typo3-rector-prefixed": "dev-main"` is required
`Fatal error: Uncaught Error: Undefined class constant 'T_ENUM' in {project}/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 517`

It seems he mixes up the vendor dirs
```
    4.6645   48820488  41. PhpParser\Lexer->__construct() phar:///{project}/vendor/ssch/typo3-rector-prefixed/vendor/phpstan/phpstan/phpstan.phar/src/Parser/LexerFactory.php:20
    4.6645   48820640  42. PhpParser\Lexer->createTokenMap() {project}/vendor/nikic/php-parser/lib/PhpParser/Lexer.php:40
```
I already deleted `/tmp/cache/` and `/tmp/rector/`

**Comment by sabbelasichon** [comment]
Could you run a 
`require nikic/php-parser:4.10.4 --dev`

explicitily in your project.

**Comment by sabbelasichon** [comment]
It is problem which will be fixed soon with the new rector/rector version.
