### ISSUE TITLE
Bug: addition of type => none in TCA overrides

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#2377]
With the latest dev-main of the prefixed version i got an issue with TCA Overrides. (commit f863060c46269925b29a79ed47aec9fbe99786c6 of prefixed rector)

~The TCA below is extended by rector and adds `'type' => 'none'` to both.~
~For ctrl this is completely wrong.~
For columns the "override" is not detected and adds `'type' => 'none'` which makes sense to add the type (still wrong though, but i can see were this is coming from)

```
$pages = [
    'ctrl' => [
        'typeicon_classes' => [
            '66' => 'tcarecords-pages-66'
        ],
    ],
    'columns' => [
        'doktype' => [
            'config' => [
                'items' => [
                    'example' => [
                        'Random label'
                        66,
                        'tcarecords-pages-66'
                    ],
                ],
            ],
        ],
```

**Comment by helsner** [comment]
I misread the rector changes - no changes are made to ctrl.
I changed the original description to be fitting - i left the old info to not irritate by deleting stuff..

**Comment by sabbelasichon** [comment]
@MK-42 Could you please check if it is possible to determine if we must add the type none?
If not, i would rather drop this Rule. Never needed it. And if it does more harm than good. Kill it.

**Comment by sabbelasichon** [comment]
@MK-42 We are going to remove this Rule. It is not really valuable anyways.

**Comment by MK-42** [comment]
Another option would be to not refactor overrides for this rule but only 'safe' full TCA arrays. But that might not be worth it as well.
