### ISSUE TITLE
Document all non php FileProcessors in template file

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#2408]
It would be nice to add more of the FileProcessors like the FlexForm one or more sets with comments to the https://github.com/sabbelasichon/typo3-rector/blob/main/templates/rector.php.dist file

**Comment by sabbelasichon** [comment]
Would you like to add those additional sets and comments to the template file?

**Comment by helsner** [comment]
Yes, i can do that.
What are you thinking of?
I also would add the composer processing for the core/third-party packages
