### ISSUE TITLE
Migrate TSconfig condition `adminUser`

### ISSUE THREAD

**Issue by kitzberger** [sabbelasichon/typo3-rector#2411]
# Feature Request: migrate TS condition `adminUser`

In my "book of migration snippets" (:tm:) I've found something that's seems to be uncovered in the typo3-rector yet.

## Diff

My example here is a TSconfig file with the extension `.tsconfig` that contains a condition checking if the BE user is an admin.

```diff
-[adminUser = 1]
+[backend.user.isAdmin]
```

### Doc references

* TYPO3 8: https://docs.typo3.org/m/typo3/reference-tsconfig/8.7/en-us/Conditions/Index.html#adminuser
* TYPO 10: https://docs.typo3.org/m/typo3/reference-tsconfig/10.4/en-us/UsingSetting/Index.html#backend-user

**Comment by sabbelasichon** [comment]
What is the opposite in the Symfony Expression language style
```
[! backend.user.isAdmin]
```
