### ISSUE TITLE
Migrate INCLUDE_TYPOSCRIPT

### ISSUE THREAD

**Issue by kitzberger** [sabbelasichon/typo3-rector#2414]
# Feature Request: Migrate TS include statements

Some (all?) INCLUDE_TYPOSCRIPT statements seem to be uncovered by typo3-rector.

Here's some regexes that I often use to handle them:

| Old | New |
| -- | -- |
| `<INCLUDE_TYPOSCRIPT: source="FILE:EXT:(.*)">` | `@import 'EXT:\1'` |
| `<INCLUDE_TYPOSCRIPT: source="FILE:typo3conf/ext/(.*)">` | `@import 'EXT:\1'` |
| `<INCLUDE_TYPOSCRIPT: source="FILE:fileadmin/(.*)">` | `@import 'fileadmin/\1'` |
| `<INCLUDE_TYPOSCRIPT: source="DIR:EXT:(.+)" extensions="(.+)">` | `@import 'EXT:\1*.\2'` |

Be careful with the latter, since the new syntax doesn't support recursive inclusion!

## Diff

```diff
-<INCLUDE_TYPOSCRIPT: source="FILE:EXT:fluid_styled_content/Configuration/TypoScript/constants.typoscript">
+@import 'EXT:fluid_styled_content/Configuration/TypoScript/constants.typoscript'

-<INCLUDE_TYPOSCRIPT: source="DIR:EXT:my_ext/Configuration/TsConfig/User/" extensions="tsconfig">
+@import 'EXT:my_ext/Configuration/TsConfig/User/*.tsconfig'
```

**Comment by sabbelasichon** [comment]
Thanks. We have discussed it already and for files exist a rule. Would love to see it in action. But as you said, for directories the older syntax does a recursive inclusion. We have decided not to offer a rule for that, because it would break stuff. And the older syntax is still allowed.

**Comment by kitzberger** [comment]
@sabbelasichon, thanks for the clarification!

Just a thought: maybe only migrate those when importing some kinda "experimental" Typo3SetList?

**Comment by sabbelasichon** [comment]
I would prefer not to have a random set list, but just use the single rule itself in the configuration like so

```php
$services = $containerConfigurator->services();
$services->set(Ssch\TYPO3Rector\FileProcessor\TypoScript\Visitors\FileIncludeToImportStatementVisitor::class);
```
