### ISSUE TITLE
Rewrite outdated typoscript conig

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#2429]
# Feature Request
https://github.com/TYPO3/TYPO3.CMS/commit/f998e96f221fa4c6b38548ddfa62704e3d4298e3#diff-247a02d93e3d0b9b8cf824e52837e37083ef9a39603bd3a241c9a4768ceb3642

This might be a long shot, but we could check for locale_all within typoscript files and mark them as not relevant.

Also - that's how i got there - the `linkData-PostProc` is removed, which is not mentioned in the code scanner, also there is no restfile.
This might be for documentation, but we could figure out what to do with that as replacement and provide it as report in rector.
I will check the replacement as i got this issue on a current project, so i hope i can provide some more infos (or docu)

**Comment by sabbelasichon** [comment]
After thinking about it, i would prefer not to do so. It will probably break users code and we cannot predict the users intention. The topic is too big to handle right. Let´s close it for now.
