### ISSUE TITLE
Conversion of TypoScript extbase persistence to php File issues

### ISSUE THREAD

**Issue by mkrappitz** [sabbelasichon/typo3-rector#2434]
Using rectorphp/rector 0.11.10 the conversion of extbase peristence to php file is working not as i would expect.

My call:
php74 /.config/composer/vendor/bin/rector process typo3conf/ext/extension/ -c ./rector.php --autoload-file ./autoload.php

The Typoscript original code in EXT:extension/ext_typoscript_setup.txt:
```
config.tx_extbase {
    persistence {
        classes {
            AEMKA\Extension\Domain\Model\Order.newRecordStoragePid = 5
            AEMKA\Extension\Domain\Model\User {
                mapping {
                    tableName = fe_users
                    recordType >
                }
            }
            AEMKA\Extension\Domain\Model\Content {
                mapping {
                    tableName = tt_content
                    recordType >
                }
            }
            AEMKA\Extension\Domain\Model\Page {
                mapping {
                    tableName = pages
                    recordType >
                }
            }
        }
    }
}
```

The conversion result:
```
<?php

declare (strict_types=1);
namespace RectorPrefix20210604;

return \[
    'AEMKA\\Extension\\Domain\\Model\\User' => [
        'tableName' => 'fe_users',
    ],
    'AEMKA\\Extension\\Domain\\Model\\Content' => [
        'tableName' => 'tt_content',
    ],
    'AEMKA\\Extension\\Domain\\Model\\Page' => [
        'tableName' => 'pages',
    ],
];
```

The expected conversion result:
```
<?php
declare (strict_types=1);

return [
    \AEMKA\Extension\Domain\Model\Order::class => [
        'newRecordStoragePid' => 5,
    ],
    \AEMKA\Extension\Domain\Model\User::class => [
        'tableName' => 'fe_users',
        'recordType' => null,
    ],
    \AEMKA\Extension\Domain\Model\Content::class => [
        'tableName' => 'tt_content',
        'recordType' => null,
    ],
    \AEMKA\Extension\Domain\Model\Page::class => [
        'tableName' => 'pages',
        'recordType' => null,
    ],
];
```

The "\\" right after the return statement is a clear error. The namespace RectorPrefix20210604 probably also. The class syntax is more cosmetics. About the "recordType" and the "newRecordStoragePid" I'm not exactly sure myself.

**Comment by mkrappitz** [comment]
Update, the newRecordStoragePid setting in the Classes.php has no effect. It has to stay in Typoscript for the moment, which makes really no sense to me, but thats how it is in v10.

**Comment by sabbelasichon** [comment]
Just to get the impression right, because i am writing tests for all the features.
The culprit is the prefixed version: https://github.com/rectorphp/rector/blob/main/vendor/ssch/typo3-rector/templates/maker/Extbase/Persistence.tpl.php

**Comment by mkrappitz** [comment]
Not sure if the namespace is actually causing problems. But I just think it should better not be there.

**Comment by sabbelasichon** [comment]
It should not be there. It wasn´t before and we excluded these files from prefixing. Not it is there again. Don´t know why.

**Comment by mkrappitz** [comment]
One more nice find: rector creates the properties mappings with key "fieldname", but it needs to be "fieldName".

**Comment by sabbelasichon** [comment]
@mkrappitz Could you elaborate on that. Don´t get it. Maybe you could create a failing test here.

**Comment by mkrappitz** [comment]
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html and there the following part:
```
'properties' => [
            'title' => [
                'fieldName' => 'title'
            ],
            'path' => [
                'fieldName' => 'path'
            ],
            'isAbsolutePath' => [
                'fieldName' => 'base'
            ],
        ],
```

Rector is generating this part, but with "fieldname" instead of the correct "fieldName".

**Comment by sabbelasichon** [comment]
@mkrappitz https://github.com/sabbelasichon/typo3-rector/pull/2444/files
