### ISSUE TITLE
Suggestion for extbase php based views

### ISSUE THREAD

**Issue by mkrappitz** [sabbelasichon/typo3-rector#2436]
Until v9 it was possible to place a rendering php class (to  bypass standard fluid rendering) file in EXT:myextension/Classes/View/Mycontroller/MyactionJSON.php and you could just use it adding the &tx_myextension_myplugin[format]=FORMAT parameter in the url (plus an appropriate page type). From v10 in your controller you additionally need to define the rendering php class like this:

```
    /**
     * action initializeMyaction
     *
     * @return void
     */
    public function initializeMyactionAction()
    {
        $arguments = $this->request->getArguments();
        if (isset($arguments['format']) && $arguments['format'] === 'JSON') {
            $this->defaultViewObjectName = \VENDOR\Myextension\View\Mycontroller\MyactionJSON::class;
        }
    }
```

Is this worth a rector rule or is this more a misunderstanding of me?

**Comment by sabbelasichon** [comment]
I tried it. But it is not reliable fixable. Sorry. But thanks for the suggestions. Good catch
