### ISSUE TITLE
TypoScript conditon [browser == msie] gets removed - remaining [else] condition causes error

### ISSUE THREAD

**Issue by tgaertner** [sabbelasichon/typo3-rector#2450]
# rector breaks the typoscript code while removing old conditions

e.g. this old code
```
[browser == msie] && [version =< 9]
   ...
[else]
   ...
[global]

```
results in

```
...
[else]
...
[global]
```

**Comment by sabbelasichon** [comment]
Solved.

**Comment by simonschaufi** [comment]
@sabbelasichon shouldn't in this case the whole block with the else be removed as the condition doesn't get parsed in newer TYPO3 versions anyway? Or commented out with a comment to refactor this block manually?

**Comment by sabbelasichon** [comment]
Yeah. That would be nice. But the parser doesn't not support that at the moment.
