### ISSUE TITLE
Environment::getPublicPath() in constant declaration

### ISSUE THREAD

**Issue by verdure-koehnlein** [sabbelasichon/typo3-rector#2451]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.14             |

First of all, thanks for this great tool. I really love to use it. I found this little problem, wich maybe could be interessting for you.

I had a class constant which uses `PATH_site` as prefix. This constant is replaced by ` Environment::getPublicPath()` which makes the code run into a fatal error: `Fatal error: Constant expression contains invalid operations ...`

## Minimal PHP Code Causing Issue

```php
class MyClass
{
    protected const LOGFILE = PATH_site . 'secured/logs/confirmation.csv';
}
```

## Expected Behaviour

I would expect to **_not_** have a method call in a constant declaration.

```php
class MyClass
{
    protected const LOGFILE = Environment::getPublicPath() . '/' . 'secured/logs/confirmation.csv';
}
```

Maybe a solution could be to use PHP's global constant `__DIR__` in combination with relative path?

```php
class MyClass
{
    protected const LOGFILE = __DIR__ . '/../../../../htdcos/' . 'secured/logs/confirmation.csv'; 
}
```

**Comment by sabbelasichon** [comment]
The only solution for me now is skipping it and use the extension scanner to identify the occurrence of the old constant.
