### ISSUE TITLE
Convert "or die();" to "|| die();"

### ISSUE THREAD

**Issue by einpraegsam** [sabbelasichon/typo3-rector#2452]
Possible feature request

Convert those lines in TCA configuration:
```
defined('TYPO3_MODE') or die();
```

to:
```
defined('TYPO3_MODE') || die();
```

**Comment by sabbelasichon** [comment]
Could you explain more in detail why this is useful or relevant in the context of TYPO3? I am aware of the operator precedence but i think it doesn´t really matter here. So i would not write a rule for that because it is very subjective.

**Comment by sabbelasichon** [comment]
Feel free to reopen, if you can explain why it is better.
