### ISSUE TITLE
Lost indent after typoscript change

### ISSUE THREAD

**Issue by ayacoo** [sabbelasichon/typo3-rector#2458]
Maybe more a question than an issue? We have an old issue https://github.com/sabbelasichon/typo3-rector/issues/2448 here and maybe this is related. I am missing some feedback in the issue as to why it was closed?

After processing we lost the indent, too. In the source file we have a 4 point indent.

Version: 0.11.16 via rector/rector

**Example code**
```
[applicationContext = "Development*"]
    config.tx_realurl_enable = 0
[global]
```

**Result**
```
[applicationContext == "Development*"]
config.tx_realurl_enable = 0
[global]
```

**Expected result**
```
[applicationContext == "Development*"]
    config.tx_realurl_enable = 0
[global]
```

**Comment by sabbelasichon** [comment]
@ayacoo I know. I haven´t mentioned it in the issue itself but personally via direct message. 
These kind of issue(s) should be create here: https://github.com/martin-helmich/typo3-typoscript-parser
Could you open up this issue there. I am gonna try to fix this.

**Comment by sabbelasichon** [comment]
It must be the right place, because i am using the PrettyPrinter of this package to write the Typoscript back. But i will verify it first. Let´s see.

**Comment by sabbelasichon** [comment]
@ayacoo I have checked it and it must be an issue in the parser itself. Have a look at these two files:

https://github.com/martin-helmich/typo3-typoscript-parser/blob/master/tests/functional/Parser/Fixtures/Assignments/comment_multiline.typoscript

https://github.com/martin-helmich/typo3-typoscript-parser/blob/master/tests/functional/Parser/Fixtures/Assignments/comment_multiline.typoscript.print

The first one is the input and the second one the output. The trailing whitespaces are lost here while writing back to file. 
Could you open up an issue here: https://github.com/martin-helmich/typo3-typoscript-parser

**Comment by sabbelasichon** [comment]
Same will happen for conditions. It is just cosmetics but would be nice if the format is kept.
