### ISSUE TITLE
Converting of extbase table mapping from TypoScript to Classes.php

### ISSUE THREAD

**Issue by einpraegsam** [sabbelasichon/typo3-rector#2459]
It took some time to find out why my field mapping doesn't work any more.

Reason: Rector added a Classes.php like
```
return [
    \In2code\In2template\Domain\Model\Toolbar::class => [
        'tableName' => 'pages',
        'properties' => [
            'active' => [
                'fieldname' => 'toolbar_active',
            ],
....
```

Problem here: `fieldName` with an upper N would be correct.

Thx for the nice tool so far

Alex

BTW: If this is fixed meanwhile (I used a rector converting last week), you can close this issue.
Reference: https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/6-Persistence/4-use-foreign-data-sources.html

**Comment by sabbelasichon** [comment]
It is fixed already. Thanks for your report

**Comment by sabbelasichon** [comment]
https://github.com/sabbelasichon/typo3-rector/releases/tag/v0.11.15

**Comment by sabbelasichon** [comment]
The problem right now is that rector/rector is not releasing that often anymore. We have to change that.
