### ISSUE TITLE
A simple key "language" is replaced by "LanguageService::class"

### ISSUE THREAD

**Issue by ayacoo** [sabbelasichon/typo3-rector#2481]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | rector/rector v0.11.25             |

## Minimal PHP Code Causing Issue

Context: We proceed an upgrade from v9 to v10. rector.php just includes these rules:

```
    $containerConfigurator->import(Typo3SetList::TYPO3_104);
    $containerConfigurator->import(Typo3SetList::TCA_104);
```

I noticed that a simple array with the key language is replaced by the LanguageService. Attached is a quick example + result.

![image](https://user-images.githubusercontent.com/5963331/123550748-54dc5680-d76f-11eb-8420-00240561042a.png)

## Expected Behaviour

Simple arrays with the key 'language' should not be changed.

## Affected line
https://github.com/sabbelasichon/typo3-rector/blob/main/Migrations/Code/ClassAliasMap.php#L877

**Comment by ayacoo** [comment]
This then also affects this line

```
- $languageId = GeneralUtility::makeInstance(Context::class)->getPropertyFromAspect('language', 'id');
+ $languageId = GeneralUtility::makeInstance(Context::class)->getPropertyFromAspect(LanguageService::class, 'id');
```

**Comment by sabbelasichon** [comment]
Are you sure that no other rule is defined here? I guess that StringClassNameToStringClassConstantRector is to blame. Could you check this first. Thank you

**Comment by ayacoo** [comment]
Of course. The rector isn't set. The trigger is this line in rector.php: 

`$containerConfigurator->import(Typo3SetList::UNDERSCORE_TO_NAMESPACE);`

![image](https://user-images.githubusercontent.com/5963331/123557210-e5c32a00-d78f-11eb-8b7e-9c807b9e40cb.png)

**Comment by sabbelasichon** [comment]
I see. Should be fixable.
