### ISSUE TITLE
Rule for PasswordHashFactory::getSaltingInstance

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#2489]
# Feature Request
PasswordHashFactory::getSaltingInstance has been marked as deprecated with v9 and is dropped in v10.
We could add a rule here to replace that.
The replacing might be different depending on the implementation so we should be careful how we replace or might event not replace, but report that there are changes needed

## Diff

```diff
- PasswordHashFactory::getSaltingInstance()->getHashedPassword(random_bytes(32) . '|' . $username);
+ GeneralUtility::makeInstance(PasswordHashFactory::class)->getDefaultHashInstance('FE')->getHashedPassword(random_bytes(32) . '|' . $username);
```

Changelog entry:
`typo3/sysext/core/Documentation/Changelog/9.4/Deprecation-85796-SaltedPasswordsCleanups.rst`

**Comment by helsner** [comment]
This issue could be one i'll try to learn rector with.
The result might be different as it is not a 100% clear but i'll discuss that with you Sebastian

**Comment by sabbelasichon** [comment]
@helsner Let´s do a small pair programming session and i am going to show you how you can create or approach this rule.

**Comment by sabbelasichon** [comment]
@helsner After thinking more about it, i would say we cannot reliable create a rule for that and the extension finds the call anyways. I would reject to add a rule for that which is only half done.
