### ISSUE TITLE
$GLOBALS['TSFE']->renderCharset getting replaced in assignment

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#2491]
latest version

$GLOBALS['TSFE']->renderCharset = 'utf-8';

## Minimal PHP Code Causing Issue
```
- $GLOBALS['TSFE']->renderCharset = 'utf-8';
+'utf-8' = 'utf-8';

```
## Expected Behaviour
Nothing to happen

**Comment by helsner** [comment]
I'll try that one

**Comment by helsner** [comment]
ok i'm kinda lost on this one :D i don't get anything on how to solve
i would extend the `shouldSkip` check, but i don't know how to check for this

**Comment by sabbelasichon** [comment]
@helsner No problem. I will create a Pull Request and assign you as a reviewer.
