### ISSUE TITLE
`[globalString = IENV:HTTPS=on]` => `[ERROR not implemented]`

### ISSUE THREAD

**Issue by vertexvaar** [sabbelasichon/typo3-rector#2509]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.36 (`c424040f97e506d29d32d58d64c2bbb8a5ee417c`)             |

![image](https://user-images.githubusercontent.com/5594393/125777966-b7bbd437-b6b6-4158-bd1d-ceaaba160112.png)

## Minimal Typoscript Code Causing Issue

```typoscript
[globalString = IENV:HTTPS=on]
  PROTOCOL = https://
[end]
```

## Expected Behaviour

In an ideal world the condition would translate to the method which _should_ actually be called. This is a non-generic mapping from a special condition to an exact transformation.

```typoscript
[request.getNormalizedParams().isHttps()]
  PROTOCOL = https://
[end]
```

I am not aware of a generic typoscript condition that can replace `IENV` in a `globalString` condition, so this is my only solution proposal, and i'm not even remotely mad if it doesn't make it into typo3-rector because i am aware that this case should most probably be handled manually anyway :sweat_smile:

**Comment by helsner** [comment]
Thx for your report, i guess i got the solution with my patch.
Sebastian did some amazing thing with that typoscript condition matcher - we'll wait for his return to merge this 👌
