### ISSUE TITLE
Fatal error: Declaration must be compatible with`Helmich\TypoScriptParser\Parser\Traverser\Visitor::enterTree`

### ISSUE THREAD

**Issue by vertexvaar** [sabbelasichon/typo3-rector#2510]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. 0.11.36             |

I installed rector via composer (as described here: https://github.com/sabbelasichon/typo3-rector/blob/main/docs/installation.md#installation),
 created the rector.php file (https://github.com/sabbelasichon/typo3-rector/blob/main/docs/configuration_and_processing.md#configuration-and-processing) and tried to execute rector with `vendor/bin/rector process`. The following exception appeared (reproducible on my colleagues laptop)

We are both running PHP in docker based on the official php:7.2-fpm and php:7.4-fpm images.

```
Fatal error: Declaration of Ssch\TYPO3Rector\FileProcessor\TypoScript\Rector\AbstractTypoScriptRector::enterTree(array $statements): void must be compatible with RectorPrefix20210710\Helmich\TypoScriptParser\Parser\Traverser\Visitor::enterTree($statements): void in /app/vendor/rector/rector/vendor/ssch/typo3-rector/src/FileProcessor/TypoScript/Rector/AbstractTypoScriptRector.php on line 22
```

**Comment by sabbelasichon** [comment]
Use version 0.11.32 for now. I am gonna fix this after the vacations

**Comment by helsner** [comment]
This issue will extend its message to all of der Visitor interface methods as all of them are missing the "Statement" or array type hint in rector/rector.
In typo3-rector everything is fine, but something seems of to me within rector/rector as there the type hints are missing.
Also affected:
`OldConditionToExpressionLanguageTypoScriptRector` 
`AdditionalHeadersToArrayTypoScriptRector`

**Comment by sabbelasichon** [comment]
@TomasVotruba Sorry for bothering you but this issue seems related to https://github.com/rectorphp/rector/issues/6556. What must be done from my side to get this working?

**Comment by TomasVotruba** [comment]
I'm fully focused somewhere else now. 
But we'll resolve this on Friday together :+1:

**Comment by sabbelasichon** [comment]
@TomasVotruba Forgotten to mention this issue here. Could you point me in the right direction here.

**Comment by sabbelasichon** [comment]
Problem solved. Rector release 0.11.47 is now compatible again. Thanks for your patience.
