### ISSUE TITLE
TemplateResolver::supports(string $type): bool must be compatible with Rector\Core\Contract\Template\TemplateResolverInterface::supports($type)

### ISSUE THREAD

**Issue by JBlocks** [sabbelasichon/typo3-rector#2517]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| TYPO3 Rector version | v0.10.6  |
| Rector version | dev-main c231e32 |

After installing sabbelasichon/typo3-rector v0.10.6, there is an incompatible type exception.

`$ ./vendor/bin/rector --version
PHP Fatal error:  Declaration of Ssch\TYPO3Rector\Template\TemplateResolver::supports(string $type): bool must be compatible with Rector\Core\Contract\Template\TemplateResolverInterface::supports($type): bool in /var/www/html/Source/vendor/ssch/typo3-rector/src/Template/TemplateResolver.php on line 26
Fatal error: Declaration of Ssch\TYPO3Rector\Template\TemplateResolver::supports(string $type): bool must be compatible with Rector\Core\Contract\Template\TemplateResolverInterface::supports($type): bool in /var/www/html/Source/vendor/ssch/typo3-rector/src/Template/TemplateResolver.php on line 26
`

```
Using version ^0.10.6 for ssch/typo3-rector                                                                                                                            
./composer.json has been updated
Running composer update ssch/typo3-rector
Loading composer repositories with package information
Updating dependencies                                 
Lock file operations: 3 installs, 0 updates, 0 removals
  - Locking phpstan/phpstan (0.12.93)
  - Locking rector/rector (dev-main c231e32)
  - Locking ssch/typo3-rector (v0.10.6)
```

## Minimal PHP Code Causing Issue

For PHP 7.4: `composer req --dev ssch/typo3-rector:^0.10`

## Expected Behaviour

No errors with incompatiblity to rector core.

**Comment by helsner** [comment]
Is there a reason you're using typo3-rector in v0.10.6?
The current version is v0.11.22.

Also you can use the original rector/rector without telling the typo3-rector version as it will be installed automatically.

**Comment by JBlocks** [comment]
If you try to install TYPO3 rector with `composer req --dev ssch/typo3-rector` and you only have PHP v7.4, composer doesnt install the package. The requirement of PHP v8.x is set in the composer.json from version 0.11.x on.

**Comment by sabbelasichon** [comment]
Use rector/rector please unless you want to contribute to typo3-rector itself

**Comment by helsner** [comment]
typo3-rector is part of rector/rector by now
So the correct was to install is via rector in general

Rector "downgrades" the Code automatically to PHP 7.1 so everybody can use it.
Meanwhile the Code in DEV is written in PHP 8

As Sebastian said, pls use typo3-rector only for DEV

**Comment by JBlocks** [comment]
Thanks for clarification and your advice!
