### ISSUE TITLE
Recommendation: Adapt TYPO3_MODE handling in ext_* files

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#2522]
I'm on an small v11 upgrade check and installed rector.

I got the following line in my ext_tables.php:
`if (TYPO3_MODE === 'BE') {...`

This will not be substituted by the rector rule as it specifically checks for the file it is in and returns null in case of ext_loca.. and ext_ta..
IMHO we should at least report this usage to the DEV
It is not recommended to do this anyway, so we should use the power of rector to hint the issue with the constant usage and the overall bad practice.

https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ExtensionArchitecture/ConfigurationFiles/Index.html#rules-and-best-practices

**Comment by helsner** [comment]
would change this myself if you're ok with that @sabbelasichon

**Comment by sabbelasichon** [comment]
Go for it.

**Comment by sabbelasichon** [comment]
@helsner I do not want to mix concerns here. For reporting stuff we should use https://github.com/sabbelasichon/typo3-phpstan-rules which is still under heavy development. 
But i am adding rules to check the config files already. One of them will check the usage of the constants.
