### ISSUE TITLE
Missing GeneralUtilityToUpperAndLowerRector and RefactorVariousGeneralUtilityMethodsRector in config/v8/typo3-81.php

### ISSUE THREAD

**Issue by kszymukowicz** [sabbelasichon/typo3-rector#2527]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.32             |

Looks like in file `config/v8/typo3-81.php` there is no registration of two tests that are in `src/Rector/v8/v1`. 
Or its intended ?
```
    $services->set(\Ssch\TYPO3Rector\Rector\v8\v1\GeneralUtilityToUpperAndLowerRector::class);
    $services->set(\Ssch\TYPO3Rector\Rector\v8\v1\RefactorVariousGeneralUtilityMethodsRector::class);
```

**Comment by sabbelasichon** [comment]
Good catch. Could you provide a PR for that.

**Comment by kszymukowicz** [comment]
Sure. Ready at /pull/2528
