### ISSUE TITLE
Convert Extbase command outputLine() to Symfony OutputInterface::writeln()

### ISSUE THREAD

**Issue by masi** [sabbelasichon/typo3-rector#2555]
# Feature Request

Convert occurences of CommandController::outputLine() with OutputInterface::writeln().

## Current Behaviour

`$this->outputLine('foorbar');`

## New Behaviour

`$output->writeln('foorbar');`

**Comment by sabbelasichon** [comment]
@masi Maybe it is still interesting. Finally it is done.
