### ISSUE TITLE
[DISCUSSION] Refactor old icon path

### ISSUE THREAD

**Issue by ayacoo** [sabbelasichon/typo3-rector#2560]
First of all as a basis for discussion, as I am not aware whether this is possible and whether it still makes sense to put effort into it.

**Old code (Icon API is fine):**

```
    \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Core\Imaging\IconRegistry::class)
        ->registerIcon(
            'apps-pagetree-reference',
            TYPO3\CMS\Core\Imaging\IconProvider\SvgIconProvider::class,
            [
                'source' => 'typo3/sysext/core/Resources/Public/Icons/T3Icons/content/content-text.svg',
            ]
        );
```

**New code (Icon API is fine)**

```
    \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Core\Imaging\IconRegistry::class)
        ->registerIcon(
            'apps-pagetree-reference',
            TYPO3\CMS\Core\Imaging\IconProvider\SvgIconProvider::class,
            [
                'source' => 'typo3/sysext/core/Resources/Public/Icons/T3Icons/svgs/content/content-text.svg',
            ]
        );
```

So we have only added a SubFolder. This was done with 10.4.10: https://github.com/TYPO3/typo3/tree/v10.4.10/typo3/sysext/core/Resources/Public/Icons/T3Icons/svgs

References: 

- https://review.typo3.org/c/Packages/TYPO3.CMS/+/66585
- https://forge.typo3.org/issues/92833

I am curious about your opinions :-)

**Comment by sabbelasichon** [comment]
Looks doable for me at the first glimpse.

**Comment by simonschaufi** [comment]
This is also related to https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.4/Feature-94692-RegisteringIconsViaServiceContainer.html and even though it is a new feature, the old php way is not recommended any more

**Comment by sabbelasichon** [comment]
@ayacoo Does it look right: https://github.com/sabbelasichon/typo3-rector/pull/2659
