### ISSUE TITLE
Invalid extbase property not reported

### ISSUE THREAD

**Issue by georgringer** [sabbelasichon/typo3-rector#2567]
Processing a model with an invalid annotation should report a warning or maybe an error instead of just skipping (?) it.

Example
```php
 	/**
	 * datetimeto
	 *
	 * @var \DateTimeTo
	 */
	protected $datetimeto = NULL;
```

Problem is the `var \DateTimeTo` which is of course wrong and must be `var \DateTime`. As there is no class `DateTimeTo`, this should be found

**Comment by sabbelasichon** [comment]
@georgringer This should be the responsibility by tools like PHPStan. If you think it is reliable fixable open an issue on https://github.com/rectorphp/rector
