### ISSUE TITLE
Removed TypoScriptCondition leaves only brackets

### ISSUE THREAD

**Issue by cepheiVV** [sabbelasichon/typo3-rector#2568]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.53             |

Leaves this TypoScript condition with empty brackets, causing a fatal error in TYPO3 frontend, because subsequent TypoScript won't be parsed by TYPO3.

<img width="523" alt="Screenshot 2021-09-16 at 21 39 34" src="https://user-images.githubusercontent.com/2963482/133632370-ed4f6335-2fdf-4c00-804d-6c5f2ffc72ad.png">

## Minimal PHP Code Causing Issue

Is was running the rector config with:
```
    $containerConfigurator->import(Typo3SetList::TYPO3_76);
    $containerConfigurator->import(Typo3SetList::TYPO3_87);
    $containerConfigurator->import(Typo3SetList::TYPO3_95);
    $containerConfigurator->import(Typo3SetList::TYPO3_104);
```

## Expected Behaviour

Set correct condition or don't change it at all.

**Comment by sabbelasichon** [comment]
@cepheiVV Thanks for the report. It will be fixed soon.
