### ISSUE TITLE
Show message on change in composer.json that composer.lock should get updated (if that is the case)

### ISSUE THREAD

**Issue by sypets** [sabbelasichon/typo3-rector#2570]
Please feel free to close if this does not make sense or I have misunderstood something. I am still pretty new to rector.

# Feature Request

Show a warning or informational message if a change in `composer.json` warrants updating the `composer.lock` file.

For example, rector may change the requirements in composer.json (e.g. when you are using `$containerConfigurator->import(Typo3SetList::COMPOSER_PACKAGES_110_CORE);` etc.). This will usually (always?) require updating composer.lock in some way (e.g. via `composer update`).

If not doing so will leave the project in an inconsistent state with changes to composer.json already made.

**Comment by sabbelasichon** [comment]
As the composer rules are just a starting point and not the end of the migration i would vote against doing a composer update after running rector. Most of the time it fails anyways. The composer update was done btw. at the beginning but was dropped intentionally afterwards by Tomas and me.
