### ISSUE TITLE
Loading extension config breaks frontend

### ISSUE THREAD

**Issue by cepheiVV** [sabbelasichon/typo3-rector#2573]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.11.53            |

When the configuration is not available:
 - The old code returns `false`
 - The new code throws a fatal error in the FE
 
<img width="759" alt="Screenshot 2021-09-20 at 16 27 01" src="https://user-images.githubusercontent.com/2963482/133981324-643c68fd-5048-4e71-8788-04212e728223.png">

Using rector config:
```
    $containerConfigurator->import(Typo3SetList::TYPO3_76);
    $containerConfigurator->import(Typo3SetList::TYPO3_87);
    $containerConfigurator->import(Typo3SetList::TYPO3_95);
    $containerConfigurator->import(Typo3SetList::TYPO3_104);
```

## Expected Behaviour

Fail soft. Don't break the frontend.

**Comment by sabbelasichon** [comment]
@cepheiVV. Thanks. What would you change in your case to fail soft?

**Comment by cepheiVV** [comment]
Not sure if this should be considered a TYPO3 bug, since it didn't break the FE before.
Wrap it in a try/catch block?

**Comment by sabbelasichon** [comment]
After thinking about it, i would say we should leave it as it is and everyone should deal with it as they like. I would not suppress the exception. I have never encountered a case where it should have been ignored.
