### ISSUE TITLE
Migrate GeneralUtility::isFirstPartOfStr to str_starts_with

### ISSUE THREAD

**Issue by georgringer** [sabbelasichon/typo3-rector#2574]
See https://review.typo3.org/c/Packages/TYPO3.CMS/+/70444.

this is btw also valid for TYPO3 10 (See https://review.typo3.org/c/Packages/TYPO3.CMS/+/71134)

**Comment by sabbelasichon** [comment]
Thanks. If you have more use cases let me know. You are definitely more into the core development than me. I am not aware of all these things. Thank you.

**Comment by georgringer** [comment]
@sabbelasichon also `str_ends_with` can be migrated, see https://review.typo3.org/c/Packages/TYPO3.CMS/+/71135

**Comment by georgringer** [comment]
@sabbelasichon this is also valid for v10

**Comment by sabbelasichon** [comment]
@georgringer I have seen that. But today we vote against it to introduce it for version 10 already. Because it is not deprecated there.
