### ISSUE TITLE
Deprecation: #94311 - GeneralUtility::rmFromList

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#2601]
Deprecation: #94311 - GeneralUtility::rmFromList

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.3/Deprecation-94311-DeprecatedGeneralUtilityrmFromList.html
.. include:: ../../Includes.txt

================================================
Deprecation: #94311 - GeneralUtility::rmFromList
================================================

See :issue:`94311`

Description
===========

The method :php:`\TYPO3\CMS\Core\Utility\GeneralUtility::rmFromList()` has not
been used in the Core since v10. The method has now been deprecated
in :php:`\TYPO3\CMS\Core\Utility\GeneralUtility` and will be removed in
TYPO3 v12.

Impact
======

Calling the method will trigger a PHP :php:`E_USER_DEPRECATED` error.

Affected Installations
======================

All TYPO3 installations calling this method in custom code. The extension
scanner will find all such usages as strong match.

Migration
=========

Replace all usages of the method in your extension code.

.. index:: PHP-API, FullyScanned, ext:core

**Comment by sabbelasichon** [comment]
implode(',', array_filter(explode(',', $list), function($item) use($element) {
           return $element == $item;
        }));

**Comment by helsner** [comment]
lol i was on the same one right now.. :D thanks though! yours looks better and probably works 😂

**Comment by helsner** [comment]
@sabbelasichon i need help with the function init via rector
