### ISSUE TITLE
Deprecation: #95367 - GeneralUtility::isAbsPath()

### ISSUE THREAD

**Issue by simonschaufi** [sabbelasichon/typo3-rector#2661]
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.5/Deprecation-95367-GeneralUtilityisAbsPath.html

**Comment by sabbelasichon** [comment]
Thanks, but please don´t add this issue from the changelogs manually. I have a local Symfony Application taking care of this.

**Comment by sabbelasichon** [comment]
I am gonna add the ones from 11.5 automatically.
