### ISSUE TITLE
ExtbasePersistenceTypoScriptRector vs. more than one enhancement of the same model

### ISSUE THREAD

**Issue by kitzberger** [sabbelasichon/typo3-rector#2703]
# Bug Report

With the generated `Configuration/Extbase/Persistence/Classes.php` created by running `ExtbasePersistenceTypoScriptRector` it's currently not possible to enhance the same extbase model more than once. The `subclasses` array is lacking its associated array keys.

Current output (stripped!):

```php
return [
    \Vendor\MyExtension\Domain\Model\Record::class => [
        'subclasses' => [
            \Vendor\MyOtherExtension\Domain\Model\OtherRecord::class,
        ],
    ],
];
```

Fixed output:

```php
return [
    \Vendor\MyExtension\Domain\Model\Record::class => [
        'subclasses' => [
            'othertype' => \Vendor\MyOtherExtension\Domain\Model\OtherRecord::class,
        ],
    ],
];
```

**Comment by sabbelasichon** [comment]
@kitzberger Could you show me your TypoScript configuration so i can add a test for that and fix the issue.
