### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by andiyps** [sabbelasichon/typo3-rector#2738]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| rector/rector | 0.12.5 |
| ssch/typo3-rector | 0.11.31 |
|PHP | 8.0.11 |

I am upgrading to TYPO3 11.5. However, I get a fatal error: 

` ./vendor/bin/rector process src/tolle_extension --dry-run`

`PHP Fatal error:  Declaration of Ssch\TYPO3Rector\FileProcessor\FlexForms\FlexFormsProcessor::supports(Rector\Core\ValueObject\Application\File $file, Rector\Core\ValueObject\Configuration $configuration): bool must be compatible with Rector\Core\Contract\Processor\FileProcessorInterface::supports($file, $configuration): bool in /var/www/html/vendor/ssch/typo3-rector/src/FileProcessor/FlexForms/FlexFormsProcessor.php on line 62
Fatal error: Declaration of Ssch\TYPO3Rector\FileProcessor\FlexForms\FlexFormsProcessor::supports(Rector\Core\ValueObject\Application\File $file, Rector\Core\ValueObject\Configuration $configuration): bool must be compatible with Rector\Core\Contract\Processor\FileProcessorInterface::supports($file, $configuration): bool in /var/www/html/vendor/ssch/typo3-rector/src/FileProcessor/FlexForms/FlexFormsProcessor.php on line 62
`

Does anyone have a solution?

**Comment by sabbelasichon** [comment]
Are you using rector/rector as a dependency? Do not use ssch/typo3-rector

**Comment by sabbelasichon** [comment]
Sorry, you have to use only rector/rector and not both as a dependency
