### ISSUE TITLE
Update StringUtility to symfony-string instead of Stringy

### ISSUE THREAD

**Issue by samsonasik** [sabbelasichon/typo3-rector#2745]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main             |

## Minimal PHP Code Causing Issue

@sabbelasichon Rector is updating to remove Stringy from its dependency, that means, the StringUtility needs update to use symfony-string as well.

@TomasVotruba the Stringy is used at:

https://github.com/sabbelasichon/typo3-rector/blob/9de803d00a9485cec79bb364e52eb85ab3613e03/src/Helper/StringUtility.php#L7

It needs to be replaced. 

## Expected Behaviour

Keep working with replacement to symfony-string.

**Comment by sabbelasichon** [comment]
@samsonasik I will take care of it.
