### ISSUE TITLE
Incorrect values in FQN : rectorprefixYYYYDDMM

### ISSUE THREAD

**Issue by Oktopuce** [sabbelasichon/typo3-rector#2816]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.12.16             |

Using rector for a migration from TYPO3 V9 to TYPO3 V10 and have incoirrect values in Fully Qualified Name, sample with configurePlugin() : 

Before : 
```
\TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
    'Oktopuce.InoviaInstitutions',
    'List',
    [
        'Institution' => 'list, show, ajaxFilter'
    ],
    // non-cacheable actions
    [
        'Institution' => 'ajaxFilter'
    ]
);
```
After : 
```
\TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
    'Inovirectorprefix20220209aInstitutions',
    'List',
    [
        \Oktopuce\Inovirectorprefix20220209aInstitutions\Controller\InstitutionController::class => 'list, show, ajaxFilter'
    ],
    // non-cacheable actions
    [
        \Oktopuce\Inovirectorprefix20220209aInstitutions\Controller\InstitutionController::class => 'ajaxFilter'
    ]
);

```
## Minimal PHP Code Causing Issue

[https://getrector.org/demo/449f184b-4de8-45d5-9d49-b52e631adbb5](url)

## Expected Behaviour

Prefix 'prefix20220209' should be deleted.

**Comment by sabbelasichon** [comment]
@TomasVotruba This bug is related to the issue https://github.com/rectorphp/rector/issues/7017 here.

**Comment by TomasVotruba** [comment]
It rather looks like these pathes should not be prefixed at all. 
What exact path is this code in?

**Comment by sabbelasichon** [comment]
@TomasVotruba Yes, exactly the prefix Inovirectorprefix20220209aInstitutions is wrong. The culprit is this preg_replace call here: https://github.com/rectorphp/rector/issues/7017. This should not be prefixed / scoped

**Comment by TomasVotruba** [comment]
I see.  I'll check the `scoper.php` to unprefix it

**Comment by TomasVotruba** [comment]
Work in progress https://github.com/rectorphp/rector-src/commit/81152d35e8e4a0dec1f8d5ff69f8cac64354007a

**Comment by TomasVotruba** [comment]
Moved to Rector repository, where bug originates: https://github.com/rectorphp/rector/issues/7017
