### ISSUE TITLE
TYPO3 11 autoload.php

### ISSUE THREAD

**Issue by mkrappitz** [sabbelasichon/typo3-rector#2852]
For the documentation for non composer installation here is an updated autoload.php file for the documentation, that works for me. If you think it's correct I can also make a pull request for the documentation:

```php
<?php
use TYPO3\CMS\Core\Cache\Backend\NullBackend;
use TYPO3\CMS\Core\Cache\Frontend\PhpFrontend;
use TYPO3\CMS\Core\Configuration\ConfigurationManager;
use TYPO3\CMS\Core\Core\Bootstrap;
use TYPO3\CMS\Core\Core\ClassLoadingInformation;
use TYPO3\CMS\Core\Core\SystemEnvironmentBuilder;
use TYPO3\CMS\Core\Package\PackageManager;
use TYPO3\CMS\Core\Package\UnitTestPackageManager;
use TYPO3\CMS\Core\Utility\ExtensionManagementUtility;
use TYPO3\CMS\Core\Utility\GeneralUtility;

define('PATH_site', rtrim(strtr(getcwd(), '\\', '/'), '/').'/');
define('PATH_thisScript', PATH_site.'typo3/index.php');
$_SERVER['SCRIPT_NAME'] = PATH_thisScript;
putenv('TYPO3_PATH_ROOT='.getcwd());
define('TYPO3_MODE', 'BE');
define('TYPO3_PATH_PACKAGES', __DIR__.'/typo3_src/vendor/');

$classLoaderFilepath = TYPO3_PATH_PACKAGES.'autoload.php';

$classLoader = require $classLoaderFilepath;

$requestType = SystemEnvironmentBuilder::REQUESTTYPE_BE | SystemEnvironmentBuilder::REQUESTTYPE_CLI;
SystemEnvironmentBuilder::run(0, $requestType);

Bootstrap::initializeClassLoader($classLoader);
Bootstrap::baseSetup();

// Initialize default TYPO3_CONF_VARS
$configurationManager = new ConfigurationManager();
$GLOBALS['TYPO3_CONF_VARS'] = $configurationManager->getDefaultConfiguration();

$coreCache = Bootstrap::createCache('core');
$cache = Bootstrap::createPackageCache($coreCache);
// Set all packages to active
$packageManager = Bootstrap::createPackageManager(UnitTestPackageManager::class, $cache);

GeneralUtility::setSingletonInstance(PackageManager::class, $packageManager);
ExtensionManagementUtility::setPackageManager($packageManager);

ClassLoadingInformation::dumpClassLoadingInformation();
ClassLoadingInformation::registerClassLoadingInformation();
```

**Comment by sabbelasichon** [comment]
Yes, could you please create a PullRequest for that. Thank you

**Comment by mkrappitz** [comment]
I just saw, this part was already included here, so task ist already done?!
https://github.com/sabbelasichon/typo3-rector/blob/main/docs/installation.md

**Comment by simonschaufi** [comment]
> $coreCache = Bootstrap::createCache('core');
> $cache = Bootstrap::createPackageCache($coreCache);

These lines are differently documented. Could you please verify which of the version is correct?

> $cache = new PhpFrontend('core', new NullBackend('production', []));
> $packageStateCache = new PackageStatesPackageCache(Environment::getLegacyConfigPath() . '/PackageStates.php', $cache);
> // Set all packages to active
> $packageManager = Bootstrap::createPackageManager(UnitTestPackageManager::class, $packageStateCache);

**Comment by mkrappitz** [comment]
I'm pretty sure I took my version of this part from the official typo3 bootstrap code and already successfully worked on some projects with rector based on TYPO3 11 with this code, So I would suppose it is fine.

**Comment by simonschaufi** [comment]
@sabbelasichon why is this closed? His template suggestion is different than the one we have currently

**Comment by sabbelasichon** [comment]
Maybe i was too tired. I have no installation without composer. So i don't know. If it works, we use this. No offense to anybody, but i won't take my time to move this forward.
