### ISSUE TITLE
TYPO3 v12: Remove typoscript option config.disableCharsetHeader

### ISSUE THREAD

**Issue by josefglatz** [sabbelasichon/typo3-rector#2854]
# Feature Request: rector for cleanup removed TypoScript config option "disableCharsetHeader"

https://review.typo3.org/c/Packages/TYPO3.CMS/+/74518

`disableCharsetHeader` within TypoScript `CONFIG` (config) has no functionality anymore

**Comment by sabbelasichon** [comment]
@josefglatz Thanks I am going to close this issue now, because i am importing all the changelogs automatically in a second.
