### ISSUE TITLE
RemoveShowRecordFieldListInsideInterfaceSectionRector.php doesn't delete empty items

### ISSUE THREAD

**Issue by josefglatz** [sabbelasichon/typo3-rector#2855]
showRecordFieldList should also delete something like that TCA:

```php
            'interface' => [
                'showRecordFieldList' => ''
            ],
```

**Comment by sabbelasichon** [comment]
I have provided a test for that. But it seems to work: https://github.com/sabbelasichon/typo3-rector/pull/3211/files
Could you please provide a failing test for that, so i can see what we could do about it. Thanks.
