### ISSUE TITLE
Breaking: #87616 - Removed hook for altering Page Links

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#2856]
Breaking: #87616 - Removed hook for altering Page Links

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/12.0/Breaking-87616-RemovedHookForAlteringPageLinks.html
.. include:: /Includes.rst.txt

=======================================================
Breaking: #87616 - Removed hook for altering Page Links
=======================================================

See :issue:`87616`

Description
===========

The hook :php:`$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['typolinkProcessing']['typolinkModifyParameterForPageLinks']`
has been removed in favor of a new PSR-14 Event :php:`TYPO3\CMS\Frontend\Event\ModifyPageLinkConfigurationEvent`.

The event is called after TYPO3 has already prepared some functionality
within the :php:`PageLinkBuilder`. This therefore allows to modify more
properties, if needed.

Impact
======

Any hook implementation registered is not executed anymore
in TYPO3 v12.0+.

Affected Installations
======================

TYPO3 installations with custom extensions using this hook.

Migration
=========

The hook is removed without deprecation in order to allow extensions
to work with TYPO3 v11 (using the hook) and v12+ (using the new Event)
when implementing the Event as well without any further deprecations.

Use the :doc:`PSR-14 Event <../12.0/Feature-87616-PSR-14EventForModifyingPageLinkGeneration>`
to allow greater influence in the functionality.

.. index:: Frontend, FullyScanned, ext:frontend

**Comment by simonschaufi** [comment]
We could also add a `FIXME` in this case into the `ext_localconf.php` for example

**Comment by sabbelasichon** [comment]
I would say that the Extension Scanner should be used. As it is FullyScanned we should just keep it as it is. Wont fix is fine for me.
