### ISSUE TITLE
Deprecation: #96641 - Link-related functionality in ContentObjectRenderer

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#2934]
Deprecation: #96641 - Link-related functionality in ContentObjectRenderer

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/12.0/Deprecation-96641-LinkRelatedFunctionalityInContentObjectRenderer.html
.. include:: /Includes.rst.txt

=========================================================================
Deprecation: #96641 - Link-related functionality in ContentObjectRenderer
=========================================================================

See :issue:`96641`

Description
===========

Various methods related to shorthand syntax of generating
Links and URLs have been deprecated:

* :php:`ContentObjectRenderer->getATagParams()`
* :php:`ContentObjectRenderer->getTypoLink()`
* :php:`ContentObjectRenderer->getUrlToCurrentLocation()`
* :php:`ContentObjectRenderer->getTypoLink_URL()`

They are related to functionality for generating URLs,
and have been marked as deprecated in favor of the new LinkFactory
API, and the existing :php:`$cObj->typoLink()` and :php:`$cObj->typoLink_URL()`
methods.

Impact
======

Calling these methods in your own PHP code will trigger
a PHP deprecation message.

Affected Installations
======================

TYPO3 installations with custom extensions using these methods for
generating links. The extension scanner in the Upgrade module / Install tool
will show affected occurrences.

Migration
=========

It is recommended to use either existing API calls:

* :php:`ContentObjectRenderer->typoLink()`
* :php:`ContentObjectRenderer->typoLink_URL()`

or the new methods for code that should be compatible with TYPO3 v12+ - only:

* :php:`ContentObjectRenderer->createUrl()`
* :php:`ContentObjectRenderer->createLink()`

or calling the LinkFactory API directly.

.. index:: Frontend, PHP-API, FullyScanned, ext:frontend

**Comment by sabbelasichon** [comment]
Have a look at:

- https://github.com/TYPO3/typo3/blob/12.4/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php#L4605
- https://github.com/TYPO3/typo3/blob/12.4/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php#L4631
- https://github.com/TYPO3/typo3/blob/12.4/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php#L4576 

The method getATagParams cannot be migrated easily.

**Comment by sabbelasichon** [comment]
After having a look at the migration path, this migration cannot be done reliable and easily.

**Comment by simonschaufi** [comment]
I would at least migrate getTypoLink_URL to createUrl
