### ISSUE TITLE
Deprecation: #97384 - TCA option "eval=null" replaced with "nullable"

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#2954]
Deprecation: #97384 - TCA option "eval=null" replaced with "nullable"

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/12.0/Deprecation-97384-TCAOptionNullable.html
.. include:: /Includes.rst.txt

=====================================================================
Deprecation: #97384 - TCA option "eval=null" replaced with "nullable"
=====================================================================

See :issue:`97384`

Description
===========

The TCA option :php:`eval=null` has been replaced with the boolean option
:php:`nullable`.

Impact
======

The TCA option :php:`eval=null` will be automatically migrated to
:php:`'nullable' => true`. The migration will trigger a deprecation level log
entry.

Affected Installations
======================

All installations defining the :php:`null` value in their :php:`eval` list.

Migration
=========

To migrate your TCA add the TCA option :php:`'nullable' => true` and remove the
:php:`null` value from the field's :php:`eval` list.

.. code-block:: php

    // Before

    'columns' => [
       'nullable_column' => [
           'title' => 'A nullable field',
           'config' => [
               'eval' => 'null',
           ],
       ],
    ],

    // After

    'columns' => [
       'nullable_column' => [
           'title' => 'A nullable field',
           'config' => [
               'nullable' => true,
           ],
       ],
    ],

.. index:: TCA, NotScanned, ext:backend

**Comment by simonschaufi** [comment]
I'm on it

**Comment by simonschaufi** [comment]
duplicates #3564
