### ISSUE TITLE
Potential Bug: UseLanguageTypeForLanguageFieldColumnRector

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#2965]
I'm creating a new rule right now and looking for references.
I came across `UseLanguageTypeForLanguageFieldColumnRector`

This line creates the new type:
https://github.com/sabbelasichon/typo3-rector/blob/main/src/Rector/v11/v3/MigrateLanguageFieldToTcaTypeLanguageRector.php#L134
But a side effect is, that everything else is thrown away.
So not only the stuff to migrate, but also configs like size, wizards etc.

As the type is newly introduced it couldn't be that big of a problem, but i want to mention that.
Also since i got some issues with the #2939 i want to prevent to use potential bugs as reference so i want to write that down here just for us to have it

**Comment by helsner** [comment]
State: needs feedback from @sabbelasichon if we want to check or if wer are ok with kicking away all other configs than type => language 

TBH: i would be ok with kicking everything

**Comment by sabbelasichon** [comment]
@helsner  Could you please check what sub array keys should be replaced, so we can identify what should be kept.

**Comment by simonschaufi** [comment]
This is what the core does, we should do the same: https://review.typo3.org/c/Packages/TYPO3.CMS/+/60293/25/typo3/sysext/core/Classes/Migrations/TcaMigration.php#367

**Comment by helsner** [comment]
Ok, then we close this.
I was fine with the solution previously, but wanted to mention it to get feedback and prevent bugs.
With this argument and solution of the core i think our solution is fully acceptable
