### ISSUE TITLE
Rename constants|setup.txt to typoscript

### ISSUE THREAD

**Issue by georgringer** [sabbelasichon/typo3-rector#2977]
# Feature Request

Change the txt files which could be safe to typoscript:

- Configuration/TypoScript/constants.txt
- Configuration/TypoScript/setup.txt

**Comment by sabbelasichon** [comment]
Thank you. My first reaction is that we should avoid bloating Rector with too much responsibilities. But i will think about it more thoroughly

**Comment by sabbelasichon** [comment]
@georgringer Let´s do it. Because this one is important too: https://github.com/sabbelasichon/typo3-rector/issues/2878

**Comment by sabbelasichon** [comment]
Resolved by https://github.com/sabbelasichon/typo3-rector/pull/3065
