### ISSUE TITLE
typo3-generate misconfig

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#3005]
I created a new rule with the command `vendor/bin/rector typo3-generate`
I was asked what type of rector is used which is resolved for the base class.
Now on first run i got the issue, that the namespace imported in the configured_rule.php is not fitting to the class namespace.

Segment in config:
`$rectorConfig->rule(\Ssch\TYPO3Rector\Rector\v12\v0\ReplaceTSFECheckEnableFieldsRector::class);`

actual namespace:
`\Ssch\TYPO3Rector\Rector\v12\v0\typo3\ReplaceTSFECheckEnableFieldsRector`

The namespace fits the folder structur. The test though is again without the folder and the `typo3` in the namespace (kinda seems inconsistent)

**Comment by simonschaufi** [comment]
This has already been fixed with https://github.com/sabbelasichon/typo3-rector/commit/95d7a8343be5d9b1f3a6e11d6e070b93124ec183

**Comment by helsner** [comment]
Simon and me discussed this in Slack
Open:
- the created config files do not have the type included in imports

**Comment by simonschaufi** [comment]
indeed. only partially fixed. Rest will follow
