### ISSUE TITLE
FileIncludeToImportStatementTypoScriptRector does not do anything

### ISSUE THREAD

**Issue by simonschaufi** [sabbelasichon/typo3-rector#3010]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | git source             |

Using the rule `FileIncludeToImportStatementTypoScriptRector` does not have any influence about the code. No changes are applied.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/d725cc9d-e340-4be2-89df-d089ec61fe93

I have also tried it with this config in my own project:

project/
  - demo/
    - index.typoscript
       - content: <INCLUDE_TYPOSCRIPT: source="FILE:lib.typoscript">
    - lib.typoscript

```php
<?php

use Rector\Config\RectorConfig;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->import(__DIR__ . '/config/config.php');

    $rectorConfig->paths([
        __DIR__ . '/demo',
    ]);

    $rectorConfig->fileExtensions(['typoscript']);
    $rectorConfig->rule(\Ssch\TYPO3Rector\FileProcessor\TypoScript\Rector\v9\v0\FileIncludeToImportStatementTypoScriptRector::class);
};
```

## Expected Behaviour

`@import lib.typoscript`

**Comment by nodeadman** [comment]
Since rector/rector version 0.13.1, typoscript rules don't seem to work anymore. Tested with AdditionalHeadersToArrayTypoScriptRector, LibFluidContentToContentElementTypoScriptPostRector and FileIncludeToImportStatementTypoScriptRector rules. In version 0.13.0 these are still recognized correctly and executed if necessary.

**Comment by simonschaufi** [comment]
@TomasVotruba do you have an idea why they don't work anymore? I have the feeling because of file types

**Comment by helsner** [comment]
Hi @TomasVotruba  - someone else reached out in twitter and mentioned issues with JSON-files as well.
I guess there is an overall bug, but i'm not into the topic regarding file types etc.

**Comment by TomasVotruba** [comment]
Hi, I'm not sure what this might be related to. 2 steps could help:

* a reproducer test in pull-request
* exact commit in Rector when this stopped working

**Comment by simonschaufi** [comment]
This is the first commit that breaks: [45eef47f27df7b6ed3422c19db03e0e74fe0417b](https://github.com/rectorphp/rector-src/commit/45eef47f27df7b6ed3422c19db03e0e74fe0417b)

**Comment by sabbelasichon** [comment]
This holds only true when parallel is active. #3017
