### ISSUE TITLE
CommandController rewrite not working

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#3022]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.0           |

Instead of rewriting the CommanController to a SymfonyCommand an error is thrown

```
[ERROR] Could not process "extensions/xxx/Classes/Command/XxxCommandController.php" file, due to: 
         "Analyze error: "Class TYPO3\CMS\Extbase\Mvc\Controller\CommandController not found.". Include your files in   
         "$rectorConfig->autoloadPaths([...]);" or "$rectorConfig->bootstrapFiles([...]);" in "rector.php" config.      
         See https://github.com/rectorphp/rector#configuration". 
```

**Comment by sabbelasichon** [comment]
Did you add the class alias map configuration
https://github.com/sabbelasichon/typo3-rector/blob/main/docs/best_practice_guide.md#classaliasmap

Then it should work.
