### ISSUE TITLE
SubstituteBackendTemplateViewWithModuleTemplateRector does not ignore initializeAction

### ISSUE THREAD

**Issue by simonschaufi** [sabbelasichon/typo3-rector#3039]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.0     |

## Minimal PHP Code Causing Issue

Original:

```php
    public function initializeAction()
    {
        // some code
    }
```

Actual output:

```php
    public function initializeAction(): \Psr\Http\Message\ResponseInterface
    {
        $moduleTemplate = $this->moduleTemplateFactory->create($this->request);
        // some code
        $moduleTemplate->setContent($this->view->render());
        return $this->htmlResponse($moduleTemplate->renderContent());
    }
```

## Expected Behaviour

initializeAction is a special action which doesn't need to return a response but just initializes an actual action. Same goes for 
"initializeIndexAction". Don't touch these methods!

**Comment by helsner** [comment]
I'm a little bit irritated.
Shouldn't that be task of the `ForwardResponseInsteadOfForwardMethodRector` ?

**Comment by simonschaufi** [comment]
Well, I ran every v11 rule individually and this rule messed it up.

**Comment by helsner** [comment]
Yep, can confirm

**Comment by simonschaufi** [comment]
So basically there should be a check if the method starts with "initialize" and skip.

**Comment by helsner** [comment]
will add yeah
