### ISSUE TITLE
Overall bug issue

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#3055]
overall issue for latest main in action

- `bin/rector init --template-type=typo3` does not create the right file

**Comment by sabbelasichon** [comment]
Yeah. The feature was removed by rector core https://github.com/rectorphp/rector-src/commit/83f7e9f3ab88c45ed8e4672ac2e2616bbdc5d722

**Comment by helsner** [comment]
Then we gotta do something about the docs and creation of the file, as this is currently not fitting

**Comment by helsner** [comment]
I did not have the latest state locally, so my push was unnecessary.. i reverted it.
Looking all good now.
