### ISSUE TITLE
The command typo3-extensions does not work anymore

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#3062]
Custom commands are not registered anymore for the rector binary. I.e. the AddComposerTypo3ExtensionsToConfigCommand is not working anymore in our standalone version. Make it work again

**Comment by sabbelasichon** [comment]
Currently it is not possible to generate the composer configuration files automatically anymore. 
We should decide if we can drop it completely, because nobody is using it or if we would like to keep them and add packages manually.

**Comment by simonschaufi** [comment]
I would find it really helpful to know which extension is compatible with which TYPO3 version and then update the dependency accordingly. It's so time consuming to go through every extension and check for the latest version

**Comment by sabbelasichon** [comment]
Me too.

**Comment by sabbelasichon** [comment]
Sorry, but this is gone due to removals in rector itself. No composer upgrades anymore.
