### ISSUE TITLE
Replace FlashMessage::ERROR and friends with AbstractMessage::ERROR

### ISSUE THREAD

**Issue by simonschaufi** [sabbelasichon/typo3-rector#3069]
# Feature Request

Instead of using the flash messages constants from `TYPO3\CMS\Core\Messaging\FlashMessage` use `TYPO3\CMS\Core\Messaging\AbstractMessage`

The TYPO3 core is using:

```php
new FlashMessage(
        '',
        'Message',
        FlashMessage::WARNING
);
```

throughout the core but the constant is actually in the AbstractMessage which phpstorm suggests to use instead.

**Comment by sabbelasichon** [comment]
This can be achieved by using a configurable rector: https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#renameclassconstfetchrector

**Comment by sabbelasichon** [comment]
@simonschaufi Could you tell me if this is valid for every TYPO3 Version, so we can add it for the least supported TYPO3 config.

**Comment by simonschaufi** [comment]
I already added label 7 so yes, it's true for all versions

**Comment by sabbelasichon** [comment]
Resolved by https://github.com/sabbelasichon/typo3-rector/pull/3074
