### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by grischpel** [sabbelasichon/typo3-rector#3075]
#Please update docu, because its not working as described here

**Comment by sabbelasichon** [comment]
Could you add more details?

**Comment by helsner** [comment]
it is important to differ between master and previous versions as we are undergoing a big rewrite affecting the setup.
We are in a pre release state, which means the docs are now changed as much to fit the new upcoming release, which means it is not working like that in the current public setup

**Comment by helsner** [comment]
I allow myself to close this without further description and the mentioned state of the project
