### ISSUE TITLE
Wrong migration for Forward and Redirect in the end of a controller action

### ISSUE THREAD

**Issue by tdeuling** [sabbelasichon/typo3-rector#3084]
Rule set: TYPO3 11
Rule: Ssch\TYPO3Rector\Rector\v11\v0\ForwardResponseInsteadOfForwardMethodRector

When using a Redirect or a Forward in the end of a controller action named `somethingAction(): ForwardResponse` like:
```php
        return (new ForwardResponse('show'))
            ->withControllerName('Bonus')
            ->withExtensionName('Bonus')
            ->withArguments(['bonus' => $bonus]);
```
…the rule generates:
```php
        return $this->htmlResponse((new ForwardResponse('show'))
            ->withControllerName('Bonus')
            ->withExtensionName('Bonus')
            ->withArguments(['bonus' => $bonus]));
```
..that's not the expected behaviour. It should not be migrated like this.

**Comment by sabbelasichon** [comment]
@tdeuling Could you provide a failing test for this. I couldn´t reproduce the error.
