### ISSUE TITLE
Multiple services of type PhpParser\NodeFinder found

### ISSUE THREAD

**Issue by tomasnorre** [sabbelasichon/typo3-rector#3204]
# Bug Report

Thank you for providing this awesome tool, helps me a lot. :heart:

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.0            |

After replacing the origin rector github.com/rectorphp/rector/ with the typo3-rector to get the newest `TYPO3SetLists`, I'm getting the error when running vendor/bin/rector 

```
PHP Fatal error:  Uncaught _PHPStan_9a6ded56a\Nette\DI\ServiceCreationException: Multiple services of type PhpParser\NodeFinder found: 0311, 0326 in phar:///home/tomas/Projects/crawler/.devbox/public/typo3conf/ext/crawler/.Build/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Autowiring.php:53
```

Get similar error with PHPStan (v. 1.9.0) 

``` 
Service of type Symplify\Astral\Reflection\ReflectionParser: Multiple services of type PhpParser\NodeFinder found: 0379, 0394 (required by $nodeFinder in ReflectionParser::__construct())     
```

## Expected Behaviour

I would expect not to have this loaded double, the question is where it's coming from, but not sure yet.

It's as of this PR that the problems appears in the TYPO3 Crawler
https://github.com/tomasnorre/crawler/pull/971

I would be happy to help fix the problem as it's get identified, can also simply be a problem in my setup.

**Comment by sabbelasichon** [comment]
@tomasnorre Thanks for your kind words. Could you update to the latest version and see if the error disappears.

**Comment by tomasnorre** [comment]
Thanks, that solved it.
