### ISSUE TITLE
Cannot autowire service: $filesFinder 

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#3229]
v1.0.6
```
 [ERROR] Cannot autowire service                                                                                
         "Ssch\TYPO3Rector\Rector\General\ConvertImplicitVariablesToExplicitGlobalsRector": argument            
         "$filesFinder" of method "__construct()" references class "Ssch\TYPO3Rector\Helper\FilesFinder" but no 
         such service exists.       

```

Config:
No Setlist, only the following from default config:
`$rectorConfig->rule(ConvertImplicitVariablesToExplicitGlobalsRector::class);`

Otherwiese:
i defined `\Rector\Doctrine\Set\DoctrineSetList::DOCTRINE_DBAL_211,` as Setlist.
then the issue happens as well.

What it solved: adding the  `Typo3LevelSetList::UP_TO_TYPO3_11,` makes it work..

**Comment by sabbelasichon** [comment]
@helsner If you only use one rule you have to additionally import the config from TYPO3-Rector via import manually.

**Comment by sabbelasichon** [comment]
@helsner The only way to get around this issues is to load the config file from TYPO3 Rector inside your configuration file. Like so

```php
$rectorConfig->import(__DIR__ . '/vendor/ssch/typo3-rector/config/config.php');
```
