### ISSUE TITLE
Breaking: #98487 - $GLOBALS['PAGES_TYPES'] removed

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#3254]
Breaking: #98487 - $GLOBALS['PAGES_TYPES'] removed

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/12.0/Breaking-98487-GLOBALSPAGES_TYPESRemoved.html
.. include:: /Includes.rst.txt

.. _breaking-98487-1664575125:

==================================================
Breaking: #98487 - $GLOBALS['PAGES_TYPES'] removed
==================================================

See :issue:`98487`

Description
===========

The global array :php:`PAGES_TYPES` has been removed in favor of a new registry
class containing the shared state.

Impact
======

Accessing or modifying :php:`$GLOBALS['PAGES_TYPES']` will have no effect anymore.

Affected installations
======================

TYPO3 installations with custom extensions creating custom TCA records or custom
Page Doktypes.

Migration
=========

Use the new PageTypeRegistry class to register custom page types with their
dependency what kind of records should be allowed for creation, or to read the
information what record types are allowed on a specific pages.doktype.

.. index:: PHP-API, FullyScanned, ext:core

**Comment by helsner** [comment]
Should be solvable via comment:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/75188/13#message-bffff4f6a10b430292386221d7c96387b82e2dec

```
$pageDoktypeRegistry = GeneralUtility::makeInstance(PageDoktypeRegistry);
$pageDoktypeRegistry->add(116, [
'type' => 'web',
'allowedTables' => '*',
]);
```

**Comment by sabbelasichon** [comment]
Resolved by https://github.com/sabbelasichon/typo3-rector/pull/4055
