### ISSUE TITLE
Feature: #96041 - Improve Backend toolbar registration

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#3334]
Feature: #96041 - Improve Backend toolbar registration

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/12.0/Feature-96041-ImproveBackendToolbarRegistration.html
.. include:: /Includes.rst.txt

.. _feature-96041:

======================================================
Feature: #96041 - Improve Backend toolbar registration
======================================================

See :issue:`96041`

Description
===========

The toolbar in the TYPO3 backend is well known by users as it provides
e.g. the personal bookmarks or a common used feature for administrators:
the "flush caches" action.

It's also possible for extension authors to add their own
toolbar items. The registration therefore had to be done in the
:file:`LocalConfiguration.php` file.

Since the introduction of the Symfony service container in TYPO3 v10,
it's possible to autoconfigure services. This feature is now also used
for the toolbar items. Therefore, the previous registration step is
now superfluous. All toolbar items are now automatically tagged and
registered based on the implemented :php:`TYPO3\CMS\Backend\Toolbar\ToolbarItemInterface`.

Impact
======

Custom toolbar items are now automatically registered, based on
the implemented interface, through the service configuration.

.. index:: Backend, PHP-API, ext:backend

**Comment by helsner** [comment]
Should be doable by checking assignments for `$GLOBALS['TYPO3_CONF_VARS']['BE']['toolbarItems']...`

**Comment by sabbelasichon** [comment]
@helsner I would refrain in doing this, because not many people are doing it anyways and the LocalConfiguration.php is most of the time out of scope.
