### ISSUE TITLE
Feature: #96614 - Automatic inclusion of page TSconfig of extensions

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#3342]
Feature: #96614 - Automatic inclusion of page TSconfig of extensions

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/12.0/Feature-96614-AutomaticInclusionOfPageTsConfigOfExtensions.html
.. include:: /Includes.rst.txt

.. _feature-96614:

====================================================================
Feature: #96614 - Automatic inclusion of page TSconfig of extensions
====================================================================

See :issue:`96614`

Description
===========

Extension authors can now put a file named
:file:`Configuration/page.tsconfig` in their extension folder.

This file is then recognized to load the contents as global page TSconfig
for the whole TYPO3 installation during build-time. This is much
more performant than the existing solution to use
:php:`ExtensionManagementUtility::addPageTSConfig()` in
:file:`ext_localconf.php`, which is added to
:php:`$TYPO3_CONF_VARS[SYS][defaultPageTSconfig]` during runtime.

Impact
======

When a file is created, the page TSconfig is loaded automatically without a
custom registration anymore, and cached within the Core caches, and more
performant than the existing registration format.

.. index:: TSConfig, ext:core

**Comment by helsner** [comment]
We could move the content of the `addPageTSConfig` call into the newly created page.tsconfig file and remove the original call
