### ISSUE TITLE
Feature: #97035 - Utilize "required" directly in TCA field configuration

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#3363]
Feature: #97035 - Utilize "required" directly in TCA field configuration

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/12.0/Feature-97035-UtilizeRequiredDirectlyInTCAFieldConfiguration.html
.. include:: /Includes.rst.txt

.. _feature-97035:

========================================================================
Feature: #97035 - Utilize "required" directly in TCA field configuration
========================================================================

See :issue:`97035`

Description
===========

Since :issue:`67354`, the FormEngine may use :php:`required` with a bool value
in a TCA field configuration, enabling the same functionality as the `required`
option within `eval`.

All TCA in TYPO3 Core is migrated to use the `required` configuration over the
corresponding `eval` option.

Impact
======

If not done already, TCA is automatically migrated to use :php:`'required' => true`
instead of the co-existing `eval` option. The automated migration will trigger
a deprecation entry though.

Example
=======

..  code-block:: php

    'columns' => [
        'some_column' => [
            'title' => 'foo',
            'config' => [
                'required' => true,
                'eval' => 'trim',
            ],
        ],
    ],

.. index:: Backend, TCA, ext:core

**Comment by helsner** [comment]
this is also already done - MigrateRequiredFlagRector
