### ISSUE TITLE
Add removal for TCA property`table_local` in TYPO3 v12

### ISSUE THREAD

**Issue by ohader** [sabbelasichon/typo3-rector#3414]
# Feature Request

* database file `sys_file_reference.table_local` has been removed
* it still might occur in TCA `foreign_match_fields` - e.g. see https://forge.typo3.org/issues/100897
* https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98479-RemovedFileReferenceRelatedFunctionality.html
* thus, in TYPO3 v12 this has to be removed from the TCA declarations, to avoid SQL selection errors during runtime

## Diff

```diff
                     'foreign_match_fields' => [
                         'fieldname' => 'media',
                         'tablenames' => 'tx_site_domain_model_mediacollection',
-                        'table_local' => 'sys_file',
                     ],
                     'maxitems' => 1,
                     'minitems' => 1,
```

**Comment by sabbelasichon** [comment]
Thanks a lot. I am gonna provide a rule for that.
