### ISSUE TITLE
BUG: Uncaught TypeError: Ssch\TYPO3Rector\Helper\OldSeverityToLogLevelMapper::mapSeverityToLogLevel

### ISSUE THREAD

**Issue by spoonerWeb** [sabbelasichon/typo3-rector#3417]
## Problem

Doing an upgrade of project extensions from v7 to v11, I got this error:
```
PHP Fatal error: Uncaught TypeError: Ssch\TYPO3Rector\Helper\OldSeverityToLogLevelMapper::mapSeverityToLogLevel()
```
Issue is a method with `int` needed, but `string` given. 
File: src/Rector/v9/v0/SubstituteGeneralUtilityDevLogRector.php:70

**Comment by sabbelasichon** [comment]
Yes, this could be the case in the ancient times. I have fixed it.
