### ISSUE TITLE
Rector fatal error with TCA `tt_address` with UP_TO_TYPO3_12 rule

### ISSUE THREAD

**Issue by mehdichaouch** [sabbelasichon/typo3-rector#3440]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.11.7 |

Hello team,

For an upgrade to TYPO3 v12 I get this error:

```
 0/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%PHP Fatal error:  Uncaught TypeError: Ssch\TYPO3Rector\Helper\StringUtility::inList(): Argument #1 ($list) must be of type string, null given, called in /var/www/html/vendor/ssch/typo3-rector/src/Rector/v12/v0/tca/MigrateRequiredFlagRector.php on line 79 and defined in /var/www/html/vendor/ssch/typo3-rector/src/Helper/StringUtility.php:37
Stack trace:
#0 /var/www/html/vendor/ssch/typo3-rector/src/Rector/v12/v0/tca/MigrateRequiredFlagRector.php(79): Ssch\TYPO3Rector\Helper\StringUtility::inList(NULL, 'required')
#1 /var/www/html/vendor/ssch/typo3-rector/src/Rector/Tca/AbstractTcaRector.php(125): Ssch\TYPO3Rector\Rector\v12\v0\tca\MigrateRequiredFlagRector->refactorColumn(Object(PhpParser\Node\Scalar\String_), Object(PhpParser\Node\Expr\Array_))
#2 /var/www/html/vendor/ssch/typo3-rector/src/Rector/Tca/AbstractTcaRector.php(66): Ssch\TYPO3Rector\Rector\Tca\AbstractTcaRector->refactorColumnList(Object(PhpParser\Node\Expr\Array_))
#3 /var/www/html/vendor/rector/rector/src/Rector/AbstractRector.php(234): Ssch\TYPO3Rector\Rector\Tca\AbstractTcaRector->refactor(Object(PhpParser\Node\Expr\Array_))
```

This stop all the Rector process, and don't allow me to run fully rule `Typo3LevelSetList::UP_TO_TYPO3_12` (the only one setted for test).

## Minimal PHP Code Causing Issue

Code that generate this issue is in my overide module `custom_address` of `tt_address`, in `./packages/custom_address/Configuration/TCA/tx_customaddress_domain_model_region.php`.
I localized code that generate issue, it's the lines ```'eval' => 'null,' . \FriendsOfTYPO3\TtAddress\Evaluation\LatitudeEvaluation::class,```

with almost same context as here:
- https://github.com/FriendsOfTYPO3/tt_address/blob/master/Configuration/TCA/tt_address.php#L644
- https://github.com/FriendsOfTYPO3/tt_address/blob/master/Configuration/TCA/tt_address.php#L656

By removing those lines ```'eval' => \FriendsOfTYPO3\TtAddress\Evaluation\LatitudeEvaluation::class,``` Rector finish to fix files.

I don't understand what's wrong in my case.

Thanks for helping.

## Expected Behaviour

Having Rector work as expected with rule `UP_TO_TYPO3_12`.

Thanks

**Comment by sabbelasichon** [comment]
@mehdichaouch Could you check with the latest release 1.3.5

**Comment by sabbelasichon** [comment]
No feedback given. It should be fixed in the new version
