### ISSUE TITLE
Nimu Testing Framework migration 

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#3444]
The Nimu Testing Framework (by Nicole Cordes and Helmut Hummel) is deprecated
We could think about some basic migration stuff to the core testing framework

**Comment by sabbelasichon** [comment]
@helsner Have a look at: https://github.com/sabbelasichon/typo3-rector/blob/main/config/nimut-testingframework/nimut-testing-framework-to-typo3-testing-framework.php

Something already exists for that.

**Comment by helsner** [comment]
Thanks a lot
Was in the car on the road to the DevDays
Will check out the next days!
