### ISSUE TITLE
Add `extensionName` to view helpers due to Breaking: #98377

### ISSUE THREAD

**Issue by denislorch** [sabbelasichon/typo3-rector#3459]
The `FLUIDTEMPLATE` setting `extbase.controllerExtensionName` does not work under TYPO3 v12 due to https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98377-FluidStandaloneViewDoesNotCreateAnExtbaseRequestAnymore.html.

The documentation https://docs.typo3.org/m/typo3/reference-typoscript/12.4/en-us/ContentObjects/Fluidtemplate/Index.html#extbase-controllerextensionname is outdated.

**Migration suggestion**
Add the `extensionName` parameter to `f:translate` and `f:uri.resource` view helper.

**Comment by sabbelasichon** [comment]
@denislorch How can that be reliable done? I see no way in doing this. Feel free to reopen and and add a PR
