### ISSUE TITLE
Breaking: #101471 - Introduce type declarations in AbstractDriver

### ISSUE THREAD

**Issue by simonschaufi** [sabbelasichon/typo3-rector#3669]
Breaking: #101471 - Introduce type declarations in AbstractDriver

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.0/Breaking-101471-IntroduceTypeDeclarationsInAbstractDriver.html
.. include:: /Includes.rst.txt

.. _breaking-101471-1690531810:

=================================================================
Breaking: #101471 - Introduce type declarations in AbstractDriver
=================================================================

See :issue:`101471`

Description
===========

Return and param type declarations have been introduced for all methods and method
stubs of of :php:`\TYPO3\CMS\Core\Resource\Driver\AbstractDriver` and
:php:`\TYPO3\CMS\Core\Resource\Driver\AbstractHierarchicalFilesystemDriver`

Impact
======

In consequence, all classes, extending any of those abstract classes and overriding
any of those affected methods need to reflect those changes and add the same return
and param type declarations.

Affected methods are:

- :php:`\TYPO3\CMS\Core\Resource\Driver\AbstractDriver::isValidFilename()`
- :php:`\TYPO3\CMS\Core\Resource\Driver\AbstractDriver::getTemporaryPathForFile()`
- :php:`\TYPO3\CMS\Core\Resource\Driver\AbstractDriver::canonicalizeAndCheckFilePath()`
- :php:`\TYPO3\CMS\Core\Resource\Driver\AbstractDriver::canonicalizeAndCheckFileIdentifier()`
- :php:`\TYPO3\CMS\Core\Resource\Driver\AbstractDriver::canonicalizeAndCheckFolderIdentifier()`

- :php:`\TYPO3\CMS\Core\Resource\Driver\AbstractHierarchicalFilesystemDriver::isPathValid()`
- :php:`\TYPO3\CMS\Core\Resource\Driver\AbstractHierarchicalFilesystemDriver::canonicalizeAndCheckFilePath()`
- :php:`\TYPO3\CMS\Core\Resource\Driver\AbstractHierarchicalFilesystemDriver::canonicalizeAndCheckFileIdentifier()`
- :php:`\TYPO3\CMS\Core\Resource\Driver\AbstractHierarchicalFilesystemDriver::canonicalizeAndCheckFolderIdentifier()`

Affected installations
======================

Installations that extend any of those abstract classes might be affected.

Migration
=========

Add the same param and return type declarations the interface does.

.. index:: FAL, PHP-API, NotScanned, ext:core

**Comment by sabbelasichon** [comment]
Have a look at https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#addreturntypedeclarationbasedonparentclassmethodrector

**Comment by sabbelasichon** [comment]
Feel free to reopen, if you see a need. But i guess it is very unlikely that someone is extending these classes in the wild
