### ISSUE TITLE
Deprecation: #91806 - BackendUtility viewOnClick

### ISSUE THREAD

**Issue by simonschaufi** [sabbelasichon/typo3-rector#3773]
Deprecation: #91806 - BackendUtility viewOnClick

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.3/Deprecation-91806-BackendUtilityViewOnClick.html
.. include:: /Includes.rst.txt

.. _deprecation-91806:

================================================
Deprecation: #91806 - BackendUtility viewOnClick
================================================

See :issue:`91806`

Description
===========

Method :php:`BackendUtility::viewOnClick()` is discouraged to be used
due to its inline JavaScript and has been deprecated now.

Impact
======

Using the method will trigger a PHP :php:`E_USER_DEPRECATED` error.

Affected Installations
======================

Extensions calling this static method will be affected. The extension
scanner will find usages as strong match.

Migration
=========

The :php:`\TYPO3\CMS\Backend\Routing\PreviewUriBuilder` should be used
instead as described in
:doc:`/Changelog/11.0/Important-91123-AvoidUsingBackendUtilityViewOnClick`.

.. index:: Backend, JavaScript, PHP-API, FullyScanned, ext:backend

**Comment by sabbelasichon** [comment]
https://github.com/TYPO3-CMS/backend/blob/11.5/Classes/Utility/BackendUtility.php#L2082

**Comment by sabbelasichon** [comment]
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.0/Important-91123-AvoidUsingBackendUtilityViewOnClick.html
