### ISSUE TITLE
max property is being removed for every type input

### ISSUE THREAD

**Issue by wtfred** [sabbelasichon/typo3-rector#3925]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.17.0             |

## Minimal PHP Code Causing Issue

```
'config' => [
    'type' => 'input',
    'max' => 255,
],
```

## Expected Behaviour

Normal input fields should be allowed to define a max property, right?
I think "MigrateToEmailTypeRector" is used for this, and it shouldn't.

**Comment by simonschaufi** [comment]
Thank you for your report. I have fixed it.
