### ISSUE TITLE
Form Framework - EmailToReceiver Finisher

### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#3926]
When the EmailToReceiver Finisher is used in PHP Userland-Code we should migrate the old Syntax recipientAddress and recipientName to the new Array Syntax recipients

Old Code
```php
'recipientAddress' => 'info@max.com',
'recipientName' => 'Mustermann',
```

New Code
```php
'recipients' => ['info@max.com' => 'Mustermann'],
```

**Comment by simonschaufi** [comment]
Do you have a change from the core for that?

**Comment by sabbelasichon** [comment]
@simonschaufi https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Feature-80420-AllowMultipleRecipientsInEmailFinisher.html

But i think it is not worth it.
