### ISSUE TITLE
Allow newer phpstan versions

### ISSUE THREAD

**Issue by kevin-appelt** [sabbelasichon/typo3-rector#3930]
Currently the up to date versions of phpstan are marked as conflict.

https://github.com/sabbelasichon/typo3-rector/blob/988df0f47098ae8c8046448049a4ae30233764e6/composer.json#L107

The conflict was introduced with https://github.com/sabbelasichon/typo3-rector/pull/3454

Are there any updates if up to date versions of phpstan will be allowed again some time soon? :)

**Comment by simonschaufi** [comment]
nah our tests break. Could you have a look at them and make them work in my PR? That would be an awesome contribution!

**Comment by sabbelasichon** [comment]
@simonschaufi With typo3-rector version 2.x this will be the case. I am going to close it for now.
