### ISSUE TITLE
Breaking: #102624 - PSR-14 Event for modifying image source collection

### ISSUE THREAD

**Issue by simonschaufi** [sabbelasichon/typo3-rector#3960]
Breaking: #102624 - PSR-14 Event for modifying image source collection

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.0/Breaking-102624-RemovedHookForManipulatingImageSourceCollection.html

---
title: "Breaking: #102624 - PSR-14 Event for modifying image source
  collection"
---

See [102624](https://forge.typo3.org/issues/102624)

# Description

The hook
`$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_content.php']['getImageSourceCollection']`
has been removed in favor of the new PSR-14
`\TYPO3\CMS\Frontend\ContentObject\Event\ModifyImageSourceCollectionEvent`.

# Impact

Any hook implementation registered is not executed anymore in TYPO3
v13.0+.

# Affected installations

TYPO3 installations with custom extensions using this hook.

# Migration

The hook is removed without deprecation in order to allow extensions to
work with TYPO3 v12 (using the hook) and v13+ (using the new Event) when
implementing the Event as well without any further deprecations. Use the
`PSR-14 Event <../13.0/Feature-102624-PSR-14EventForModifyingImageSourceCollection>`
to allow greater influence in the functionality.

<div class="index">

Frontend, PHP-API, FullyScanned, ext:frontend

</div>

**Comment by sabbelasichon** [comment]
@simonschaufi Those PSR-14 Events are not safe to migrate. I would close all related issues. Feel free to do so.
