### ISSUE TITLE
Deprecation: #102631 - Deprecated Controller attribute for auto configuring backend controllers

### ISSUE THREAD

**Issue by simonschaufi** [sabbelasichon/typo3-rector#3971]
Deprecation: #102631 - Deprecated Controller attribute for auto configuring backend controllers

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.0/Deprecation-102631-DeprecatedControllerAttributeForAutoConfiguringBackendControllers.html

---
title: "Deprecation: #102631 - Deprecated Controller attribute for auto
  configuring backend controllers"
---

See [102631](https://forge.typo3.org/issues/102631)

# Description

In order to unify PHP attribute naming, the former
`introduced <feature-99055-1668096727>`
`\TYPO3\CMS\Backend\Attribute\Controller` attribute has been deprecated
and is replaced by the `new <feature-102631-1702031335>`
`\TYPO3\CMS\Backend\Attribute\AsController` attribute.

# Impact

The attribute has changed from `\TYPO3\CMS\Backend\Attribute\Controller`
to `\TYPO3\CMS\Backend\Attribute\AsController` and the old name has been
deprecated.

# Affected installations

All installations using the deprecated attribute
`\TYPO3\CMS\Backend\Attribute\Controller`. The extension scanner will
report usages.

# Migration

Replace usages with the new attribute
`\TYPO3\CMS\Backend\Attribute\AsController` in custom extension code.

<div class="index">

Backend, PHP-API, FullyScanned, ext:backend

</div>

**Comment by sabbelasichon** [comment]
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/BackendModule/CreateModule.html
