### ISSUE TITLE
ExtbaseControllerActionsMustReturnResponseInterfaceRector is incorrectly applied

### ISSUE THREAD

**Issue by saschanowak** [sabbelasichon/typo3-rector#3981]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.17.0 (invoke `vendor/bin/rector --version`)             |

The Rule `ExtbaseControllerActionsMustReturnResponseInterfaceRector` detects only `ResponseInterface` as return type. Given you have a return type of a class that implements `ResponseInterface` then the rule is applied.

## Minimal PHP Code Causing Issue
```php
<?php

declare(strict_types=1);

namespace Demo\Demo\Controller;

use TYPO3\CMS\Extbase\Mvc\Controller\ActionController;

class DemoController extends ActionController
{
    public function someAction(): ResponseInterface
    {
        $result = $this->repository->findAll();

        return match (strtolower($this->request->getFormat())) {
            'csv' => CsvResponse::fromArray($result),
            default => JsonResponse::fromArray($result)
        };
    }
}
```

```php
<?php

final class JsonResponse extends \TYPO3\CMS\Core\Http\JsonResponse
{
    public static function fromArray(array $payload): self
    {
        return new self(data: $payload, status: 200, headers: [
            'Content-Type' => 'application/json',
        ]);
    }
}
```

when I change my code to 

```php
<?php

final class JsonResponse extends \TYPO3\CMS\Core\Http\JsonResponse
{
    public static function fromArray(array $payload): ResponseInterface
    {
        return new self(data: $payload, status: 200, headers: [
            'Content-Type' => 'application/json',
        ]);
    }
}
```

the rule is not applied anymore.

## Expected Behaviour

The rector rule should allow return type of classes that implements `ResponseInterface`

**Comment by simonschaufi** [comment]
ok, that is a tricky one. Good to know that people also use other variants of return types.

**Comment by saschanowak** [comment]
@sabbelasichon thanks 👍
