### ISSUE TITLE
Keep code-style of TypoScript

### ISSUE THREAD

**Issue by julianhofmann** [sabbelasichon/typo3-rector#3997]
# Feature Request

TYPO3-rector should not change the code style of TypoScript - or handle it in a more configurable way.

As a team, we decide what the formatting of shared TypoScript code should look like. Tools such as `helmich/typo3-typoscript-lint` and appropriate configuration are used to ensure compliance with the coding guidelines.

Unfortunately, TYPO3-rector internally uses the PrettyPrinter when applying TypoScript rectors and sets (mostly fixed) coding styles.

**Comment by sabbelasichon** [comment]
@julianhofmann Tbh. Keeping existing code style is really difficult to achieve. Same applies for PHP itself. That´s the reason why tools like php-cs-fixer exist. 

But feel free to open a Merge Request for all relevant settings which should be configurable.

**Comment by julianhofmann** [comment]
I am aware of the difficulty. That's why the issue is formulated relatively openly.

If I have seen this correctly, it is unfortunately not possible to simply adopt the configuration of `helmich/typo3-typoscript-lint`. That would be the best solution here IMO.

What is unclear to me, is why rector reformats via PrettyPrinter at all? 
In my opinion, this is a half-baked solution: a bit of formatting, but then not going into depth due to the possible variety of formatting. 
Why not leave the formatting completely to the other available tools?

As I said, I understand the difficulty (and I have great respect for all contributors. Thank you very much!). However, a solution (or MR) requires some understanding of decisions and backgrounds.

---
Our workaround is to remove the TypoScriptFileProcessor depending on the context in rector configuration: 
```
if (($_ENV['TYPO3_CONTEXT'] ?? '') !== 'Development') {
    $rectorConfig->services()->remove(TypoScriptFileProcessor::class);
}
```

**Comment by sabbelasichon** [comment]
@julianhofmann I have added in this PR https://github.com/sabbelasichon/typo3-rector/pull/4038 all possible options to configure the PrettyPrinter. Would this somehow solve your formatting issues as well?
Keeping all formatting is impossible now for us. Feel free to add all possible formatting options from helmich/typo3-typoscript-lint. I am not against it and there are no reasons whatsoever.
