### ISSUE TITLE
Add compatibility with vanta/gitlab-rector

### ISSUE THREAD

**Issue by moritz-ngo** [sabbelasichon/typo3-rector#4018]
# Feature Request

It would be nice, if Rector for TYPO3 would be compatible with [`vanta/gitlab-rector`](https://github.com/VantaFinance/GitlabRector), to provide simple output when using in GitLab CI Pipelines

**Comment by simonschaufi** [comment]
@moritz-ngo Can you please specify what you mean by "compatible"?

Would you also be able to sponsor this feature as this is a very specific customer request?

**Comment by sabbelasichon** [comment]
@moritz-ngo As far as i read it, the version <= 0.2.2 should be compatible already. 
Just run composer require --dev vanta/gitlab-rector:^0.2.2 -W

**Comment by moritz-ngo** [comment]
@sabbelasichon sorry my bad… I haven't looked properly and used an old `ssch/typo3-rector` version. 🤦🏼  
The funny thing is that it won't got updated automatically with `composer update -W`, I had to manually update the version constraint…

Anyway thanks for having a look into this nonetheless :)
