### ISSUE TITLE
Upgrade to `nikic/php-parser` V5

### ISSUE THREAD

**Issue by oliverklee** [sabbelasichon/typo3-rector#4045]
The recently-released `nikic/php-parser` V5 has some breaking changes over V4: https://github.com/nikic/PHP-Parser/releases/tag/v5.0.0

Upgrading probably is not urgent, but at I think at some time upgrading would be helpful to make use of the performance improvements in V5, and to allow us to update to future bugfix releases.

**Comment by simonschaufi** [comment]
See https://github.com/sabbelasichon/typo3-rector/pull/4048

**Comment by sabbelasichon** [comment]
Thanks. Looks promising. But we are restricted by rector itself. So i am going to close it for now, but actively following development.
