### ISSUE TITLE
Scope not available on "PhpParser\Node\Expr\ArrayDimFetch" node with parent node of "PhpParser\Node\Expr\ArrayDimFetch"

### ISSUE THREAD

**Issue by moritz-ngo** [sabbelasichon/typo3-rector#4049]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.0 |
| ssch/typo3-rector version | 1.7.1 |

After upgrading `ssch/typo3-rector` to v1.7.1, I get the following error message when running rector:
```
In AbstractScopeAwareRector.php line 53:

  Scope not available on "PhpParser\Node\Expr\ArrayDimFetch" node with parent node of "PhpParser\Node\Expr\ArrayDimFetch", but is required by a refactorWithScope() method of "Ssch\TYPO3Rector\Rector\v9\v0\UseExtensionConfigurationApiRector" rule. Fix scope refresh on changed nodes first
```

## Expected Behaviour

The exception should not be thrown. 

Or do I need to update something in my `rector.php`?

**Comment by Patta** [comment]
can confirm this issue.

**Comment by saschanowak** [comment]
Same here. If this helps to debug:
{code}
[file] extensions/.../Configuration/TCA/Overrides/fe_groups.php
[rule] Ssch\TYPO3Rector\Rector\v9\v0\UseExtensionConfigurationApiRector

In AbstractScopeAwareRector.php line 53:

  [Rector\Core\Exception\ShouldNotHappenException]
  Scope not available on "PhpParser\Node\Expr\ArrayDimFetch" node with parent node of "PhpParser\Node\Expr\ArrayDimFetch", but is required by a refactorWithScope() method of "Ssch\TYPO3Rector\Rector\v9\v0\UseExtensionCon
  figurationApiRector" rule. Fix scope refresh on changed nodes first

Exception trace:
  at vendor/rector/rector/src/Rector/AbstractScopeAwareRector.php:53
 Rector\Core\Rector\AbstractScopeAwareRector->refactor() at vendor/rector/rector/src/Rector/AbstractRector.php:234
 Rector\Core\Rector\AbstractRector->enterNode() at vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:113
 PhpParser\NodeTraverser->traverseNode() at vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:133
 PhpParser\NodeTraverser->traverseNode() at vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:133
 PhpParser\NodeTraverser->traverseNode() at vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:133
 PhpParser\NodeTraverser->traverseNode() at vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:196
 PhpParser\NodeTraverser->traverseArray() at vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:105
 PhpParser\NodeTraverser->traverseNode() at vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:196
 PhpParser\NodeTraverser->traverseArray() at vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:85
 PhpParser\NodeTraverser->traverse() at vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php:42
 Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse() at vendor/rector/rector/src/Application/FileProcessor.php:60
 Rector\Core\Application\FileProcessor->refactor() at vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php:115
 Rector\Core\Application\FileProcessor\PhpFileProcessor->process() at vendor/rector/rector/src/Application/ApplicationFileProcessor.php:169
 Rector\Core\Application\ApplicationFileProcessor->processFiles() at vendor/rector/rector/src/Application/ApplicationFileProcessor.php:139
 Rector\Core\Application\ApplicationFileProcessor->run() at vendor/rector/rector/src/Console/Command/ProcessCommand.php:120
 Rector\Core\Console\Command\ProcessCommand->execute() at vendor/rector/rector/vendor/symfony/console/Command/Command.php:325
 RectorPrefix202306\Symfony\Component\Console\Command\Command->run() at vendor/rector/rector/vendor/symfony/console/Application.php:944
 RectorPrefix202306\Symfony\Component\Console\Application->doRunCommand() at vendor/rector/rector/vendor/symfony/console/Application.php:326
 RectorPrefix202306\Symfony\Component\Console\Application->doRun() at vendor/rector/rector/src/Console/ConsoleApplication.php:49
 Rector\Core\Console\ConsoleApplication->doRun() at vendor/rector/rector/vendor/symfony/console/Application.php:212
 RectorPrefix202306\Symfony\Component\Console\Application->run() at vendor/rector/rector/bin/rector.php:132
 require_once() at vendor/rector/rector/bin/rector:5
 include() at vendor/bin/rector:119
{code}

This error also happened when I completely empty the file.

**Comment by sabbelasichon** [comment]
Please update to the latest release. Thanks for reporting the issue

**Comment by moritz-ngo** [comment]
Works like charm, thanks for the quick fix!
