### ISSUE TITLE
typo3-rector binary missing

### ISSUE THREAD

**Issue by dev-rke** [sabbelasichon/typo3-rector#4203]
Installation via ```$ composer require --dev ssch/typo3-rector``` causes the following warning 
```
Skipped installation of bin bin/typo3-rector for package ssch/typo3-rector: file not found in package
```

The file ```typo3-rector``` actually does not exist within ```vendor/ssch/typo3-rector/bin/```.

**Comment by Patta** [comment]
Can confirm

**Comment by simonschaufi** [comment]
This bin is creating new rules and is not needed. Use rector instead.

**Comment by dev-rke** [comment]
Hi @simonschaufi 

this is not solved, it seems to me you did not understand the impact of the issue:
When installing the dependency via composer in a blank TYPO3 project, a warning is thrown.
This warning must not be thrown.

In my opinion the definition of typo3-rector in composer.json is wrong:
https://github.com/sabbelasichon/typo3-rector/blob/main/composer.json#L81

**Comment by Patta** [comment]
The composer warning is also thrown on `composer update` command.

**Comment by simonschaufi** [comment]
yes, i completely misunderstood the issue. I'll provide a fix.

**Comment by dev-rke** [comment]
@simonschaufi thank you very much for that quick fix. :-)
