### ISSUE TITLE
Move ExtensionManagementUtility::addStaticFile into TCA Overrides folder

### ISSUE THREAD

**Issue by simonschaufi** [sabbelasichon/typo3-rector#4218]
Write a Rector rule that moves ExtensionManagementUtility::addStaticFile into Configuration/TCA/Overrides/sys_template.php

**Comment by sabbelasichon** [comment]
@simonschaufi Could you add an url to the changelog?

**Comment by simonschaufi** [comment]
I could trace it back to TYPO3 6.2 where no changelogs yet existed: https://review.typo3.org/c/Packages/TYPO3.CMS/+/29484

**Comment by simonschaufi** [comment]
@sabbelasichon I would put it into Code Quality as it doesn't fit to a specific TYPO3 version
