### ISSUE TITLE
Allow nikic/php-parser v5 (TYPO3 13 compatibility)

### ISSUE THREAD

**Issue by kevin-appelt** [sabbelasichon/typo3-rector#4247]
**The issue**

TYPO3 Rector does block the update to the just released TYPO3 v13.1 due to dependency conflicts.

**Composer error message**

```
- Root composer.json requires ssch/typo3-rector 2.5.0 -> satisfiable by ssch/typo3-rector[v2.5.0].
- typo3/cms-install 13.2.x-dev is an alias of typo3/cms-install dev-main and thus requires it to be installed too.
- typo3/cms-install[dev-main, v13.1.0] require nikic/php-parser ^5.0.1 -> satisfiable by nikic/php-parser[v5.0.1, v5.0.2, 5.0.x-dev].
- Conclusion: don't install nikic/php-parser v5.0.2 (conflict analysis result)
- Root composer.json requires typo3/cms-install ^13.1 -> satisfiable by typo3/cms-install[v13.1.0, 13.2.x-dev (alias of dev-main)].
```

**The dependency conflict**

`typo3/cms-install` requires `"nikic/php-parser": "^5.0.1"`
`ssch/typo3-rector` requires `"nikic/php-parser": "^4.18.0"`

**The solution**

Allow installation of `nikic/php-parser` v5 (maybe in addition to v4 if needed/possible).

**This might help somehow**

* [The related require commit from TYPO3](https://github.com/TYPO3/typo3/commit/79fa7333b9e5c61eb1bed60f5758c6a417dfa1b1)
* [The nikic/php-parser upgrade guide for v4=>v5](https://github.com/nikic/PHP-Parser/blob/master/UPGRADE-5.0.md)

**Quickfix**

Just in case someone stumbles across this issue as long as it is not resolved.
Removing TYPO3 Rector (for now) does allow installation of TYPO3 v13.1

**Comment by sabbelasichon** [comment]
@kevin-appelt Thanks for reporting it. We should rather make TYPO3 compatible for v4 and v5 of nikic/php-parser. The task is much more simpler.

**Comment by simonschaufi** [comment]
This is mostly blocked by Rector itself as Rector itself is not compatible with nikic/php-parser v5, see https://github.com/rectorphp/rector/issues/8567

**Comment by mabolek** [comment]
The temporary fix for this issue would be to remove the install core extension (`composer remove typo3/cms-install`) and add it again after running TYPO3 Rector.

**Comment by georgringer** [comment]
thanks @mabolek! you also can't install phpunit (or typo3 testing framework) or yoast_seo which requires ext:install

**Comment by wtfred** [comment]
Hello, just bumped into that issue while trying to update a project from TYPO3 12.4 to 13.4

I'm a bit lost with what is blocking what... What solution do i have if i want to benefit of typo3-rector? I got hooked into using it for last LTS upgrade, and now i would like to use it again :smiling_face_with_tear:

**Comment by georgringer** [comment]
use it in a  directory standalone and you are fine
