### ISSUE TITLE
[BUG] TYPO3 v13 and phpstan 1.11.0

### ISSUE THREAD

**Issue by kevin-appelt** [sabbelasichon/typo3-rector#4270]
### Minimal PHP Code Causing Issue

It's not about some of "my" PHP code.
Issue does not occur with phpstan version 1.10.67, but only 1.11.0

### Applied rules

The issue is within Typo3LevelSetList::UP_TO_TYPO3_13
and even more specific it's this line
https://github.com/sabbelasichon/typo3-rector/blob/main/config/v13/strict-types.php#L955
And to me it looks like 
`new ObjectType('TYPO3\CMS\Core\Resource\FileInterface')`
is the issue, because I can replace it with `new BooleanType()` and rector can be executed again (but the rule if wrong of cause).

### Expected Behaviour

Rector should be usable.

### Package Version

2.5.0

### PHP Version

8.3.6

### TYPO3 Version

13.1.1

**Comment by simonschaufi** [comment]
How did you actually setup rector with TYPO3 13 as they are not directly compatible with each other?
