### ISSUE TITLE
Using $resetSingletonInstances = true; instead of teardown?

### ISSUE THREAD

**Issue by tomasnorre** [sabbelasichon/typo3-rector#4275]
# Question

I have discovered in the TYPO3 Crawler that I have mixed. 

```php
protected bool $resetSingletonInstances = true;
```
and

```php
protected function tearDown(): void
{
    $this->resetSingletonInstances = true;
}
```

Throughout the testing files. I personally prefer the 1st option with the property set, as it's less lines of code, and I rarely don't have teardown methods. 

Would you be interested to have that rector rule in this repository? I consider creating a rule for the Crawler to keep the code aligned with my preferences. But if you could benefit from that rule too, I would be happy to give it a spin and add it here instead. Have the TYPO3 Rector in the Crawler anyway, so not important to me where that rule lives.

**Comment by sabbelasichon** [comment]
@tomasnorre Sure, would love to see the rule in action. But i guess it would better fit to https://github.com/sabbelasichon/typo3-rector-testing-framework

**Comment by tomasnorre** [comment]
You're totally right. Forgot about that rector-package. 
I'll see if I can make it happen.
