### ISSUE TITLE
[BUG]: Exception on install with rector/rector verson 1.2.0

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#4286]
### Minimal PHP Code Causing Issue

Composer setup with latest typo3-rector and 1.2.0 version of rector/rector

Eception
PHP Fatal error:  Uncaught ReflectionException: Class "Rector\Symfony\NodeAnalyzer\Command\SetAliasesMethodCallExtractor" does not exist in /var/www/html/vendor/rector/rector/vendor/illuminate/container/Container.php:782
Stack trace:
#0 /var/www/html/vendor/rector/rector/vendor/illuminate/container/Container.php(782): ReflectionClass->__construct('Rector\\Symfony\\...')
#1 /var/www/html/vendor/rector/rector/vendor/illuminate/container/Container.php(681): RectorPrefix202407\Illuminate\Container\Container->build('Rector\\Symfony\\...')

### Applied rules

-

### Expected Behaviour

- 

### Package Version

2.6.1

### PHP Version

8.1

### TYPO3 Version

12.4

**Comment by mbrodala** [comment]
This duplicates https://github.com/sabbelasichon/typo3-rector/issues/4285
