### ISSUE TITLE
[BUG]: TYPO3_MODE

### ISSUE THREAD

**Issue by die-netwerker** [sabbelasichon/typo3-rector#4293]
### Minimal PHP Code Causing Issue

<?php

call_user_func(
    function()
    {
        if (TYPO3_MODE === 'BE')
        {
}
}
);

### Applied rules

        Typo3SetList::CODE_QUALITY,
        Typo3SetList::GENERAL,
        Typo3SetList::TYPO3_12

### Expected Behaviour

TYPO3_MODE is removed in v12 and should be converted to the new code, but nothing happens.

### Package Version

2.6.4

### PHP Version

8.3.8

### TYPO3 Version

12.4.17

**Comment by helsner** [comment]
@die-netwerker seems like the code example got missing!
i remember it was something along {... if (TYPO_MODE === 'BE'){} ... } which was wrapped in a call_user_function

**Comment by die-netwerker** [comment]
`<?php

call_user_func(
    function()
    {
        if (TYPO3_MODE === 'BE')
        {`

**Comment by helsner** [comment]
i cannot reproduce this in our tests, but i can in my demo project.. this is pretty strange.
maybe @simonschaufi or @sabbelasichon understand whats going on?
you can simply checkout https://github.com/helsner/typo3-rector-demo and add the test code to verify

**Comment by simonschaufi** [comment]
maybe this rule is too old and got deleted in v2?

**Comment by helsner** [comment]
should be `SubstituteConstantsModeAndRequestTypeRector`

**Comment by simonschaufi** [comment]
This works as expected:

```
<?php

namespace Ssch\TYPO3Rector\Tests\Rector\v11\v0\SubstituteConstantsModeAndRequestTypeRector\Fixture;

call_user_func(
    function() {
        if (TYPO3_MODE === 'BE') {
            // Do something
        }
    }
);
?>
-----
<?php

namespace Ssch\TYPO3Rector\Tests\Rector\v11\v0\SubstituteConstantsModeAndRequestTypeRector\Fixture;

use TYPO3\CMS\Core\Http\ApplicationType;

call_user_func(
    function() {
        if (ApplicationType::fromRequest($GLOBALS['TYPO3_REQUEST'])->isBackend()) {
            // Do something
        }
    }
);
?>
```

if not, please show us a code example which is not working.
