### ISSUE TITLE
[BUG]: SimplifyCheckboxItemsTCARector removes non-empty labels (TYPO3 11)

### ISSUE THREAD

**Issue by LeoniePhiline** [sabbelasichon/typo3-rector#4298]
### Minimal PHP Code Causing Issue

```php
<?php

return [
  'columns' => [
     'col_name' => [
         'config'   => [
             'type'       => 'check',
             'renderType' => 'checkboxToggle',
             'items'      => [
                 ['LLL:EXT:some_extension/Resources/Private/Language/locallang_db.xlf:some_label', ''],
             ],
         ],
     ],
  ],
];
```

### Applied rules

`SimplifyCheckboxItemsTCARector`

### Expected Behaviour

```php
<?php

return [
  'columns' => [
     'col_name' => [
         'config'   => [
             'type'       => 'check',
             'renderType' => 'checkboxToggle',
             'items'      => [
                 [0 => 'LLL:EXT:some_extension/Resources/Private/Language/locallang_db.xlf:some_label'],
             ],
         ],
     ],
  ],
];
```

Note: Manually changing `['LLL:EXT:some_extension/Resources/Private/Language/locallang_db.xlf:some_label', '']` to `[0 => 'LLL:EXT:some_extension/Resources/Private/Language/locallang_db.xlf:some_label']` prevents `SimplifyCheckboxItemsTCARector` from triggering and falsely removing the label.

### Package Version

2.6.4

### PHP Version

8.3.10

### TYPO3 Version

11.5.38

### Notes

Actual behavior:

```php
<?php

return [
  'columns' => [
     'col_name' => [
         'config'   => [
             'type'       => 'check',
             'renderType' => 'checkboxToggle',
         ],
     ],
  ],
];
```

The `['items'][...][0]` label gets lost even if it is non-empty. Docs: https://docs.typo3.org/m/typo3/reference-tca/11.5/en-us/ColumnsConfig/Type/Check/Toggle.html#tca_example_checkbox_17

Later, for TYPO3 12, the `0 => ` will be translated into `'label' => `. Docs: https://docs.typo3.org/m/typo3/reference-tca/12.4/en-us/ColumnsConfig/Type/Check/Toggle.html#columns-check-checkboxToggle-examples-17

**Comment by helsner** [comment]
@simonschaufi // @sabbelasichon 
Here it is kinda the question what we want to do.
Basically the original config is wrong, that's why the items config gets killed.
Should we still check for this and prevent a removal?

**Comment by LeoniePhiline** [comment]
In which way is the original config wrong?
