### ISSUE TITLE
[BUG] Rule ExtbaseControllerActionsMustReturnResponseInterfaceRector is not working

### ISSUE THREAD

**Issue by nollm** [sabbelasichon/typo3-rector#4320]
### Minimal PHP Code Causing Issue

I think the if condition here is not correct.

https://github.com/sabbelasichon/typo3-rector/blob/v2.9.2/rules/TYPO311/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector.php#L184
```
if (! $this->nodeTypeResolver->isMethodStaticCallOrClassMethodObjectType(
    $classMethod,
    new ObjectType('TYPO3\CMS\Extbase\Mvc\Controller\ActionController')
)) {
    return true;
}
```

### Applied rules

ExtbaseControllerActionsMustReturnResponseInterfaceRector

### Expected Behaviour

In my opinion the negation is wrong. If the controller is of type ActionController it should not be skipped.

```diff
- if (! $this->nodeTypeResolver->isMethodStaticCallOrClassMethodObjectType(
+ if ($this->nodeTypeResolver->isMethodStaticCallOrClassMethodObjectType(
    $classMethod,
    new ObjectType('TYPO3\CMS\Extbase\Mvc\Controller\ActionController')
)) {
    return true;
}
```

### Package Version

2.9.2

### PHP Version

8.2.22

### TYPO3 Version

12.4.20

**Comment by simonschaufi** [comment]
We have tests that prove that it is working. The rule should be skipped, if the class is not extending ActionController, so this is double negation.
