### ISSUE TITLE
[BUG] UseServerRequestInsteadOfGeneralUtilityGetRector might introduce notices

### ISSUE THREAD

**Issue by georgringer** [sabbelasichon/typo3-rector#4392]
### Minimal PHP Code Causing Issue

```diff
-        $post = GeneralUtility::_POST('xxx');
+        $post = $this->request->getParsedBody()['xxx'];
```

### Applied rules

UseServerRequestInsteadOfGeneralUtilityGetRector
UseServerRequestInsteadOfGeneralUtilityPostRector

### Expected Behaviour

I guess `$post = $this->request->getParsedBody()['xxx'] ?? null;` would be tter

### Package Version

2.10.2

### PHP Version

8.3.0

### TYPO3 Version

13.4

### Notes

see #4181 and #4182

**Comment by simonschaufi** [comment]
We actually had this with a null coalesce behavior bevor and then removed it again. I fixed it now properly.
