### ISSUE TITLE
[BUG] Redirect response is not correctly migrated

### ISSUE THREAD

**Issue by georgringer** [sabbelasichon/typo3-rector#4393]
### Minimal PHP Code Causing Issue

```
public function createStep3Action(Step3 $step3) {
    $this->redirect('index');
}
```

### Applied rules

ExtbaseControllerActionsMustReturnResponseInterfaceRector

### Expected Behaviour

it is migrated to

```
public function createStep3Action(Step3 $step3): void {
    $this->redirect('index');
}
```

but the correct change would be

```
public function createStep3Action(Step3 $step3): ResponseInterface {
    return $this->redirect('index');
}
```

### Package Version

2.10

### PHP Version

8.3

### TYPO3 Version

13

**Comment by simonschaufi** [comment]
ok, I see the issue. The rule is already available in TYPO3 11 but in TYPO3 11 the redirect was not yet migrated to return a ResponseInterface. That was only done in TYPO3 12. This was a bit messed up in TYPO3 11.

I'll provide a rule that just targets the redirects for v12.
