### ISSUE TITLE
[BUG]:  AddErrorCodeToExceptionRector always adds code even if the exception dose not have that parameter

### ISSUE THREAD

**Issue by Kanti** [sabbelasichon/typo3-rector#4445]
### Minimal PHP Code Causing Issue

````php
throw new \Symfony\Component\Process\Exception\ProcessFailedException($process);
````

Signature of `ProcessFailedException` looks like this:
````php
public function __construct(Process $process)
````

It dose not have a `$code` parameter.

### Applied rules

AddErrorCodeToExceptionRector

### Expected Behaviour

do nothing instead

### Package Version

2.11.0

### PHP Version

8.2.0

### TYPO3 Version

11.5.41

**Comment by simonschaufi** [comment]
Please exclude this file manually yourself like so:

```php
->withSkip([
AddErrorCodeToExceptionRector::class => [
__dir__ . '/path/to/file.php'
])
```
Rector cannot easily detect if the class supports an error code.
