### ISSUE TITLE
[BUG] InjectMethodToConstructorInjectionRector uses wrong variable name

### ISSUE THREAD

**Issue by cweiske** [sabbelasichon/typo3-rector#4447]
### Minimal PHP Code Causing Issue

```
class Foo
{
    public function injectApiClient(ApiService $service): void
    {
        $this->apiClient = $service;
    }
}
```

gets converted to

```
class Foo
{
    public function __construct(\Vendor\ApiService $service): void
    {
        $this->service = $service;
    }
}
```

which is not the variable that is used by the class methods.

### Applied rules

InjectMethodToConstructorInjectionRector

### Expected Behaviour

Rector should use the assigned variable name instead of the variable name in the depencendy injection method signature.

### Package Version

2.11.0

### PHP Version

8.3.13

### TYPO3 Version

10.4.37

### Notes

The variable name of the inject method signature is different from the assigned class variable name.

**Comment by simonschaufi** [comment]
This is a rector core bug, well, more like a missing feature. Rector doesn't allow creating constructor properties with a different property name. For rector they need to match.

Since all rector classes are final, there is not even the possibility to patch the classes with a custom one for us.

So the only possibility is to adjust your php code and match the parameter with the property name. Sorry.

**Comment by cweiske** [comment]
> Rector doesn't allow creating constructor properties with a different property name. For rector they need to match.

If the injector property name would be renamed at first, then it all would work. There is no need to "create constructor properties with a different property name".

But as it is now, typo3-rector breaks working code without a single warning. This should not be. Running the automatic adjustments should not break code; at least that is my expectation.

**Comment by simonschaufi** [comment]
Good idea! I fixed it with your proposed solution

**Comment by cweiske** [comment]
That was quick! Thank you!.
