### ISSUE TITLE
[BUG] Rector change a complete Function Call to null

### ISSUE THREAD

**Issue by hdietrich-timespin** [sabbelasichon/typo3-rector#4459]
### Minimal PHP Code Causing Issue

Rector move in my own Static-Function  
/typo3conf/ext/myExtension/Classes/Domain/Model/Calculationvalues::createInstanceByLoadingFromEntity($entity) a parent Function  call createInstanceByLoadingFromEntity to null.  

DIFF:
![grafik](https://github.com/user-attachments/assets/44eb30a8-ad27-4e3e-9abc-bead81eab2e4)
![grafik](https://github.com/user-attachments/assets/b24c27b5-07a8-4a2f-90ae-dbbf6acb3821)

The Parent funktion is in a other Extension: 
\Timespin\OtherExtension\Domain\Model\Traits\BaseModel::createInstanceByLoadingFromEntity

I think it is because it occurs when saving the class from the reflection framework. Because if the Rector's rules do not find anything in this class, the class does not need to be saved. And this line is not handled by the Rector rules. It is just a phenomenon that occurs when saving other changes, such as here by the param Annotation:

![grafik](https://github.com/user-attachments/assets/50d8c353-f7ca-4668-ae20-bd3e8c69feea)
![grafik](https://github.com/user-attachments/assets/725cd341-7b4f-4582-96b9-1901ed88256b)

if I remove the param Annotation before rector. Rector say the class is ok.:
![grafik](https://github.com/user-attachments/assets/55abee55-cb12-481f-8bd1-03ea4d99f19b)

 

### Applied rules

    ->withSets([
        Typo3LevelSetList::UP_TO_TYPO3_12,
        LevelSetList::UP_TO_PHP_81,
    ])
    // uncomment to reach your current PHP version
    // ->withPhpSets()
    ->withRules([
        AddVoidReturnTypeWhereNoReturnRector::class,
    ]);

### Expected Behaviour

Do not  remove:
![grafik](https://github.com/user-attachments/assets/51c779bb-7135-4469-963d-067044fe6531)

### Package Version

2.0.0

### PHP Version

8.2.26

### TYPO3 Version

12.4.21

**Comment by hdietrich-timespin** [comment]
I have update typo3-rector to 2.12.0 and the Error was away!

**Comment by simonschaufi** [comment]
The problem is that you didn't even tell us which rule applied the code change. Without that we can't help you. It could also be something from rector core but our rules from TYPO3 don't change these kind of php code.
