### ISSUE TITLE
[BUG] "System error: "MigrateBackendModuleRegistrationRector::getAccess(): Argument #1 ($access) must be of type string, null given, called in MigrateBackendModuleRegistrationRector.php337"

### ISSUE THREAD

**Issue by georgringer** [sabbelasichon/typo3-rector#4462]
### Minimal PHP Code Causing Issue

```php
\TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerModule(
    'XXForms',
    'web',
    'tx_xxxorms_m1',
    '',
    [\Vendor\XXForms\Controller\BackendController::class => 'index,export'],
    [
        'labels' => 'LLL:EXT:xx_forms/Resources/Private/Language/locallang_mod.xlf',
    ]
);
```

Problem is that the array key `access` is not set. TBH I don't know if this is an error or not but current code of rector looks like
```
$returnArray[$moduleIdentifier]['access'] = $this->getAccess($moduleArray['access']);
```

### Applied rules

MigrateBackendModuleRegistrationRector

### Expected Behaviour

no error

### Package Version

2.12

### PHP Version

8.3

### TYPO3 Version

13.4

**Comment by simonschaufi** [comment]
Is this value optional? It would be helpful to have a link to the documentation.

**Comment by georgringer** [comment]
TBH haven't really found anything but even if it is required, it must not lead to the situation that rector breaks! it could be handled with `admin` as defensive fallback

**Comment by simonschaufi** [comment]
the changelog documents: 'user', 'admin' or 'systemMaintainer', so what permissions get applied, if no value is provided?

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-96733-NewBackendModuleRegistrationAPI.html#module-configuration-options
