### ISSUE TITLE
Breaking: #72370 - Removed deprecated code from extbase


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#473]
Breaking: #72370 - Removed deprecated code from extbase

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.0/Breaking-72370-RemovedDeprecatedCodeFromExtbase.html

.. include:: ../../Includes.txt

=======================================================

Breaking: #72370 - Removed deprecated code from extbase

=======================================================

See :issue:`72370`

Description

===========

Remove deprecated code from extbase

The ChangeLog file has been removed.

`TYPO3\CMS\Extbase\DomainObject\AbstractDomainObject::__wakeup()` has been removed.

`TYPO3\CMS\Extbase\Utility\ExtensionUtility::configureModule()` has been removed.

Impact

======

Using the methods above directly in any third party extension will result in a fatal error.

Affected Installations

======================

Instances which use calls to the methods above.

Migration

=========

Use the according method in `\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::configureModule()` instead of the removed one from ext:extbase.

Objects are instantiated differently calling `parent::__wakeup()` is no longer necessary. No migration needed.

.. index:: PHP-API, ext:extbase

**Comment by verdure-peuser** [comment]
Readme says i should assign this issue if i want to contribute. Seems like i have no permission for it.
So i just write it down, i'd like to try this one :)

**Comment by tmotyl** [comment]
@verdure-peuser also feel invited to the #ext-typo3-rector slack channel on typo3 slack.

**Comment by sabbelasichon** [comment]
@verdure-peuser Yeah. I assigned you to this issue. Ask me anything either via direct message or the slack channel.
