### ISSUE TITLE
Deprecation: #73794 - SearchFormController->utf8_to_currentCharset and TSFE->renderCharset


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#487]
Deprecation: #73794 - SearchFormController->utf8_to_currentCharset and TSFE->renderCharset

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.0/Deprecation-73794-SearchFormController-utf8_to_currentCharsetAndTSFE-renderCharset.html

.. include:: ../../Includes.txt

==========================================================================================

Deprecation: #73794 - SearchFormController->utf8_to_currentCharset and TSFE->renderCharset

==========================================================================================

See :issue:`73794`

Description

===========

The public method `SearchFormController->utf8_to_currentCharset()` within indexed search has been marked as

deprecated.

The public property `TypoScriptFrontendController->renderCharset` has been marked as deprecated.

Impact

======

Calling the method above will result in a deprecation log entry.

Affected Installations

======================

Any installation that extends Indexed Search and uses this method, and any extension that accesses `TSFE->renderCharset` via TypoScript or PHP directly.

Migration

=========

Remove any calls to the method and the public property.

.. index:: PHP-API, Frontend

**Comment by tomasnorre** [comment]
Does this part 
> TypoScript or PHP directly.

Change the to-do what needs to be done here? Not sure about the TypoScript path or is it enough to make sure that the property or function isn't used?

**Comment by sabbelasichon** [comment]
This is not really solvable. Because you cannot just remote the node without knowing the users intention. That will probably break the code.
