### ISSUE TITLE
Deprecation: #71255 - ExtendedFileUtility::pushErrorMessagesToFlashMessageQueue()


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#500]
Deprecation: #71255 - ExtendedFileUtility::pushErrorMessagesToFlashMessageQueue()

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.0/Deprecation-71255-ExtendedFileUtilitypushErrorMessagesToFlashMessageQueue.html

.. include:: ../../Includes.txt

=================================================================================

Deprecation: #71255 - ExtendedFileUtility::pushErrorMessagesToFlashMessageQueue()

=================================================================================

See :issue:`71255`

Description

===========

Method `\TYPO3\CMS\Core\Utility\File\ExtendedFileUtility::pushErrorMessagesToFlashMessageQueue()` has been marked as deprecated.

Impact

======

Using the method will trigger a deprecation log entry.

Affected Installations

======================

Instances with custom backend modules that use this method.

Migration

=========

Implement the method by yourself.

.. index:: PHP-API, FAL

**Comment by tomasnorre** [comment]
This one I'm not sure out. Migration `Implement the method by yourself` can be done in many ways. Not sure how to do a rector for that approach.
