### ISSUE TITLE
Deprecation: #68748 - Deprecate AbstractContentObject::getContentObject()


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#501]
Deprecation: #68748 - Deprecate AbstractContentObject::getContentObject()

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.0/Deprecation-68748-DeprecateAbstractContentObjectgetContentObject.html

.. include:: ../../Includes.txt

=========================================================================

Deprecation: #68748 - Deprecate AbstractContentObject::getContentObject()

=========================================================================

See :issue:`68748`

Description

===========

The method has been renamed to `getContentObjectRenderer()`. The old method name is

still present as a deprecated alias, which will be removed in TYPO3 v9.

Impact

======

Calling this method will trigger a deprecation log entry.

Affected Installations

======================

Any extensions calling `getContentObject()`.

Migration

=========

Replace calls to `getContentObject()` with `getContentObjectRenderer()`.

.. index:: PHP-API, Frontend

**Comment by josefglatz** [comment]
@sabbelasichon is this something which is a false-positive in extensin scanner of core? Or how do you fix this?
