### ISSUE TITLE
Deprecation: #71917 - Deprecate the argument 'hsc' for getLL, getLLL, sL and pi_getLL


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#536]
Deprecation: #71917 - Deprecate the argument 'hsc' for getLL, getLLL, sL and pi_getLL

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.2/Deprecation-71917-DeprecateTheArgumentHscForGetLLGetLLLAndSL.html

.. include:: ../../Includes.txt

=====================================================================================

Deprecation: #71917 - Deprecate the argument 'hsc' for getLL, getLLL, sL and pi_getLL

=====================================================================================

See :issue:`71917`

Description

===========

The parameter :php:`$hsc` within the following methods of :php:`TYPO3\CMS\Lang\LanguageService` has been marked as deprecated:

* :php:`getLL()`

* :php:`getLLL()`

* :php:`sL()`

The parameter :php:`$hsc` within the following method of :php:`TYPO3\CMS\Frontend\Plugin\AbstractPlugin` has been marked as deprecated:

* :php:`pi_getLL()`

Impact

======

Directly or indirectly using any of the methods :php:`getLL()`, :php:`getLLL()`, :php:`sL()` or :php:`pi_getLL()` with the parameter :php:`$hsc` will trigger a deprecation log entry.

Affected Installations

======================

Any installation with a third-party extension calling one of the methods in its PHP code.

Migration

=========

If the return value of these methods is output in HTML context use :php:`htmlspecialchars` directly to properly escape the content.

.. index:: Frontend, Backend, PHP-API

**Comment by tomasnorre** [comment]
How should this be done? This part is making me insecure. If I did it manually no problems, but as it's automated not sure.
> If the return value of these methods is output in HTML context use :php:htmlspecialchars directly to properly escape the content.

**Comment by sabbelasichon** [comment]
Be aware of $GLOBALS['LANG']
