### ISSUE TITLE
Deprecation: #77557 - Method QueryView->tableWrap()


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#578]
Deprecation: #77557 - Method QueryView->tableWrap()

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.3/Deprecation-77557-MethodQueryView-tableWrap.html

.. include:: ../../Includes.txt

===================================================

Deprecation: #77557 - Method QueryView->tableWrap()

===================================================

See :issue:`77557`

Description

===========

Method :php:`QueryView->tableWrap()` has been marked as deprecated.

Impact

======

Extensions using this method will trigger a deprecation log entry.

Affected Installations

======================

Extensions using :php:`QueryView->tableWrap()`

Migration

=========

Use :php:`'<pre>' . $str . '</pre>'` instead.

.. index:: PHP-API, Backend

**Comment by tomasnorre** [comment]
I'm on this one.

**Comment by tomasnorre** [comment]
I'm getting into troubles every time I have to work with Echo_, Constants or wrapping html like here :(
