### ISSUE TITLE
Deprecation: #77826 - RTEHtmlArea Spellchecker entrypoint


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#622]
Deprecation: #77826 - RTEHtmlArea Spellchecker entrypoint

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.4/Deprecation-77826-RTEHtmlAreaSpellcheckerEntrypoint.html

.. include:: ../../Includes.txt

=========================================================

Deprecation: #77826 - RTEHtmlArea Spellchecker entrypoint

=========================================================

See :issue:`77826`

Description

===========

The entry point for HTTP Requests `SpellCheckingController->main` within RTEHtmlArea has been marked as deprecated.

Impact

======

Calling the PHP method above will trigger a deprecation log entry.

Affected Installations

======================

All TYPO3 instances calling this PHP method.

Migration

=========

Use `SpellCheckingController->processRequest` instead.

.. index:: PHP-API, RTE, Backend

**Comment by tomasnorre** [comment]
Have assigned myself, but will wait till https://github.com/sabbelasichon/typo3-rector/pull/1650 is done and merged, as it's will use/need the same file that doesn't exist yet, so to avoid conflict. 

But it's fast done when the other is merged.

**Comment by sabbelasichon** [comment]
Resolved by #1689
