### ISSUE TITLE
Deprecation: #80440 - EXT:lowlevel ArrayBrowser->wrapValue


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#738]
Deprecation: #80440 - EXT:lowlevel ArrayBrowser->wrapValue

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.7/Deprecation-80440-EXTlowlevelArrayBrowser-wrapValue.html

.. include:: ../../Includes.txt

==========================================================

Deprecation: #80440 - EXT:lowlevel ArrayBrowser->wrapValue

==========================================================

See :issue:`80440`

Description

===========

The method :php:`ArrayBrowser->wrapValue` in EXT:lowlevel has been marked as deprecated, since the sole

logic was to wrap the incoming string into :php:`htmlspecialchars()`.

Impact

======

Calling the method will trigger a deprecation warning.

Affected Installations

======================

Any TYPO3 installation using the EXT:lowlevel ArrayBrowser class in a custom extension.

Migration

=========

Remove the call to the method and directly use :php:`htmlspecialchars()` instead.

.. index:: PHP-API, ext:lowlevel

**Comment by sabbelasichon** [comment]
Easy pick

**Comment by tomasnorre** [comment]
I'll fix this one. I'm awaiting feedback on some other, but want to use the momentum and have things done :)
