### ISSUE TITLE
Deprecation: #80053 - Extbase CLI Console Output different method signature for infinite attempts


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#741]
Deprecation: #80053 - Extbase CLI Console Output different method signature for infinite attempts

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.7/Deprecation-80053-ExtbaseCLIConsoleOutputDifferentMethodSignatureForInfiniteAttempts.html

.. include:: ../../Includes.txt

=================================================================================================

Deprecation: #80053 - Extbase CLI Console Output different method signature for infinite attempts

=================================================================================================

See :issue:`80053`

Description

===========

When using Extbase's CLI functionality to ask for a question via :php:`ConsoleOutput->select()` or

:php:`ConsoleOutput->askAndValidate()` the option to define infinite attempts has changed from "false"

to "null".

Impact

======

Calling any of the methods with :php:`$attempts = false` will trigger a deprecation log entry.

Affected Installations

======================

Any TYPO3 extension shipping custom CLI commands for Extbase using the methods above with the option

to have infinite attempts.

Migration

=========

Set the method argument from "false" to "null" in the Extbase Command of your extension.

.. index:: CLI, ext:extbase, PHP-API

**Comment by tomasnorre** [comment]
I was close to being done when I saw this was already done. 
https://github.com/sabbelasichon/typo3-rector/blob/master/src/Rector/v8/v7/ChangeAttemptsParameterConsoleOutputRector.php

Issue can be closed.
