### ISSUE TITLE
Deprecation: #80514 - GraphicalFunctions->tempPath and createTempSubDir()


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#763]
Deprecation: #80514 - GraphicalFunctions->tempPath and createTempSubDir()

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.7/Deprecation-80514-GraphicalFunctions-tempPathAndCreateTempSubDir.html

.. include:: ../../Includes.txt

=========================================================================

Deprecation: #80514 - GraphicalFunctions->tempPath and createTempSubDir()

=========================================================================

See :issue:`80514`

Description

===========

The method :php:`GraphicalFunctions->createTempSubDir()` and the property

:php:`GraphicalFunctions->tempPath` have been marked as deprecated.

Impact

======

Calling the method above will trigger a deprecation log entry.

Affected Installations

======================

Any instance with custom extensions extending the PHP class GraphicalFunctions.

Migration

=========

Use :php:`GeneralUtility::mkdir_deep()` with the full path (including the PHP constant `PATH_site`)

directly.

.. index:: PHP-API

**Comment by tomasnorre** [comment]
This looks like it can be inspired if not reused from here:
https://github.com/sabbelasichon/typo3-rector/issues/838
