### ISSUE TITLE
Deprecation: #80445 - Deprecate printContent methods


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#772]
Deprecation: #80445 - Deprecate printContent methods

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.7/Deprecation-80445-DeprecatePrintContentMethods.html

.. include:: ../../Includes.txt

====================================================

Deprecation: #80445 - Deprecate printContent methods

====================================================

See :issue:`80445`

Description

===========

The methods :php:`TaskModuleController::printContent()` and :php:`PageLayoutController::printContent()`  have been marked as deprecated.

Impact

======

Calling the deprecated methods will trigger a deprecation log entry.

.. index:: Backend, PHP-API

**Comment by sabbelasichon** [comment]
For TaskModuleController: Migrate to "echo TaskModuleController->content"
For PageLayoutController: Migrate to "echo PageLayoutController->getModuleTemplate()->renderContent()

**Comment by tomasnorre** [comment]
This sounds like an easy pick to me too. Should I give it a go?

**Comment by tomasnorre** [comment]
Morning. 

I'm close to being done with this one. But struggling with two things. 

1) Adding the `echo` to the return values in general. I have the function call build as needed, but the `echo` part I haven't figured out yet how to do. If I use `$this->createFuncCall('echo', ['arguments']);` it do it with `echo(arguments)` and I don't what that.

2) I haven't figured out how to echo the `TaskModuleController->content` property. 

It's probably two really easy things, but currently I cannot get my head around it. Hope you can give me some pointers. 

```php
if ($this->isMethodStaticCallOrClassMethodObjectType($node, PageLayoutController::class)) {
    return $this->createMethodCall($this->createMethodCall($node->var, 'getModuleTemplate'), 'renderContent');
}

if ($this->isMethodStaticCallOrClassMethodObjectType($node, TaskModuleController::class)) {
    return $this->getValue($node->var);
}
```

**Comment by sabbelasichon** [comment]
@tomasnorre Echo is actually not a function it is language construct. For this you have to create the special Node new Node\Stmt\Echo_(). And to get the property content from the class TaskModuleController you can use the helper method $this->createPropertyFetch($node->var, 'content');

**Comment by tomasnorre** [comment]
Hmm. The property part I thought I had tried out, but if so in a combination with something else that didn't work. Works now :) 

The echo is not working for me. I found this documentation from Rector.
https://github.com/rectorphp/rector/blob/3b1e31ef8c/docs/nodes_overview.md#phpparsernodestmtecho_

The example here isn't working for me throwing and exception. 
`LogicException: Trying to replace expression (Expr_MethodCall) with statement (Stmt_Echo)` 

Will look more into this. You have already given me some good pointers. Thanks.

**Comment by tomasnorre** [comment]
It looks like I need some more concrete pointers regarding the echo part :( I don't get my head around how this should look like.

**Comment by sabbelasichon** [comment]
@tomasnorre Have a look at: https://github.com/sabbelasichon/typo3-rector/pull/1636

**Comment by tomasnorre** [comment]
Thanks @sabbelasichon, will you merged yours or should I adjust mine? The looks the same besides the part with the echo that I didn't figure out.

**Comment by tomasnorre** [comment]
I thought I had pushed this, but only locally as the echo part wasn't done yet. So you can merge yours.
