### ISSUE TITLE
Deprecation: #79580 - Deprecate methods in DataHandler related to page delete access


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#781]
Deprecation: #79580 - Deprecate methods in DataHandler related to page delete access

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.7/Deprecation-79580-MethodsInDataHandlerRelatedToPageDeleteAccess.html

.. include:: ../../Includes.txt

====================================================================================

Deprecation: #79580 - Deprecate methods in DataHandler related to page delete access

====================================================================================

See :issue:`79580`

Description

===========

The following methods have been marked as deprecated:

* :php:`TYPO3\CMS\Core\DataHandling\DataHandler->rmComma()`

* :php:`TYPO3\CMS\Core\DataHandling\DataHandler->noRecordsFromUnallowedTables()`

Impact

======

Calling these methods will trigger a deprecation log entry.

Affected Installations

======================

Any TYPO3 extension calling one of these methods.

Migration

=========

Use native :php:`rtrim($input, ',')` instead of :php:`TYPO3\CMS\Core\DataHandling\DataHandler->rmComma()`.

No migration available for :php:`TYPO3\CMS\Core\DataHandling\DataHandler->noRecordsFromUnallowedTables()`.

.. index:: Database, PHP-API, Backend

**Comment by Tuurlijk** [comment]
@sabbelasichon Do we close this? There is no migration available for `noRecordsFromUnallowedTables`

**Comment by sabbelasichon** [comment]
@Tuurlijk Yes.
