### ISSUE TITLE
Deprecation: #83093 - Replace @cascade with @TYPO3\\CMS\\Extbase\\Annotation\\ORM\\Cascade


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#839]
Deprecation: #83093 - Replace @cascade with @TYPO3\\CMS\\Extbase\\Annotation\\ORM\\Cascade

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Deprecation-83093-ReplaceCascadeWithTYPO3CMSExtbaseAnnotationORMCascade.html

.. include:: ../../Includes.txt

==========================================================================================

Deprecation: #83093 - Replace @cascade with @TYPO3\\CMS\\Extbase\\Annotation\\ORM\\Cascade

==========================================================================================

See :issue:`83093`

Description

===========

The :php:`@cascade` annotation has been deprecated and must be replaced with the doctrine annotation

:php:`@TYPO3\CMS\Extbase\Annotation\ORM\Cascade`.

Impact

======

From version 9.0 on, :php:`@cascade` is deprecated and will be removed in version 10.

Affected Installations

======================

All extensions that use :php:`@cascade`

Migration

=========

Use :php:`@TYPO3\CMS\Extbase\Annotation\ORM\Cascade` instead.

A tyical example has been :php:`@cascade remove` which is now :php:`@TYPO3\CMS\Extbase\Annotation\ORM\Cascade("remove")`

.. index:: PHP-API, ext:extbase, FullyScanned

**Comment by sabbelasichon** [comment]
This is done by https://github.com/sabbelasichon/typo3-rector/blob/master/src/Rector/Annotation/CascadeAnnotationRector.php

**Comment by ayacoo** [comment]
Should we check for CamelCase variant?, too? We had "Cascade" instead of "cascade" and the rector does not found anything.

**Comment by sabbelasichon** [comment]
Yes, should be doable. Are you going to open a PR for it?
