### ISSUE TITLE
Deprecation: #81434 - String Cache Frontend Deprecated


### ISSUE THREAD

**Issue by sabbelasichon** [sabbelasichon/typo3-rector#980]
Deprecation: #81434 - String Cache Frontend Deprecated

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.2/Deprecation-81434-StringCacheFrontendDeprecated.html

.. include:: ../../Includes.txt

======================================================

Deprecation: #81434 - String Cache Frontend Deprecated

======================================================

See :issue:`81434`

Description

===========

The `StringFrontend` cache frontend has been marked as deprecated in favor of `VariableFrontend`.

Impact

======

Using `TYPO3\CMS\Core\Cache\Frontend\StringFrontend` will trigger a deprecation warning.

Affected Installations

======================

Any TYPO3 installation which defines any custom cache using `StringFrontend`.

Migration

=========

Replace `TYPO3\CMS\Core\Cache\Frontend\StringFrontend` occurrences in cache configurations with `TYPO3\CMS\Core\Cache\Frontend\VariableFrontend`.

.. index:: PHP-API, NotScanned

**Comment by Jashi** [comment]
I'll try my hand at this one.
